#!/usr/bin/env zsh
export K9S_CONFIG_DIR=$XDG_CONFIG_HOME/k9s

compdef _kubectl kubecolor
compdef _kubectl k

alias k='kubecolor'
alias ksys='kubecolor --namespace=kube-system'
alias ka='kubecolor apply --recursive -f'
alias ksysa='kubecolor --namespace=kube-system apply --recursive -f'
alias kak='kubecolor apply -k'
alias kk='kubecolor kustomize'
alias kex='kubecolor exec -i -t'
alias ksysex='kubecolor --namespace=kube-system exec -i -t'
alias klo='kubecolor logs -f'
alias ksyslo='kubecolor --namespace=kube-system logs -f'
alias klop='kubecolor logs -f -p'
alias ksyslop='kubecolor --namespace=kube-system logs -f -p'
alias kp='kubecolor proxy'
alias kpf='kubecolor port-forward'
alias kg='kubecolor get'
alias ksysg='kubecolor --namespace=kube-system get'
alias kd='kubecolor describe'
alias ksysd='kubecolor --namespace=kube-system describe'
alias krm='kubecolor delete'
alias ksysrm='kubecolor --namespace=kube-system delete'
alias krun='kubecolor run --rm --restart=Never --image-pull-policy=IfNotPresent -i -t'
alias ksysrun='kubecolor --namespace=kube-system run --rm --restart=Never --image-pull-policy=IfNotPresent -i -t'
alias kgpo='kubecolor get pods'
alias ksysgpo='kubecolor --namespace=kube-system get pods'
alias kdpo='kubecolor describe pods'
alias ksysdpo='kubecolor --namespace=kube-system describe pods'
alias krmpo='kubecolor delete pods'
alias ksysrmpo='kubecolor --namespace=kube-system delete pods'
alias kgdep='kubecolor get deployment'
alias ksysgdep='kubecolor --namespace=kube-system get deployment'
alias kddep='kubecolor describe deployment'
alias ksysddep='kubecolor --namespace=kube-system describe deployment'
alias krmdep='kubecolor delete deployment'
alias ksysrmdep='kubecolor --namespace=kube-system delete deployment'
alias kgsts='kubecolor get statefulset'
alias ksysgsts='kubecolor --namespace=kube-system get statefulset'
alias kdsts='kubecolor describe statefulset'
alias ksysdsts='kubecolor --namespace=kube-system describe statefulset'
alias krmsts='kubecolor delete statefulset'
alias ksysrmsts='kubecolor --namespace=kube-system delete statefulset'
alias kgsvc='kubecolor get service'
alias ksysgsvc='kubecolor --namespace=kube-system get service'
alias kdsvc='kubecolor describe service'
alias ksysdsvc='kubecolor --namespace=kube-system describe service'
alias krmsvc='kubecolor delete service'
alias ksysrmsvc='kubecolor --namespace=kube-system delete service'
alias kging='kubecolor get ingress'
alias ksysging='kubecolor --namespace=kube-system get ingress'
alias kding='kubecolor describe ingress'
alias ksysding='kubecolor --namespace=kube-system describe ingress'
alias krming='kubecolor delete ingress'
alias ksysrming='kubecolor --namespace=kube-system delete ingress'
alias kgcm='kubecolor get configmap'
alias ksysgcm='kubecolor --namespace=kube-system get configmap'
alias kdcm='kubecolor describe configmap'
alias ksysdcm='kubecolor --namespace=kube-system describe configmap'
alias krmcm='kubecolor delete configmap'
alias ksysrmcm='kubecolor --namespace=kube-system delete configmap'
alias kgsec='kubecolor get secret'
alias ksysgsec='kubecolor --namespace=kube-system get secret'
alias kdsec='kubecolor describe secret'
alias ksysdsec='kubecolor --namespace=kube-system describe secret'
alias krmsec='kubecolor delete secret'
alias ksysrmsec='kubecolor --namespace=kube-system delete secret'
alias kgno='kubecolor get nodes'
alias kdno='kubecolor describe nodes'
alias kgns='kubecolor get namespaces'
alias kdns='kubecolor describe namespaces'
alias krmns='kubecolor delete namespaces'
alias kgoyaml='kubecolor get -o=yaml'
alias ksysgoyaml='kubecolor --namespace=kube-system get -o=yaml'
alias kgpooyaml='kubecolor get pods -o=yaml'
alias ksysgpooyaml='kubecolor --namespace=kube-system get pods -o=yaml'
alias kgdepoyaml='kubecolor get deployment -o=yaml'
alias ksysgdepoyaml='kubecolor --namespace=kube-system get deployment -o=yaml'
alias kgstsoyaml='kubecolor get statefulset -o=yaml'
alias ksysgstsoyaml='kubecolor --namespace=kube-system get statefulset -o=yaml'
alias kgsvcoyaml='kubecolor get service -o=yaml'
alias ksysgsvcoyaml='kubecolor --namespace=kube-system get service -o=yaml'
alias kgingoyaml='kubecolor get ingress -o=yaml'
alias ksysgingoyaml='kubecolor --namespace=kube-system get ingress -o=yaml'
alias kgcmoyaml='kubecolor get configmap -o=yaml'
alias ksysgcmoyaml='kubecolor --namespace=kube-system get configmap -o=yaml'
alias kgsecoyaml='kubecolor get secret -o=yaml'
alias ksysgsecoyaml='kubecolor --namespace=kube-system get secret -o=yaml'
alias kgnooyaml='kubecolor get nodes -o=yaml'
alias kgnsoyaml='kubecolor get namespaces -o=yaml'
alias kgowide='kubecolor get -o=wide'
alias ksysgowide='kubecolor --namespace=kube-system get -o=wide'
alias kgpoowide='kubecolor get pods -o=wide'
alias ksysgpoowide='kubecolor --namespace=kube-system get pods -o=wide'
alias kgdepowide='kubecolor get deployment -o=wide'
alias ksysgdepowide='kubecolor --namespace=kube-system get deployment -o=wide'
alias kgstsowide='kubecolor get statefulset -o=wide'
alias ksysgstsowide='kubecolor --namespace=kube-system get statefulset -o=wide'
alias kgsvcowide='kubecolor get service -o=wide'
alias ksysgsvcowide='kubecolor --namespace=kube-system get service -o=wide'
alias kgingowide='kubecolor get ingress -o=wide'
alias ksysgingowide='kubecolor --namespace=kube-system get ingress -o=wide'
alias kgcmowide='kubecolor get configmap -o=wide'
alias ksysgcmowide='kubecolor --namespace=kube-system get configmap -o=wide'
alias kgsecowide='kubecolor get secret -o=wide'
alias ksysgsecowide='kubecolor --namespace=kube-system get secret -o=wide'
alias kgnoowide='kubecolor get nodes -o=wide'
alias kgnsowide='kubecolor get namespaces -o=wide'
alias kgojson='kubecolor get -o=json'
alias ksysgojson='kubecolor --namespace=kube-system get -o=json'
alias kgpoojson='kubecolor get pods -o=json'
alias ksysgpoojson='kubecolor --namespace=kube-system get pods -o=json'
alias kgdepojson='kubecolor get deployment -o=json'
alias ksysgdepojson='kubecolor --namespace=kube-system get deployment -o=json'
alias kgstsojson='kubecolor get statefulset -o=json'
alias ksysgstsojson='kubecolor --namespace=kube-system get statefulset -o=json'
alias kgsvcojson='kubecolor get service -o=json'
alias ksysgsvcojson='kubecolor --namespace=kube-system get service -o=json'
alias kgingojson='kubecolor get ingress -o=json'
alias ksysgingojson='kubecolor --namespace=kube-system get ingress -o=json'
alias kgcmojson='kubecolor get configmap -o=json'
alias ksysgcmojson='kubecolor --namespace=kube-system get configmap -o=json'
alias kgsecojson='kubecolor get secret -o=json'
alias ksysgsecojson='kubecolor --namespace=kube-system get secret -o=json'
alias kgnoojson='kubecolor get nodes -o=json'
alias kgnsojson='kubecolor get namespaces -o=json'
alias kgall='kubecolor get --all-namespaces'
alias kdall='kubecolor describe --all-namespaces'
alias kgpoall='kubecolor get pods --all-namespaces'
alias kdpoall='kubecolor describe pods --all-namespaces'
alias kgdepall='kubecolor get deployment --all-namespaces'
alias kddepall='kubecolor describe deployment --all-namespaces'
alias kgstsall='kubecolor get statefulset --all-namespaces'
alias kdstsall='kubecolor describe statefulset --all-namespaces'
alias kgsvcall='kubecolor get service --all-namespaces'
alias kdsvcall='kubecolor describe service --all-namespaces'
alias kgingall='kubecolor get ingress --all-namespaces'
alias kdingall='kubecolor describe ingress --all-namespaces'
alias kgcmall='kubecolor get configmap --all-namespaces'
alias kdcmall='kubecolor describe configmap --all-namespaces'
alias kgsecall='kubecolor get secret --all-namespaces'
alias kdsecall='kubecolor describe secret --all-namespaces'
