complete -c worker -s w -l wait -x -d 'Wait for exit; zero waits without timeout'
complete -c worker -s b -l wait-blocked -x -d 'Wait for exit or input'
complete -c worker -s t -l tail -x -d 'Log lines after waiting'
complete -c worker -s n -l name -x -d 'Run name'
complete -c worker -l status -d 'Show the workspace worker'
complete -c worker -l close -d 'Close the worker pane'
complete -c worker -l release -x -d 'Release a run name'
complete -c worker -l force -d 'Force release'
complete -c worker -s h -l help -d 'Show usage'
