#!/usr/bin/env bash
# Bring this configuration up on a box with no Nix.
set -euo pipefail

remote=${SYSINIT_REMOTE:-https://github.com/roshbhatia/sysinit.git}
branch=${SYSINIT_BRANCH:-main}
checkout=${SYSINIT_CHECKOUT:-$HOME/.local/share/sysinit}

log() { printf '\033[1msysinit:\033[0m %s\n' "$*"; }

# ---------------------------------------------------------------- 1.

# `--no-checkout` first, so the working tree is never fully materialized.
if [ ! -d "$checkout/.git" ]; then
  log "sparse checkout of ${remote} into ${checkout}"
  mkdir -p "$(dirname "$checkout")"
  git clone --filter=blob:none --no-checkout --depth 1 --branch "$branch" \
    "$remote" "$checkout"
else
  log "updating ${checkout}"
  git -C "$checkout" fetch --depth 1 origin "$branch"
  git -C "$checkout" reset --hard "origin/${branch}" > /dev/null 2>&1 ||
    git -C "$checkout" reset --hard FETCH_HEAD > /dev/null
fi

git -C "$checkout" sparse-checkout set --cone \
  bootstrap \
  modules/home/programs/neovim/config \
  modules/home/programs/zsh \
  modules/shared/options \
  pkgs/sysinit-agent
# `read-tree -mu HEAD` rather than `checkout "$branch"`.
git -C "$checkout" read-tree -mu HEAD

test -f "$checkout/bootstrap/tools.toml" || {
  echo "bootstrap: the sparse checkout produced no tools.toml" >&2
  exit 1
}

# ------------------------------------------------------- 2.

# Written from `modules/shared/options/paths-layout.json` by substituting $HOME
layout="$checkout/modules/shared/options/paths-layout.json"
# The one path no consumer can learn from the manifest, because it IS the
# sysinit:documented-default
manifest="$HOME/.local/state/sysinit/paths.json"

log "writing ${manifest}"
mkdir -p "$(dirname "$manifest")"
sed "s#\$HOME#${HOME}#g" "$layout" > "$manifest.tmp"
mv "$manifest.tmp" "$manifest"

# --------------------------------------------------------- 3.

# The `system` entries in the manifest.
if command -v apt-get > /dev/null 2>&1; then
  packages=$(
    awk '
      /^\[\[tool\]\]|^\[\[program\]\]/ { pkg = "" }
      /^system = / { gsub(/^system = "|"$/, "", $0); print $0 }
    ' "$checkout/bootstrap/tools.toml"
  )
  log "apt-get install: $(echo "$packages" | tr '\n' ' ')"
  # shellcheck disable=SC2086
  DEBIAN_FRONTEND=noninteractive apt-get install -y -qq --no-install-recommends $packages > /dev/null
else
  log "no apt-get; skipping the distribution packages"
fi

# ------------------------------------------------------------------- 4.

if ! command -v mise > /dev/null 2>&1 && [ ! -x "$HOME/.local/bin/mise" ]; then
  log "installing mise"
  curl -fsSL https://mise.run | sh
fi
export PATH="$HOME/.local/bin:$PATH"

# The generated file becomes mise's GLOBAL config, by symlink, rather than
log "mise install"
mkdir -p "$HOME/.config/mise"
ln -sfn "$checkout/bootstrap/mise.toml" "$HOME/.config/mise/config.toml"
mise trust --yes "$HOME/.config/mise/config.toml" > /dev/null 2>&1 || true
mise install --yes
mise reshim > /dev/null 2>&1 || true

export PATH="$HOME/.local/share/mise/shims:$PATH"

# ---------------------------------------------------------------- 5.

# neovim is a symlink to the checkout, which is what the Nix side does too
log "linking the neovim config"
mkdir -p "$HOME/.config"
rm -rf "$HOME/.config/nvim"
ln -sfn "$checkout/modules/home/programs/neovim/config" "$HOME/.config/nvim"

# zsh cannot be a symlink: the Nix side assembles `initContent` from fragments
log "writing the zsh config"
zsh_dir="$checkout/modules/home/programs/zsh"
{
  echo "# GENERATED by bootstrap/bootstrap.sh. Edit the fragments in"
  echo "# ${zsh_dir} and re-run it."
  echo "export SYSINIT_CHECKOUT=${checkout}"
  # shellcheck disable=SC2016  # written literally into .zshrc, expanded there
  echo 'export PATH="$HOME/.local/share/mise/shims:$HOME/.local/bin:$HOME/go/bin:$PATH"'
  for fragment in \
    core/zshenv.zsh \
    core/init.zsh \
    core/path.zsh \
    core/compinit.zsh \
    core/path-apply.zsh \
    system/env.zsh \
    lib/cache.zsh \
    integrations/completions.zsh \
    integrations/extras.zsh; do
    echo ". ${zsh_dir}/${fragment}"
  done
} > "$HOME/.zshrc"

# --------------------------------------------------------- 6.

# `go install` rather than a release binary: this is the repository's own tool
log "go install ./pkgs/sysinit-agent"
mkdir -p "$HOME/.local/bin"
(cd "$checkout/pkgs/sysinit-agent" && GOBIN="$HOME/.local/bin" go install .)

log "done. Open a new shell, or: exec zsh"
