#!/usr/bin/env bash
# Bring this configuration up on a box with no Nix.
set -euo pipefail

remote=${SYSINIT_REMOTE:-https://github.com/roshbhatia/sysinit.git}
branch=${SYSINIT_BRANCH:-main}
checkout=${SYSINIT_CHECKOUT:-$HOME/.local/share/sysinit}

# `--editor` installs the neovim config and nothing else: no zsh, no
# utils, and only the tools the config shells out to. It is the mode for
# a box that is not yours, where replacing the shell would be rude.
mode=full
case ${1:-} in
  --editor) mode=editor ;;
  "") ;;
  *)
    echo "usage: bootstrap.sh [--editor]" >&2
    exit 2
    ;;
esac

log() { printf '\033[1msysinit:\033[0m %s\n' "$*"; }

# ---------------------------------------------------------------- 1.

# `--no-checkout` first, so the working tree is never fully materialized.
if [ ! -d "$checkout/.git" ]; then
  log "sparse checkout of ${remote} into ${checkout}"
  mkdir -p "$(dirname "$checkout")"
  git clone --filter=blob:none --no-checkout --depth 1 --branch "$branch" \
    "$remote" "$checkout"
else
  log "updating ${checkout}"
  git -C "$checkout" fetch --depth 1 origin "$branch"
  git -C "$checkout" reset --hard "origin/${branch}" > /dev/null 2>&1 ||
    git -C "$checkout" reset --hard FETCH_HEAD > /dev/null
fi

if [ "$mode" = editor ]; then
  git -C "$checkout" sparse-checkout set --cone \
    bootstrap \
    modules/home/programs/neovim/config \
    modules/shared/options
else
  git -C "$checkout" sparse-checkout set --cone \
    bootstrap \
    modules/home/programs/neovim/config \
    modules/home/programs/zsh \
    modules/shared/options \
    pkgs/utils
fi
# `read-tree -mu HEAD` rather than `checkout "$branch"`.
git -C "$checkout" read-tree -mu HEAD

test -f "$checkout/bootstrap/tools.toml" || {
  echo "bootstrap: the sparse checkout produced no tools.toml" >&2
  exit 1
}

# ------------------------------------------------------- 2.

# Written from `modules/shared/options/paths-layout.json` by substituting $HOME
layout="$checkout/modules/shared/options/paths-layout.json"
# The one path no consumer can learn from the manifest, because it IS the
# sysinit:documented-default
manifest="$HOME/.local/state/sysinit/paths.json"

log "writing ${manifest}"
mkdir -p "$(dirname "$manifest")"
sed "s#\$HOME#${HOME}#g" "$layout" > "$manifest.tmp"
mv "$manifest.tmp" "$manifest"

# --------------------------------------------------------- 3.

# The `system` entries in the manifest. In editor mode only the entries the
# neovim config needs, which is what `editor = true` marks.
if command -v apt-get > /dev/null 2>&1; then
  if [ "$mode" = editor ]; then
    packages=$(
      awk '
        /^\[\[tool\]\]|^\[\[program\]\]/ { sys = ""; want = 0 }
        /^system = / { sys = $0; gsub(/^system = "|"$/, "", sys) }
        /^editor = true/ { want = 1 }
        /^$/ { if (want && sys != "") print sys; sys = ""; want = 0 }
        END { if (want && sys != "") print sys }
      ' "$checkout/bootstrap/tools.toml"
    )
  else
    packages=$(
      awk '
        /^\[\[tool\]\]|^\[\[program\]\]/ { pkg = "" }
        /^system = / { gsub(/^system = "|"$/, "", $0); print $0 }
      ' "$checkout/bootstrap/tools.toml"
    )
  fi
  log "apt-get install: $(echo "$packages" | tr '\n' ' ')"
  # shellcheck disable=SC2086
  DEBIAN_FRONTEND=noninteractive apt-get install -y -qq --no-install-recommends $packages > /dev/null
else
  log "no apt-get; skipping the distribution packages"
fi

# ------------------------------------------------------------------- 4.

if ! command -v mise > /dev/null 2>&1 && [ ! -x "$HOME/.local/bin/mise" ]; then
  log "installing mise"
  curl -fsSL https://mise.run | sh
fi
export PATH="$HOME/.local/bin:$PATH"

# The generated file becomes mise's GLOBAL config, by symlink, rather than
log "mise install"
mkdir -p "$HOME/.config/mise"
if [ "$mode" = editor ]; then
  ln -sfn "$checkout/bootstrap/mise-editor.toml" "$HOME/.config/mise/config.toml"
else
  ln -sfn "$checkout/bootstrap/mise.toml" "$HOME/.config/mise/config.toml"
fi
mise trust --yes "$HOME/.config/mise/config.toml" > /dev/null 2>&1 || true
mise install --yes
mise reshim > /dev/null 2>&1 || true

export PATH="$HOME/.local/share/mise/shims:$PATH"

# ---------------------------------------------------------------- 5.

# neovim is a symlink to the checkout, which is what the Nix side does too
log "linking the neovim config"
mkdir -p "$HOME/.config"
rm -rf "$HOME/.config/nvim"
ln -sfn "$checkout/modules/home/programs/neovim/config" "$HOME/.config/nvim"

if [ "$mode" = editor ]; then
  # shellcheck disable=SC2016  # printed for the reader to paste, not expanded
  log 'done. Run: PATH="$HOME/.local/share/mise/shims:$PATH" nvim'
  exit 0
fi

# zsh cannot be a symlink: the Nix side assembles `initContent` from fragments
log "writing the zsh config"
zsh_dir="$checkout/modules/home/programs/zsh"
{
  echo "# GENERATED by bootstrap/bootstrap.sh. Edit the fragments in"
  echo "# ${zsh_dir} and re-run it."
  echo "export SYSINIT_CHECKOUT=${checkout}"
  # shellcheck disable=SC2016  # written literally into .zshrc, expanded there
  echo 'export PATH="$HOME/.local/share/mise/shims:$HOME/.local/bin:$HOME/go/bin:$PATH"'
  for fragment in \
    core/zshenv.zsh \
    core/init.zsh \
    core/path.zsh \
    core/compinit.zsh \
    core/path-apply.zsh \
    system/env.zsh \
    lib/cache.zsh \
    integrations/completions.zsh \
    integrations/extras.zsh; do
    echo ". ${zsh_dir}/${fragment}"
  done
} > "$HOME/.zshrc"

# --------------------------------------------------------- 6.

# `go install` rather than a release binary: this is the repository's own tool
log "go install ./pkgs/utils"
mkdir -p "$HOME/.local/bin"
(cd "$checkout/pkgs/utils" && GOBIN="$HOME/.local/bin" go install .)

log "done. Open a new shell, or: exec zsh"
