#!/usr/bin/env bash
set -euo pipefail

here=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
mode=${1:-write}

render() {
  python3 - "$here/tools.toml" "$1" << 'PY'
import sys, tomllib

with open(sys.argv[1], "rb") as fh:
    manifest = tomllib.load(fh)

editor_only = sys.argv[2] == "editor"

lines = [
    "# GENERATED by bootstrap/gen-mise-toml.sh from bootstrap/tools.toml.",
    "",
    "[tools]",
]

for entry in manifest.get("program", []) + manifest.get("tool", []):
    ident = entry.get("mise")
    if ident and (entry.get("editor") or not editor_only):
        lines.append(f'"{ident}" = "latest"')

print("\n".join(lines))
PY
}

status=0

emit() {
  local kind="$1" target="$here/$2" generated
  generated=$(render "$kind")

  if [ "$mode" = "--check" ]; then
    if [ ! -f "$target" ]; then
      echo "gen-mise-toml: $target does not exist; run $0" >&2
      status=1
      return
    fi
    if ! printf '%s\n' "$generated" | diff -u "$target" -; then
      echo "gen-mise-toml: $target has drifted from tools.toml; run $0" >&2
      status=1
    fi
    return
  fi

  printf '%s\n' "$generated" > "$target"
  echo "gen-mise-toml: wrote $target"
}

emit full mise.toml
emit editor mise-editor.toml

exit "$status"
