#!/usr/bin/env bash
# Generate `bootstrap/mise.toml` from `bootstrap/tools.toml`.
set -euo pipefail

here=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
mode=${1:-write}

generated=$(
  python3 - "$here/tools.toml" << 'PY'
import sys, tomllib

with open(sys.argv[1], "rb") as fh:
    manifest = tomllib.load(fh)

lines = [
    "# GENERATED by bootstrap/gen-mise-toml.sh from bootstrap/tools.toml.",
    "",
    "[tools]",
]

for entry in manifest.get("program", []) + manifest.get("tool", []):
    ident = entry.get("mise")
    if ident:
        lines.append(f'"{ident}" = "latest"')

print("\n".join(lines))
PY
)

target="$here/mise.toml"

if [ "$mode" = "--check" ]; then
  if [ ! -f "$target" ]; then
    echo "gen-mise-toml: $target does not exist; run $0" >&2
    exit 1
  fi
  if ! printf '%s\n' "$generated" | diff -u "$target" -; then
    echo "gen-mise-toml: bootstrap/mise.toml has drifted from tools.toml; run $0" >&2
    exit 1
  fi
  exit 0
fi

printf '%s\n' "$generated" > "$target"
echo "gen-mise-toml: wrote $target"
