#!/usr/bin/env bash
# Generate `bootstrap/mise.toml` from `bootstrap/tools.toml`.
#
# The manifest is the source and this file is derived, so `mise.toml` is checked
# in only so the bootstrap can read it without a python interpreter on the box.
# `.githooks/pre-commit` runs this with `--check` and fails when the checked-in
# file has drifted.
#
# python3 rather than a toml CLI: `tomllib` is in the standard library since
# 3.11, so this needs nothing installed. The bootstrap itself never runs this.
set -euo pipefail

here=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
mode=${1:-write}

generated=$(
  python3 - "$here/tools.toml" << 'PY'
import sys, tomllib

with open(sys.argv[1], "rb") as fh:
    manifest = tomllib.load(fh)

lines = [
    "# GENERATED by bootstrap/gen-mise-toml.sh from bootstrap/tools.toml.",
    "# Do not edit. Edit the manifest and re-run the generator.",
    "#",
    "# Only the entries mise can install are here. A tool the distribution",
    "# provides is installed by `bootstrap.sh` with apt, and a tool with no",
    "# non-Nix path is named in the manifest and dropped.",
    "",
    "[tools]",
]

for entry in manifest.get("program", []) + manifest.get("tool", []):
    ident = entry.get("mise")
    if ident:
        lines.append(f'"{ident}" = "latest"')

print("\n".join(lines))
PY
)

target="$here/mise.toml"

if [ "$mode" = "--check" ]; then
  if [ ! -f "$target" ]; then
    echo "gen-mise-toml: $target does not exist; run $0" >&2
    exit 1
  fi
  if ! printf '%s\n' "$generated" | diff -u "$target" -; then
    echo "gen-mise-toml: bootstrap/mise.toml has drifted from tools.toml; run $0" >&2
    exit 1
  fi
  exit 0
fi

printf '%s\n' "$generated" > "$target"
echo "gen-mise-toml: wrote $target"
