version: 1.0.0
title: Nix System Configuration Management
description: A guide for working with Nix-based system configurations using nix-darwin and home-manager for macOS and NixOS.
instructions: This workflow involves managing system configurations through Nix flakes, utilizing nix-darwin for macOS and home-manager for user configuration. The process includes understanding the project structure, working with Nix files (flake.nix, default.nix), Lua configurations, and shell scripts. Key tasks involve making changes to configuration files, building and testing systems, ensuring proper formatting and linting, and understanding how Nix expressions work. The tools and formats used include Nix syntax, Lua for home-manager configurations, shell scripting, and various Nix commands for building and testing configurations. All work should focus on maintaining the integrity of the Nix infrastructure while making appropriate system modifications.
extensions:
- type: builtin
  name: autovisualiser
  description: ''
  display_name: Auto Visualiser
  timeout: 300
  bundled: true
  available_tools: []
- type: builtin
  name: computercontroller
  description: ''
  display_name: Computer Controller
  timeout: 300
  bundled: true
  available_tools:
  - browser_action
  - computer_use
- type: builtin
  name: developer
  description: ''
  display_name: Developer
  timeout: 300
  bundled: true
  available_tools:
  - text_editor
  - shell
  - analyze
  - screen_capture
  - image_processor
- type: stdio
  name: Serena
  description: Serena IDE assistant with AGENTS.md integration for project-aware coding assistance
  cmd: uvx
  args:
  - --from
  - git+https://github.com/oraios/serena
  - serena
  - start-mcp-server
  - --enable-web-dashboard
  - 'false'
  - --context
  - claude-code
  envs: {}
  env_keys: []
  timeout: 300
  bundled: null
  available_tools: []
- type: platform
  name: skills
  description: Load and use skills from relevant directories
  bundled: true
  available_tools: []
- type: platform
  name: todo
  description: Enable a todo list for Goose so it can keep track of what it is doing
  bundled: true
  available_tools: []
- type: platform
  name: Extension Manager
  description: Enable extension management tools for discovering, enabling, and disabling extensions
  bundled: true
  available_tools: []
settings:
  goose_provider: openrouter
  goose_model: qwen/qwen3-coder-30b-a3b-instruct
  temperature: 0.0
activities:
- Manage Nix flake configurations
- Modify macOS system settings
- Update home-manager configurations
- Build and test system setups
- Format and lint Nix code
author:
  contact: rshnbhatia
