# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

includes:
  nix:
    taskfile: ./tasks/nix.yml
    optional: true
  fmt:
    taskfile: ./tasks/format.yml
    optional: true

tasks:
  default:
    desc: Show all available tasks
    cmds:
      - task --list-all
    silent: true

  fmt:
    desc: Format all supported file types
    deps: [fmt:all]
    silent: true

  docs:values:
    desc: Generate and inject values.nix schema documentation into README.md
    cmds:
      - ./hack/generate-values-docs.sh README.md
    silent: true
