version: '3'

vars:
  SUCCESS_STYLE: --foreground 212 --border normal --border-foreground 212 --align left --width 50 --margin "0 1" --padding "0 1"
  ERROR_STYLE: --foreground 196 --border normal --border-foreground 196 --align left --width 50 --margin "0 1" --padding "0 1"
  INFO_STYLE: --foreground 87 --border normal --border-foreground 87 --align left --width 50 --margin "0 1" --padding "0 1"

tasks:
  default:
    cmds:
      - task -l
    desc: Show help information
    silent: true

  # System Configuration
  nix:build:
    cmds:
      - gum style {{.INFO_STYLE}} "Building system configuration..."
      - |
        if ! gum spin --spinner dot --title "Running darwin-rebuild..." -- darwin-rebuild build --flake .; then
          gum style {{.ERROR_STYLE}} "Build failed"
          exit 1
        fi
      - gum style {{.SUCCESS_STYLE}} "Build completed successfully"
    desc: Build the configuration without applying
    silent: true

  nix:clean:
    cmds:
      - gum style {{.INFO_STYLE}} "Running garbage collection..."
      - |
        if ! gum spin --spinner dot --title "Collecting garbage..." -- sudo nix-collect-garbage -d; then
          gum style {{.ERROR_STYLE}} "Garbage collection failed"
          exit 1
        fi
      - gum style {{.SUCCESS_STYLE}} "Garbage collection completed"
    desc: Run garbage collection
    silent: true

  nix:refresh:
    deps: [update-flake]
    cmds:
      - |
        gum style {{.INFO_STYLE}} "Applying system configuration..."
        
        git add -A
        git commit -m "chore: update configuration and regenerate lockfile" || true
        git push || true
        
        if ! gum spin --spinner dot --title "Running darwin-rebuild..." -- darwin-rebuild switch --flake . --show-trace; then
          gum style {{.ERROR_STYLE}} "Failed to apply configuration"
          exit 1
        fi
        
        gum style {{.SUCCESS_STYLE}} "System configuration applied successfully"
    desc: Apply the system configuration
    silent: true

  nix:refresh:work:
    cmds:
      - |
        WORK_SYSINIT=$(find ~/github/work -maxdepth 2 -type d -name "sysinit" 2>/dev/null | head -n 1)
        
        if [ -z "$WORK_SYSINIT" ]; then
          gum style {{.ERROR_STYLE}} "Could not find work sysinit repository"
          exit 1
        fi
        
        gum style {{.INFO_STYLE}} "Working in: $WORK_SYSINIT"
        cd "$WORK_SYSINIT"

        if ! gum spin --spinner dot --title "Running nix flake update..." -- nix flake update; then
          gum style {{.ERROR_STYLE}} "Failed to update flake"
          exit 1
        fi
        
        if ! gum spin --spinner dot --title "Running refresh..." -- task refresh; then
          gum style {{.ERROR_STYLE}} "Failed to refresh work configuration"
          exit 1
        fi
        
        gum style {{.SUCCESS_STYLE}} "Work configuration refreshed successfully"
    desc: Update and rebuild work sysinit configuration
    silent: true

  nix:update-flake:
    cmds:
      - gum style {{.INFO_STYLE}} "Updating flake inputs..."
      - |
        if ! gum spin --spinner dot --title "Running flake update..." -- nix flake update; then
          gum style {{.ERROR_STYLE}} "Failed to update flake"
          exit 1
        fi
      - gum style {{.SUCCESS_STYLE}} "Flake inputs updated successfully"
    desc: Update flake inputs
    silent: true

  # System Setup
  nix:install:
    cmds:
      - gum style {{.INFO_STYLE}} "Installing prerequisites..."
      - |
        if ! gum spin --spinner dot --title "Running setup..." -- ./hack/install-deps.sh; then
          gum style {{.ERROR_STYLE}} "Setup failed"
          exit 1
        fi
      - gum style {{.SUCCESS_STYLE}} "Setup completed"
    desc: Install prerequisites for sysinit
    silent: true

  nix:uninstall:
    cmds:
      - gum style {{.INFO_STYLE}} "Uninstalling Nix..."
      - |
        if ! gum spin --spinner dot --title "Uninstalling..." -- ./hack/uninstall-nix.sh; then
          gum style {{.ERROR_STYLE}} "Uninstall failed"
          exit 1
        fi
      - gum style {{.SUCCESS_STYLE}} "Nix uninstalled successfully"
    desc: Completely uninstall Nix from the system
    silent: true

  nix:perms:
    cmds:
      - |
          {
            fix_permissions() {
              local dir="$1"
              local message="$2"
              shift 2
              local ignore_patterns=("${IGNORE_PATTERNS[@]}")
              
              # Add any additional ignore patterns passed as arguments
              for pattern in "$@"; do
                ignore_patterns+=("$pattern")
              done
              
              local ignore_args=()
              for pattern in "${ignore_patterns[@]}"; do
                ignore_args+=("-E" "$pattern")
              done
              
              echo "🔍 $message"
              echo "   Directory: $dir"
              
              if ! fd . "$dir" -t f -t d "${ignore_args[@]}" --owner "!$USER" -x sudo chown -v "$USER:staff" {} 2>/dev/null; then
                echo "❌ Failed to fix permissions for $dir"
                return 1
              fi
              
              # Fix directories where we need execute permission
              fd . "$dir" -t d "${ignore_args[@]}" -x sudo chmod -v 755 {} 2>/dev/null || true
              
              # Fix files where we need read/write permission
              fd . "$dir" -t f "${ignore_args[@]}" -x sudo chmod -v 644 {} 2>/dev/null || true
              
              echo "✅ Permissions fixed for $dir"
            }
            
            # Use more specific patterns for exclusions, especially for nix store
            IGNORE_PATTERNS=(
              ".DS_Store"
              ".git"
              "*.lock"
              "node_modules"
              "OrbStack*"
              "^/nix/store"  # Specifically exclude /nix/store at the beginning of paths
            )
            
            # Define XDG directories if not set
            XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
            XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
            XDG_CACHE_HOME="${XDG_CACHE_HOME:-$HOME/.cache}"
            XDG_STATE_HOME="${XDG_STATE_HOME:-$HOME/.local/state}"
            
            # Create XDG directories if they don't exist
            mkdir -p "$XDG_DATA_HOME" "$XDG_CONFIG_HOME" "$XDG_CACHE_HOME" "$XDG_STATE_HOME"
            
            echo "🔧 Starting permission fixes..."
            
            # Fix XDG directories first - these are most important for your needs
            fix_permissions "$XDG_DATA_HOME" "Fixing XDG_DATA_HOME permissions..."
            fix_permissions "$XDG_CONFIG_HOME" "Fixing XDG_CONFIG_HOME permissions..."
            fix_permissions "$XDG_CACHE_HOME" "Fixing XDG_CACHE_HOME permissions..."
            fix_permissions "$XDG_STATE_HOME" "Fixing XDG_STATE_HOME permissions..."
            
            # Fix other common directories that might need permission fixes
            fix_permissions "$HOME/.local" "Fixing .local directory permissions..."
            fix_permissions "$HOME/.nix-profile" "Fixing .nix-profile permissions..."
            
            # Fix Homebrew permissions if needed
            if [ -d "/opt/homebrew/opt" ]; then
              fix_permissions "/opt/homebrew/opt" "Fixing Homebrew permissions..."
            fi
            
            # Fix only specific directories under /nix that might need user access
            # Avoid touching /nix/store directly
            if [ -d "/nix/var" ]; then
              fix_permissions "/nix/var" "Fixing /nix/var permissions..."
            fi
            
            echo ""
            echo "✅ All permissions fixed successfully"
            echo "XDG directories are now properly accessible"
          }
    desc: Fix permissions for XDG directories and other relevant system paths
    silent: true
    vars:
      IGNORE_PATTERNS:
        - .DS_Store
        - .git
        - '*.lock'
        - node_modules
        - OrbStack*
        - '^/nix/store'
        - 
  nix:orphans:locate:
    cmds:
      - |
          {
            find_orphaned_nix_files() {
              echo "🔍 Finding orphaned Nix files that aren't part of current generation..."
              
              # Get the current generation path
              local current_gen=$(readlink -f "$HOME/.nix-profile")
              echo "Current Nix profile generation: $current_gen"
              
              # Find nix store paths in the user's home directory
              local found_count=0
              
              echo "Searching for Nix store paths in $HOME that don't link to current generation..."
              
              while IFS= read -r file; do
                if [[ -L "$file" ]]; then
                  target=$(readlink -f "$file")
                  if [[ "$target" == /nix/store/* && "$target" != "$current_gen"* ]]; then
                    echo "Found: $file → $target"
                    found_count=$((found_count + 1))
                  fi
                fi
              done < <(find "$HOME" -type l -not -path "*/\.*" -not -path "*/node_modules/*" 2>/dev/null)
              
              echo ""
              if [ $found_count -eq 0 ]; then
                echo "✅ No orphaned Nix files found."
              else
                echo "🔍 Found $found_count orphaned Nix files."
                echo "To remove them, run: task nix-orphans:prune"
              fi
            }
            
            # Run in find-only mode by default
            find_orphaned_nix_files
          }
    desc: Find Nix files that don't link to current home-manager generation
    silent: false

  nix:orphans:prune:
    cmds:
      - |
          {
            prune_orphaned_nix_files() {
              echo "🗑️ Pruning orphaned Nix files that aren't part of current generation..."
              
              # Get the current generation path
              local current_gen=$(readlink -f "$HOME/.nix-profile")
              echo "Current Nix profile generation: $current_gen"
              
              # Find and remove nix store paths not in current generation
              local removed_count=0
              
              while IFS= read -r file; do
                if [[ -L "$file" ]]; then
                  target=$(readlink -f "$file")
                  if [[ "$target" == /nix/store/* && "$target" != "$current_gen"* ]]; then
                    echo "Removing: $file → $target"
                    rm -f "$file"
                    removed_count=$((removed_count + 1))
                  fi
                fi
              done < <(find "$HOME" -type l -not -path "*/\.*" -not -path "*/node_modules/*" 2>/dev/null)
              
              echo ""
              echo "🗑️ Removed $removed_count orphaned Nix files."
            }
            
            prune_orphaned_nix_files
          }
    desc: Remove Nix files that don't link to current home-manager generation
    silent: false


  # Neovim Tasks
  nvim:extract-nvim-commands: { cmds: [task -d modules/darwin/home/neovim nvim:extract-nvim-commands], silent: true }
  nvim:extract-vsc-commands: { cmds: [task -d modules/darwin/home/neovim nvim:extract-vsc-commands], silent: true }
  nvim:pull-docs: { cmds: [task -d modules/darwin/home/neovim nvim:pull-docs], silent: true }
  nvim:run-local-headless-isolated: { cmds: [task -d modules/darwin/home/neovim nvim:run-local-headless-isolated], silent: true }
  nvim:run-local-isolated: { cmds: [task -d modules/darwin/home/neovim nvim:run-local-isolated], silent: true }
  nvim:verify-vsc-commands: { cmds: [task -d modules/darwin/home/neovim nvim:verify-vsc-actions], silent: true }
