# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

includes:
  nix:
    taskfile: ./tasks/nix.yml
    optional: true
  fmt:
    taskfile: ./tasks/format.yml
    optional: true

vars:
  NIXPKGS_ALLOW_UNFREE: 1
  NIX_DARWIN_REBUILD: "darwin-rebuild"
  WORK_REPO_PATH: "~/github/work"
  NIXFMT_WIDTH: 100
  SHFMT_OPTS: "-i 2 -ci -sr -s -w"
  NIX_CUSTOM_CONF: "nix.custom.conf"
  NIX_SYSTEM_CONF_DIR: "/etc/nix"
  NIX_MAX_JOBS: 2
  NIX_CORES: 2

tasks:
  default:
    desc: Show all available tasks
    cmds:
      - task --list-all
    silent: true

  sh:chmod:
    desc: Make all .sh files in the repository executable
    cmds:
      - |
        #!/usr/bin/env nu
        try {
          fd -e sh -x chmod +x {}
        } catch {
          print "✗ Failed to make .sh files executable"
          exit 1
        }
    silent: true

  fmt:
    desc: Format all supported file types
    deps: [fmt:all]
    silent: true

  docs:values:
    desc: Generate and inject values.nix schema documentation into README.md
    cmds:
      - |
        #!/usr/bin/env nu
        try {
          bash ./hack/generate-values-docs.sh README.md
        } catch {
          print "✗ Failed to generate values documentation"
          exit 1
        }
    silent: true
