cpu: 6
memory: 12
disk: 100
arch: aarch64
runtime: docker

vmType: vz
rosetta: true
mountType: sshfs
mountInotify: true

network:
  address: true

docker:
  insecure-registries:
    - "xpkg.crossplane.io"
    - "artifactory.nike.com:9001"
    - "artifactory.nike.com:9001"
    - "artifactory.nike.com.cn:9002"
    - "artifactory.nike.com.cn:9002"
  buildkit: true
  features:
    buildkit: true

forwardAgent: false

mounts:
  - location: /tmp/colima
    writable: true
  - location: /etc/ssl/certs
    writable: true
