- name: openai/claude-3.5-sonnet
  extra_params:
    extra_headers:
      accept: application/json
      editor-version: Neovim/0.11.1
      editor-plugin-version: copilot.vim/1.49.0
      content-type: application/json
      user-agent: GithubCopilot/1.155.0
    max_tokens: 8192

- name: openai/gpt-4.1
  extra_params:
    extra_headers:
      accept: application/json
      editor-version: Neovim/0.11.1
      editor-plugin-version: copilot.vim/1.49.0
      content-type: application/json
      user-agent: GithubCopilot/1.155.0
    max_tokens: 8192

- name: openai/gpt-4o
  extra_params:
    extra_headers:
      accept: application/json
      editor-version: Neovim/0.11.1
      editor-plugin-version: copilot.vim/1.49.0
      content-type: application/json
      user-agent: GithubCopilot/1.155.0
    max_tokens: 8192

- name: openai/o1-preview
  extra_params:
    extra_headers:
      accept: application/json
      editor-version: Neovim/0.11.1
      editor-plugin-version: copilot.vim/1.49.0
      content-type: application/json
      user-agent: GithubCopilot/1.155.0
    max_tokens: 8192

- name: openai/o3-mini
  extra_params:
    extra_headers:
      accept: application/json
      editor-version: Neovim/0.11.1
      editor-plugin-version: copilot.vim/1.49.0
      content-type: application/json
      user-agent: GithubCopilot/1.155.0
    max_tokens: 4096
