animation_duration_ms 150

blur enable
blur_passes 2
blur_radius 5
corner_radius 0
smart_corner_radius off
shadows enable
shadow_blur_radius 20
shadow_color #0000007F
default_dim_inactive 0.1

layer_effects "waybar" blur enable; shadows enable
