-- Main SketchyBar Lua config (user-managed)
require("sysinit.pkg.theme")
require("sysinit.pkg.core").setup()
require("sysinit.pkg.items.workspaces").setup()
require("sysinit.pkg.items.front_app").setup()
require("sysinit.pkg.items.system").setup()
