#!/usr/bin/env bash
# shellcheck disable=all
. "$CONFIG_DIR/utils/loglib.sh"

log_info "Loading theme configuration"
. "${CONFIG_DIR}/themes/catppuccin-latte.sh"

log_info "Configuring bar properties"
sketchybar --bar position=top height=40 color="${_SSDF_CM_MANTLE}"

log_info "Setting default properties"
sketchybar --default \
  padding_left=5 \
  padding_right=5 \
  icon.font="Symbols Nerd Font Mono:Regular:15.0" \
  label.font="JetBrains Mono:Thin:15.0" \
  icon.color="${_SSDF_CM_SUBTEXT_1}" \
  label.color="${_SSDF_CM_SUBTEXT_0}" \
  icon.padding_left=4 \
  icon.padding_right=4 \
  label.padding_left=4 \
  label.padding_right=4

log_info "Loading item configurations"
. "$CONFIG_DIR/items/left.sh"
. "$CONFIG_DIR/items/right.sh"

log_info "Updating sketchybar"
sketchybar --hotload true
sketchybar --update

