{
  config,
  lib,
  values,
  ...
}:

let
  themes = import ../../../lib/themes { inherit lib; };
  paths = import ../../../lib/paths { inherit config lib; };
  vividTheme = themes.getAppTheme "vivid" values.theme.colorscheme values.theme.variant;
  nushellTheme = themes.getAppTheme "nushell" values.theme.colorscheme values.theme.variant;

  pathsList = paths.getAllPaths config.home.username config.home.homeDirectory;
in
{

  programs.carapace.enableNushellIntegration = true;
  programs.nushell = {
    enable = true;

    configFile.source = ./core/config.nu;

    shellAliases = {
      "....." = "cd ../../../..";
      "...." = "cd ../../..";
      "..." = "cd ../..";
      ".." = "cd ..";
      "~" = "cd ~";
      code = "code-insiders";
      c = "code-insiders";
      kubectl = "kubecolor";
      l = "ls";
      la = "ls -a";
      ll = "ls -la";
      lt = "eza --icons=always -1 -a -T --git-ignore --ignore-glob='.git'";
      tf = "terraform";
      y = "yazi";
      v = "nvim";
      g = "git";
      sudo = "sudo -E";
      diff = "diff --color";
      grep = "grep -s --color=auto";
      watch = "watch --quiet";

      # Required for macos
      nu-open = "open";
      open = "^open";
    };

    environmentVariables = config.home.sessionVariables;

    extraConfig = ''
      $env.LS_COLORS = (vivid generate ${vividTheme})
      $env.EZA_COLORS = $env.LS_COLORS

      source theme.nu

      source wezterm.nu

      source atuin.nu
      source completion-external.nu
      source direnv.nu
      source zoxide.nu

      source carapace.nu
      source kubectl.nu

      source macchina.nu
      source omp.nu
    '';
  };

  xdg.configFile = {
    "nushell/env.nu".text = ''
      #!/usr/bin/env nu
      # THIS FILE WAS GENERATED BY SYSINIT. MODIFICATIONS WILL BE OVERWRITTEN UPON UPDATE.
      # shellcheck disable=all
      # modules/darwin/home/nu/core/env.nu (begin)
      $env.XDG_DATA_HOME   = ($env.XDG_DATA_HOME?   | default $"($env.HOME)/.local/share")
      $env.XDG_CONFIG_HOME = ($env.XDG_CONFIG_HOME? | default $"($env.HOME)/.config")
      $env.XDG_STATE_HOME  = ($env.XDG_STATE_HOME?  | default $"($env.HOME)/.local/state")
      $env.XDG_CACHE_HOME  = ($env.XDG_CACHE_HOME?  | default $"($env.HOME)/.cache")

      def path_add [dir: string] {
        if ($dir | path exists) {
          $env.PATH = ($env.PATH | split row (char esep) | prepend $dir | uniq | str join (char esep))
        }
      }

      let paths = [
        ${lib.concatStringsSep "\n        " (map (path: "\"${path}\"") pathsList)}
      ]

      for path in $paths {
        path_add $path
      }

      $env.LANG = "en_US.UTF-8"
      $env.LC_ALL = "en_US.UTF-8"
      $env.SUDO_EDITOR = "nvim"
      $env.VISUAL = "nvim"
      $env.EDITOR = "nvim"
      $env.GIT_DISCOVERY_ACROSS_FILESYSTEM = "1"
      $env.COLIMA_HOME = $"($env.XDG_CONFIG_HOME)/colima"

      $env.FZF_DEFAULT_COMMAND = "fd --type f --hidden --follow --exclude .git --exclude node_modules"
      $env.FZF_DEFAULT_OPTS = [
        "--bind=resize:refresh-preview"
        "--cycle"
        "--height=30"
        "--highlight-line"
        "--ignore-case"
        "--info=inline"
        "--input-border=rounded"
        "--layout=reverse"
        "--list-border=rounded"
        "--no-scrollbar"
        "--pointer='>'"
        "--preview-border=rounded"
        "--prompt='>> '"
        "--scheme=history"
        "--style=minimal"
        "--preview=~/.local/bin/fzf_preview.sh {}"
      ] | str join " "
      # modules/darwin/home/nu/core/env.nu (end)
    '';

    "nushell/theme.nu".source = ./themes/${nushellTheme};

    "nushell/atuin.nu".source = ./core/atuin.nu;
    "nushell/carapace.nu".source = ./core/carapace.nu;
    "nushell/direnv.nu".source = ./core/direnv.nu;
    "nushell/kubectl.nu".source = ./core/kubectl.nu;
    "nushell/macchina.nu".source = ./core/macchina.nu;
    "nushell/omp.nu".source = ./core/omp.nu;
    "nushell/wezterm.nu".source = ./core/wezterm.nu;
    "nushell/zoxide.nu".source = ./core/zoxide.nu;
  };
}

