# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  crush = {
    pname = "crush";
    version = "0.68.0";
    src = fetchurl {
      url = "https://github.com/charmbracelet/crush/releases/download/v0.68.0/crush_0.68.0_Darwin_arm64.tar.gz";
      sha256 = "sha256-b68DOmD3q2oSe6WLTnoFA0nDS4Kfp3x2LXZ8//T2iJA=";
    };
  };
  crush-aarch64-linux = {
    pname = "crush-aarch64-linux";
    version = "0.68.0";
    src = fetchurl {
      url = "https://github.com/charmbracelet/crush/releases/download/v0.68.0/crush_0.68.0_Linux_arm64.tar.gz";
      sha256 = "sha256-l8U3rBZ883vae9zsQsunTzQX6KrKVjiQs090xnjWF2A=";
    };
  };
  crush-x86_64-darwin = {
    pname = "crush-x86_64-darwin";
    version = "0.68.0";
    src = fetchurl {
      url = "https://github.com/charmbracelet/crush/releases/download/v0.68.0/crush_0.68.0_Darwin_x86_64.tar.gz";
      sha256 = "sha256-GBbgjWp9ofpzV11SUOqJBcc4aoQeqyZFJztWqL8hly8=";
    };
  };
  crush-x86_64-linux = {
    pname = "crush-x86_64-linux";
    version = "0.68.0";
    src = fetchurl {
      url = "https://github.com/charmbracelet/crush/releases/download/v0.68.0/crush_0.68.0_Linux_x86_64.tar.gz";
      sha256 = "sha256-mgJgrvg26nwXu5nCr8UFzMz4F9s0XVq4hzJ0qeFdMIY=";
    };
  };
  go-enum = {
    pname = "go-enum";
    version = "v0.9.2";
    src = fetchFromGitHub {
      owner = "abice";
      repo = "go-enum";
      rev = "v0.9.2";
      fetchSubmodules = false;
      sha256 = "sha256-VZH7xLEDqU8N7oU3tOWVdTABEQEp2mlh1NtTg22hzco=";
    };
  };
  gomvp = {
    pname = "gomvp";
    version = "v0.0.4";
    src = fetchFromGitHub {
      owner = "abenz1267";
      repo = "gomvp";
      rev = "v0.0.4";
      fetchSubmodules = false;
      sha256 = "sha256-dXjI+nItJCAGKxyC9tX11hxWHCP+NgXtTYtm5+6dqDU=";
    };
  };
  goose-cli-bin = {
    pname = "goose-cli-bin";
    version = "1.34.0";
    src = fetchurl {
      url = "https://github.com/block/goose/releases/download/v1.34.0/goose-aarch64-apple-darwin.tar.gz";
      sha256 = "sha256-gPZua1G5P+vPpboFClEUnTH4WAkTfEJ43vQ5vhFKvVk=";
    };
  };
  goose-cli-bin-aarch64-linux = {
    pname = "goose-cli-bin-aarch64-linux";
    version = "1.34.0";
    src = fetchurl {
      url = "https://github.com/block/goose/releases/download/v1.34.0/goose-aarch64-unknown-linux-gnu.tar.gz";
      sha256 = "sha256-evbXoH2jRQV8plpLsVSxnQndXatPhzazT0VgCTOzjgc=";
    };
  };
  goose-cli-bin-x86_64-darwin = {
    pname = "goose-cli-bin-x86_64-darwin";
    version = "1.34.0";
    src = fetchurl {
      url = "https://github.com/block/goose/releases/download/v1.34.0/goose-x86_64-apple-darwin.tar.gz";
      sha256 = "sha256-VuBU3OtVq6QfCdjPXJkjDDwrv9XxUWXja/HXeOh427g=";
    };
  };
  goose-cli-bin-x86_64-linux = {
    pname = "goose-cli-bin-x86_64-linux";
    version = "1.34.0";
    src = fetchurl {
      url = "https://github.com/block/goose/releases/download/v1.34.0/goose-x86_64-unknown-linux-gnu.tar.gz";
      sha256 = "sha256-jQv2+aXVoABxpXpv08iONgUYEzie98S2mhQFlV+vSiE=";
    };
  };
  hererocks = {
    pname = "hererocks";
    version = "0.25.1";
    src = fetchFromGitHub {
      owner = "luarocks";
      repo = "hererocks";
      rev = "0.25.1";
      fetchSubmodules = false;
      sha256 = "sha256-y28MTFncy5oD57jpY6AN+X/58OzY3ae3rSL236rfuL0=";
    };
  };
  ioskeleyMono = {
    pname = "ioskeleyMono";
    version = "2026.03.19-7";
    src = fetchurl {
      url = "https://github.com/ahatem/IoskeleyMono/releases/download/2026.03.19-7/IoskeleyMono-TTF-Hinted.zip";
      sha256 = "sha256-641PVxt0MVXQentV5oWObBpu2P0e3qtfpWmbdOuNUtI=";
    };
  };
  kubernetes-zeitgeist = {
    pname = "kubernetes-zeitgeist";
    version = "v0.7.0";
    src = fetchFromGitHub {
      owner = "kubernetes-sigs";
      repo = "zeitgeist";
      rev = "v0.7.0";
      fetchSubmodules = false;
      sha256 = "sha256-tzR9hOMfnEa4p1ssktTISO6cAwlSxEGfvzJeLyM2qYo=";
    };
  };
  pi-coding-agent = {
    pname = "pi-coding-agent";
    version = "0.74.0";
    src = fetchurl {
      url = "https://github.com/earendil-works/pi/releases/download/v0.74.0/pi-darwin-arm64.tar.gz";
      sha256 = "sha256-MGMXmCPGqYVjQxIkDFcBUCQxb3/mZh7dQfFMd9ixXhA=";
    };
  };
  pi-coding-agent-aarch64-linux = {
    pname = "pi-coding-agent-aarch64-linux";
    version = "0.74.0";
    src = fetchurl {
      url = "https://github.com/earendil-works/pi/releases/download/v0.74.0/pi-linux-arm64.tar.gz";
      sha256 = "sha256-JhqpEoeMqYPJA9nEoECDEN2GN7WDCFZR2bXdtwyd9XI=";
    };
  };
  pi-coding-agent-x86_64-darwin = {
    pname = "pi-coding-agent-x86_64-darwin";
    version = "0.74.0";
    src = fetchurl {
      url = "https://github.com/earendil-works/pi/releases/download/v0.74.0/pi-darwin-x64.tar.gz";
      sha256 = "sha256-+mXJjyxlHsL4n7Goo9ybmHlHvJsQI2Gi8XiGKrrMdWA=";
    };
  };
  pi-coding-agent-x86_64-linux = {
    pname = "pi-coding-agent-x86_64-linux";
    version = "0.74.0";
    src = fetchurl {
      url = "https://github.com/earendil-works/pi/releases/download/v0.74.0/pi-linux-x64.tar.gz";
      sha256 = "sha256-1nZXow1JyfrKgIaNKkvbpN/KwEcCiT9FptFLJJNF640=";
    };
  };
}
