# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  crush = {
    pname = "crush";
    version = "0.47.2";
    src = fetchurl {
      url = "https://github.com/charmbracelet/crush/releases/download/v0.47.2/crush_0.47.2_Darwin_arm64.tar.gz";
      sha256 = "sha256-GZDKSUUOtMV7zV5uNXFl6geQUkfyWnS6PX7XsZOGvpI=";
    };
  };
  crush-aarch64-linux = {
    pname = "crush-aarch64-linux";
    version = "0.47.2";
    src = fetchurl {
      url = "https://github.com/charmbracelet/crush/releases/download/v0.47.2/crush_0.47.2_Linux_arm64.tar.gz";
      sha256 = "sha256-Ke7k1BaTqaj+CRU0V/LcHcpeTbubQtA0Z++W81mb0bY=";
    };
  };
  crush-x86_64-darwin = {
    pname = "crush-x86_64-darwin";
    version = "0.47.2";
    src = fetchurl {
      url = "https://github.com/charmbracelet/crush/releases/download/v0.47.2/crush_0.47.2_Darwin_x86_64.tar.gz";
      sha256 = "sha256-59CW6mkiWE9XUE5wRooXc/x8aCSGPvZhXkxP9Jzz5lY=";
    };
  };
  crush-x86_64-linux = {
    pname = "crush-x86_64-linux";
    version = "0.47.2";
    src = fetchurl {
      url = "https://github.com/charmbracelet/crush/releases/download/v0.47.2/crush_0.47.2_Linux_x86_64.tar.gz";
      sha256 = "sha256-azUv/6WFQtLla4a/2dlLqFBaCeSgmEZxAtRP3WR1lz4=";
    };
  };
  go-enum = {
    pname = "go-enum";
    version = "v0.9.2";
    src = fetchFromGitHub {
      owner = "abice";
      repo = "go-enum";
      rev = "v0.9.2";
      fetchSubmodules = false;
      sha256 = "sha256-VZH7xLEDqU8N7oU3tOWVdTABEQEp2mlh1NtTg22hzco=";
    };
  };
  gomvp = {
    pname = "gomvp";
    version = "v0.0.4";
    src = fetchFromGitHub {
      owner = "abenz1267";
      repo = "gomvp";
      rev = "v0.0.4";
      fetchSubmodules = false;
      sha256 = "sha256-dXjI+nItJCAGKxyC9tX11hxWHCP+NgXtTYtm5+6dqDU=";
    };
  };
  hererocks = {
    pname = "hererocks";
    version = "0.25.1";
    src = fetchFromGitHub {
      owner = "luarocks";
      repo = "hererocks";
      rev = "0.25.1";
      fetchSubmodules = false;
      sha256 = "sha256-y28MTFncy5oD57jpY6AN+X/58OzY3ae3rSL236rfuL0=";
    };
  };
  kubernetes-zeitgeist = {
    pname = "kubernetes-zeitgeist";
    version = "v0.5.4";
    src = fetchFromGitHub {
      owner = "kubernetes-sigs";
      repo = "zeitgeist";
      rev = "v0.5.4";
      fetchSubmodules = false;
      sha256 = "sha256-o9uk8WnoIvG5Ylz6We2QElBrKOq2mUWKu0pqzlKtaXY=";
    };
  };
  pi-coding-agent = {
    pname = "pi-coding-agent";
    version = "0.57.1";
    src = fetchurl {
      url = "https://github.com/badlogic/pi-mono/releases/download/v0.57.1/pi-darwin-arm64.tar.gz";
      sha256 = "sha256-T8cLJKI+ODscNW6jdiDhGJ1ohCDfNrSMSbR1eJ9eD44=";
    };
  };
  pi-coding-agent-aarch64-linux = {
    pname = "pi-coding-agent-aarch64-linux";
    version = "0.57.1";
    src = fetchurl {
      url = "https://github.com/badlogic/pi-mono/releases/download/v0.57.1/pi-linux-arm64.tar.gz";
      sha256 = "sha256-GrX78MvEEKaM6MOAEGttfW4v6ryg3KJ7jmi3dw6h9K0=";
    };
  };
  pi-coding-agent-x86_64-darwin = {
    pname = "pi-coding-agent-x86_64-darwin";
    version = "0.57.1";
    src = fetchurl {
      url = "https://github.com/badlogic/pi-mono/releases/download/v0.57.1/pi-darwin-x64.tar.gz";
      sha256 = "sha256-vGdzPOmldi00rmCP62Va53Q08fU1qgimXG3kBFt37HM=";
    };
  };
  pi-coding-agent-x86_64-linux = {
    pname = "pi-coding-agent-x86_64-linux";
    version = "0.57.1";
    src = fetchurl {
      url = "https://github.com/badlogic/pi-mono/releases/download/v0.57.1/pi-linux-x64.tar.gz";
      sha256 = "sha256-ghQwKFWi+oPRW0cGvI6L6Rommqy0lhTBSqc/0sKqZac=";
    };
  };
}
