# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  crush = {
    pname = "crush";
    version = "0.70.0";
    src = fetchurl {
      url = "https://github.com/charmbracelet/crush/releases/download/v0.70.0/crush_0.70.0_Darwin_arm64.tar.gz";
      sha256 = "sha256-dCNRoA6KCaqrQ8UH8Z2V/pSfGjOZ9cxSqOJJ0C/IKlo=";
    };
  };
  crush-aarch64-linux = {
    pname = "crush-aarch64-linux";
    version = "0.70.0";
    src = fetchurl {
      url = "https://github.com/charmbracelet/crush/releases/download/v0.70.0/crush_0.70.0_Linux_arm64.tar.gz";
      sha256 = "sha256-/5ksewkT0E+S/HR6kWJ/qbbfNor0DyJ5WVsadxGW6kg=";
    };
  };
  crush-x86_64-darwin = {
    pname = "crush-x86_64-darwin";
    version = "0.70.0";
    src = fetchurl {
      url = "https://github.com/charmbracelet/crush/releases/download/v0.70.0/crush_0.70.0_Darwin_x86_64.tar.gz";
      sha256 = "sha256-mXFOuT44ah1Mq00vll6MI4RFVs0MKnILl39UTie8kgA=";
    };
  };
  crush-x86_64-linux = {
    pname = "crush-x86_64-linux";
    version = "0.70.0";
    src = fetchurl {
      url = "https://github.com/charmbracelet/crush/releases/download/v0.70.0/crush_0.70.0_Linux_x86_64.tar.gz";
      sha256 = "sha256-dtLn4MFdze9XoYv5JqbOcVrpAKiE7sCoEGIHTJ9Z/0I=";
    };
  };
  go-enum = {
    pname = "go-enum";
    version = "v0.9.2";
    src = fetchFromGitHub {
      owner = "abice";
      repo = "go-enum";
      rev = "v0.9.2";
      fetchSubmodules = false;
      sha256 = "sha256-VZH7xLEDqU8N7oU3tOWVdTABEQEp2mlh1NtTg22hzco=";
    };
  };
  gomvp = {
    pname = "gomvp";
    version = "v0.0.4";
    src = fetchFromGitHub {
      owner = "abenz1267";
      repo = "gomvp";
      rev = "v0.0.4";
      fetchSubmodules = false;
      sha256 = "sha256-dXjI+nItJCAGKxyC9tX11hxWHCP+NgXtTYtm5+6dqDU=";
    };
  };
  goose-cli-bin = {
    pname = "goose-cli-bin";
    version = "1.35.0";
    src = fetchurl {
      url = "https://github.com/block/goose/releases/download/v1.35.0/goose-aarch64-apple-darwin.tar.gz";
      sha256 = "sha256-ifoRPt55Lm5NW3Pj6dQ5Haucw4E5XNmNAgKcmG3dEmA=";
    };
  };
  goose-cli-bin-aarch64-linux = {
    pname = "goose-cli-bin-aarch64-linux";
    version = "1.35.0";
    src = fetchurl {
      url = "https://github.com/block/goose/releases/download/v1.35.0/goose-aarch64-unknown-linux-gnu.tar.gz";
      sha256 = "sha256-GaCN4gQo1Kh5ObbxBxjtc9ZOh4uW2V8Yzt3JEQs8y8c=";
    };
  };
  goose-cli-bin-x86_64-darwin = {
    pname = "goose-cli-bin-x86_64-darwin";
    version = "1.35.0";
    src = fetchurl {
      url = "https://github.com/block/goose/releases/download/v1.35.0/goose-x86_64-apple-darwin.tar.gz";
      sha256 = "sha256-MVwxvy/nRVs/airjseEqBXS11g/PYjF/88oWcpugEr0=";
    };
  };
  goose-cli-bin-x86_64-linux = {
    pname = "goose-cli-bin-x86_64-linux";
    version = "1.35.0";
    src = fetchurl {
      url = "https://github.com/block/goose/releases/download/v1.35.0/goose-x86_64-unknown-linux-gnu.tar.gz";
      sha256 = "sha256-sz9PaPC8qomPQreuVfe/eQM16VbsDsM0LF77ZsVXpAU=";
    };
  };
  hererocks = {
    pname = "hererocks";
    version = "0.25.1";
    src = fetchFromGitHub {
      owner = "luarocks";
      repo = "hererocks";
      rev = "0.25.1";
      fetchSubmodules = false;
      sha256 = "sha256-y28MTFncy5oD57jpY6AN+X/58OzY3ae3rSL236rfuL0=";
    };
  };
  ioskeleyMono = {
    pname = "ioskeleyMono";
    version = "2026.03.19-7";
    src = fetchurl {
      url = "https://github.com/ahatem/IoskeleyMono/releases/download/2026.03.19-7/IoskeleyMono-TTF-Hinted.zip";
      sha256 = "sha256-641PVxt0MVXQentV5oWObBpu2P0e3qtfpWmbdOuNUtI=";
    };
  };
  kubernetes-zeitgeist = {
    pname = "kubernetes-zeitgeist";
    version = "v0.7.0";
    src = fetchFromGitHub {
      owner = "kubernetes-sigs";
      repo = "zeitgeist";
      rev = "v0.7.0";
      fetchSubmodules = false;
      sha256 = "sha256-tzR9hOMfnEa4p1ssktTISO6cAwlSxEGfvzJeLyM2qYo=";
    };
  };
  mermaid-ascii = {
    pname = "mermaid-ascii";
    version = "1.2.0";
    src = fetchFromGitHub {
      owner = "AlexanderGrooff";
      repo = "mermaid-ascii";
      rev = "1.2.0";
      fetchSubmodules = false;
      sha256 = "sha256-PbYqYy0jHQb+qvkp+lp/Wlde50dhdg7Ri2eNExXeoQ4=";
    };
  };
  pi-coding-agent = {
    pname = "pi-coding-agent";
    version = "0.74.2";
    src = fetchurl {
      url = "https://github.com/earendil-works/pi/releases/download/v0.74.2/pi-darwin-arm64.tar.gz";
      sha256 = "sha256-KhQ5s1NAI6cwN2FfVRboTlsgB7Si6gYufI834Xd7asc=";
    };
  };
  pi-coding-agent-aarch64-linux = {
    pname = "pi-coding-agent-aarch64-linux";
    version = "0.74.2";
    src = fetchurl {
      url = "https://github.com/earendil-works/pi/releases/download/v0.74.2/pi-linux-arm64.tar.gz";
      sha256 = "sha256-nAR897Mg2ZfrYg5OTIGG/4InaioHq9csy+FjrBN9j2E=";
    };
  };
  pi-coding-agent-x86_64-darwin = {
    pname = "pi-coding-agent-x86_64-darwin";
    version = "0.74.2";
    src = fetchurl {
      url = "https://github.com/earendil-works/pi/releases/download/v0.74.2/pi-darwin-x64.tar.gz";
      sha256 = "sha256-ipMH9Ta3kg/5SXVIlAE3a8pmLEz88JVyxeF7N0W9TN0=";
    };
  };
  pi-coding-agent-x86_64-linux = {
    pname = "pi-coding-agent-x86_64-linux";
    version = "0.74.2";
    src = fetchurl {
      url = "https://github.com/earendil-works/pi/releases/download/v0.74.2/pi-linux-x64.tar.gz";
      sha256 = "sha256-cnz6hNpO8MXoindN725DZK2RSn/y/pjRCt6yJwo9U3U=";
    };
  };
}
