local wezterm = require("wezterm")

local keybindings = require("sysinit.pkg.keybindings")
local utils = require("sysinit.pkg.utils")
local plugin_loader = require("sysinit.pkg.plugin_loader")

local M = {}

function M.setup(config)
  local config_data = utils.load_json_file(utils.get_config_path("config.json"))
  local font = wezterm.font_with_fallback({
    {
      family = config_data.font.monospace,
      harfbuzz_features = { "calt", "liga" },
    },
    config_data.font.symbols,
  })

  -- Core settings
  config.font = font
  config.font_size = 11.0
  config.line_height = 1.0
  config.cell_width = 1.0

  -- Apply base16 colors from config.json (generated by Nix from Stylix)
  if config_data.colors then
    config.colors = config_data.colors
  end

  config.status_update_interval = 150
  config.animation_fps = 240
  config.max_fps = 240
  config.cursor_blink_rate = 320
  config.cursor_thickness = 1
  config.scrollback_lines = 200000
  config.quick_select_alphabet = "fjdkslaghrueiwoncmv"
  config.adjust_window_size_when_changing_font_size = false
  config.use_resize_increments = false
  config.pane_focus_follows_mouse = false

  config.tab_bar_at_bottom = true
  config.use_fancy_tab_bar = false
  config.hide_tab_bar_if_only_one_tab = false

  -- Every fresh window (launch, relaunch after quit, CMD+N) starts in the
  -- "default" workspace instead of inheriting the last-used session. Paired
  -- with wm.session_restore_on_startup = false so nothing overrides this on
  -- startup.
  config.default_workspace = "default"

  config.window_frame = {
    font = font,
    font_size = 11.0,
  }

  config.visual_bell = {
    fade_in_function = "EaseIn",
    fade_in_duration_ms = 70,
    fade_out_function = "EaseOut",
    fade_out_duration_ms = 100,
  }

  config.window_background_opacity = config_data.transparency.opacity

  if utils.is_darwin() then
    -- macOS: compositor handles blur, wezterm handles opacity
    config.front_end = "WebGpu"
    config.window_decorations = "RESIZE|MACOS_FORCE_ENABLE_SHADOW"
    config.macos_window_background_blur = config_data.transparency.blur
  else
    -- Linux/Wayland (sway)
    config.enable_wayland = false
    config.front_end = "WebGpu"
    config.window_decorations = "RESIZE"
    config.freetype_load_flags = "NO_HINTING|NO_AUTOHINT"
    -- Tell wezterm it's in a tiling WM so it accounts for
    -- window sizing correctly (fixes tab bar cutoff)
    config.tiling_desktop_environments = {
      "X11 LG3D",
      "X11 bspwm",
      "X11 i3",
      "X11 dwm",
      "Wayland",
    }
  end

  local function locked_indicator()
    if keybindings.locked_mode then
      return "  "
    end
    return "  "
  end

  -- Load agent-deck before tabline so its API is available in tabline sections
  local agent_deck_ok, agent_deck = plugin_loader.load("agent-deck")
  if not agent_deck_ok then
    wezterm.log_warn("Failed to load agent-deck: " .. tostring(agent_deck))
  end
  if agent_deck_ok then
    agent_deck.apply_to_config(config, {
      tab_title = { enabled = false },
      right_status = { enabled = false },
      cooldown_ms = 150,
      max_lines = 500,
      notifications = {
        enabled = true,
        on_waiting = true,
        backend = "native",
      },
      agents = {
        claude = {
          -- Claude Code 2.x ships as a Bun-compiled Mach-O binary whose
          -- kernel-visible name is `.claude-wrapped`; the broad "claude"
          -- substring matches the install path .../claude-X.Y.Z/bin/.claude-wrapped.
          patterns = { ".claude%-wrapped", "claude", "claude%-code" },
          executable_patterns = { "@anthropic%-ai/claude%-code", "/claude%-code/", "/claude$", "claude" },
          argv_patterns = { "@anthropic%-ai/claude%-code", "claude%-code", "^claude%s*$" },
          title_patterns = { "claude code", "claude", ".claude%-wrapped" },
        },
        goose = {
          patterns = { "goose", "goosed" },
          executable_patterns = { "/goose$", "/goosed$" },
          argv_patterns = { "^goose%s*$" },
          title_patterns = { "goose" },
        },
        amp = {
          patterns = { "amp" },
          executable_patterns = { "/amp$" },
          argv_patterns = { "^amp%s*$" },
          title_patterns = { "amp" },
        },
        copilot = {
          patterns = { "copilot" },
          executable_patterns = { "/copilot$", "copilot%-language%-server" },
          argv_patterns = { "^copilot%s*$" },
          title_patterns = { "copilot" },
        },
        cursor = {
          patterns = { "cursor%-agent", "cursor" },
          executable_patterns = { "/cursor%-agent$" },
          argv_patterns = { "cursor%-agent" },
          title_patterns = { "cursor" },
        },
        crush = {
          patterns = { "crush" },
          executable_patterns = { "/crush$" },
          argv_patterns = { "^crush%s*$" },
          title_patterns = { "crush" },
        },
        opencode = {
          patterns = { "opencode" },
          executable_patterns = { "opencode%-darwin", "opencode%-linux", "/opencode$" },
          argv_patterns = { "bunx%s+opencode", "npx%s+opencode", "/opencode$" },
          title_patterns = { "opencode" },
        },
      },
    })

    -- Prune stale agent-deck state for closed panes (fixes count-never-decrements bug).
    -- agent-deck's own update-status handler only visits panes that currently exist;
    -- when a pane is closed its entry stays in state.agent_states forever and the count
    -- never decrements. get_all_agent_states() returns the live table by reference so
    -- we can mutate it. This handler runs after agent-deck's (registered first above).
    --
    -- Liveness MUST be computed over every mux window, not the one this handler was
    -- called for. update-status fires per GUI window, and each seshy session is its
    -- own workspace in its own window — scoping to `window` marked every pane in every
    -- other workspace as dead and wiped its state on each tick, so hookless agents
    -- outside the focused window never held a status.
    wezterm.on("update-status", function(_window, _pane)
      local all_states = agent_deck.get_all_agent_states()
      local active_ids = {}
      local ok = pcall(function()
        for _, win in ipairs(wezterm.mux.all_windows()) do
          for _, tab in ipairs(win:tabs()) do
            for _, p in ipairs(tab:panes()) do
              active_ids[p:pane_id()] = true
            end
          end
        end
      end)
      -- A partial walk would under-report liveness and prune live panes; skip
      -- this tick instead and let the next one do the pruning.
      if not ok then
        return
      end
      for pane_id in pairs(all_states) do
        if not active_ids[pane_id] then
          all_states[pane_id] = nil
        end
      end
    end)
  end

  -- Per-status icon + urgency rank, shared by the statusline and the session
  -- switcher. Worst-wins ordering: waiting (you must act) > done (your move) >
  -- working > idle. `done` is not an agent-deck status, so we carry our own
  -- icon table rather than relying on agent_deck.get_status_icon for it.
  local nf = wezterm.nerdfonts or {}
  local agent_state_icons = {
    waiting = nf.md_clock_alert or "⏱",
    done    = nf.md_check_circle or "✔",
    working = nf.md_loading or "⟳",
    idle    = nf.cod_circle_small_filled or "○",
  }
  local agent_state_rank = {
    waiting = 4,
    done    = 3,
    working = 2,
    idle    = 1,
  }
  -- `done` means the agent finished its turn and the move is yours. It used to
  -- render as "Idle", which read as "nothing happened here" — the opposite of
  -- the signal. `idle` renders nothing at all: an unattended pane is not news.
  local agent_state_labels = {
    waiting = "Needs Input",
    done    = "Done",
    working = "Working",
    idle    = "",
  }
  local SUPPRESSED_REASONS = { ["your move"] = true, ["submit"] = true, ["message"] = true }

  local function status_color(status, colors)
    if status == "waiting" then return colors.waiting
    elseif status == "done" then return colors.done
    elseif status == "working" then return colors.working
    end
    return nil
  end

  local function format_status_label(status, reason)
    local lbl = agent_state_labels[status] or ""
    local show_reason = reason and reason ~= "" and not SUPPRESSED_REASONS[reason]
    if lbl == "" and not show_reason then return "" end
    local parts = {}
    if lbl ~= "" then parts[#parts + 1] = lbl end
    if show_reason then parts[#parts + 1] = reason end
    return table.concat(parts, " · ")
  end

  local function format_age(secs)
    if not secs or secs < 0 then
      return ""
    end
    if secs < 60 then
      return string.format("%ds", secs)
    elseif secs < 3600 then
      return string.format("%dm", math.floor(secs / 60))
    end
    return string.format("%dh", math.floor(secs / 3600))
  end

  -- Best-effort repo name for a pane: the basename of its current working dir.
  -- Uses only the in-memory mux cwd (no shell-out), tolerates both the Url-object
  -- and the raw `file://host/path` string forms wezterm has returned across
  -- versions, and yields "" on any failure. Branch and dirty are NOT derivable
  -- in-memory — the per-pane state-file bus carries those for out-of-WezTerm
  -- consumers; the render-path rollup deliberately stays shell-out-free.
  -- Returns (basename, fullpath). Both are "" on failure.
  local function pane_repo(p)
    local ok, repo, cwd = pcall(function()
      local url = p:get_current_working_dir()
      if not url then return "", "" end
      local path
      if type(url) == "string" then
        path = url:gsub("^file://[^/]*", "")
      else
        path = url.file_path
      end
      if not path or path == "" then return "", "" end
      path = path:gsub("/+$", "")
      return path:match("([^/]+)$") or "", path
    end)
    if not ok then return "", "" end
    return repo or "", cwd or ""
  end

  -- Read per-pane agent state JSON (written by agent-state hook) for git metadata.
  -- Returns { branch, dirty } or nil when no state file exists for this pane.
  -- Only agent-active panes have state files; normal shell panes return nil.
  local function read_pane_git(pane_id)
    local home = os.getenv("HOME") or ""
    local path = home .. "/.local/state/agents/panes/" .. tostring(pane_id) .. ".json"
    local f = io.open(path, "r")
    if not f then return nil end
    local content = f:read("*a")
    f:close()
    local ok, data = pcall(wezterm.json_parse, content)
    if not ok or type(data) ~= "table" then return nil end
    return {
      branch = type(data.branch) == "string" and data.branch ~= "" and data.branch or nil,
      dirty  = data.dirty == true,
    }
  end

  -- Smart display path: strips noisy parent dirs, returns just the meaningful part.
  --   ~/github/<tier>/<org>/<repo>[/sub]            → <repo>[/sub]
  --   ~/.local/state/seshy/sessions/<s>/<rest>      → <rest>  (rest = repo[/sub] after session/)
  --   ~/.local/state/seshy/sessions/<s>  (root)     → ""  (session name already in workspace row)
  --   ~[/rest]                                       → ~[/rest]
  local function smart_path(full_cwd)
    if not full_cwd or full_cwd == "" then return "" end
    local home = os.getenv("HOME") or ""
    -- Seshy: ~/.local/state/seshy/sessions/<session>[/rest] → {sy}/<session>[/rest]
    local seshy_base = home .. "/.local/state/seshy/sessions"
    if full_cwd == seshy_base or full_cwd:sub(1, #seshy_base + 1) == seshy_base .. "/" then
      local after = full_cwd:sub(#seshy_base + 2)  -- "<session>[/rest]"
      return after ~= "" and ("{sy}/" .. after) or "{sy}"
    end
    -- GitHub: ~/github/<tier>/<org>/<repo>[/sub] → {gh}/<repo>[/sub]
    local gh_base = home .. "/github/"
    if full_cwd:sub(1, #gh_base) == gh_base then
      local rest = full_cwd:sub(#gh_base + 1)             -- "<tier>/<org>/<repo>[/sub]"
      local short = rest:match("^[^/]+/[^/]+/(.+)$") or rest
      return "{gh}/" .. short
    end
    -- Home-relative fallback
    if full_cwd == home then return "{home}" end
    if full_cwd:sub(1, #home + 1) == home .. "/" then
      return "{home}/" .. full_cwd:sub(#home + 2)
    end
    return full_cwd
  end

  -- Extract a pane's agent state from the two sources, worst-source-wins: prefer
  -- the `agent_state` user-var (status|reason|since|agent) emitted by the
  -- lifecycle hooks, else agent-deck's scraped status for hookless agents.
  -- Returns status, reason, since, agent (all nil when the pane has no agent).
  local function pane_agent_state(p, deck_states)
    local status, reason, since, agent
    local uv = p:get_user_vars()
    local raw = uv and uv.agent_state
    if raw and raw ~= "" then
      local s, r, ts, a = raw:match("^([^|]*)|([^|]*)|([^|]*)|(.*)$")
      if s and agent_state_rank[s] then
        status, reason, since, agent = s, r, tonumber(ts), a
      end
    end
    if not status then
      local deck = deck_states[p:pane_id()]
      if deck and agent_state_rank[deck.status] then
        status = deck.status -- working | waiting | idle; no reason/age
        agent = deck.agent
      end
    end
    return status, reason, since, agent
  end

  -- Roll per-pane agent state up to one state per seshy session (= workspace),
  -- AND return the per-pane records visited on the same single walk. For each
  -- live pane: prefer the `agent_state` user-var emitted by the agent lifecycle
  -- hooks (status|reason|since|agent); fall back to agent-deck's scraped status
  -- for panes that set none (hookless agents). Reduce a session's panes
  -- worst-wins, carrying the reason + transition time of the winning pane (oldest
  -- `since` breaks ties so age reflects the longest wait).
  -- Pure in-memory walk of live panes — safe to call on every update-status
  -- tick. Returns two values:
  --   sessions = { [workspace] = { status, reason, since, rank } }
  --   panes    = array of { pane_id, window_id, tab_id, workspace, repo, branch,
  --                          agent, status, reason, since, rank } for every pane
  --              currently holding agent state (branch always "" on this path).
  local function compute_agent_session_states()
    local sessions = {}
    local panes = {}
    local deck_states = agent_deck_ok and agent_deck.get_all_agent_states() or {}

    local ok = pcall(function()
      for _, win in ipairs(wezterm.mux.all_windows()) do
        local workspace = win:get_workspace()
        local window_id = win:window_id()
        for _, tab in ipairs(win:tabs()) do
          local tab_id = tab:tab_id()
          for _, p in ipairs(tab:panes()) do
            local status, reason, since, agent = pane_agent_state(p, deck_states)
            if status then
              local rank = agent_state_rank[status]
              -- Per-pane record — same walk, in-memory only. Enough to activate
              -- the exact pane later (window/tab/pane id + workspace).
              panes[#panes + 1] = {
                pane_id = p:pane_id(),
                window_id = window_id,
                tab_id = tab_id,
                workspace = workspace,
                repo = (function() local r, _ = pane_repo(p); return r end)(),
                branch = "", -- not in-memory; the state-file bus carries it
                agent = agent or "",
                status = status,
                reason = reason or "",
                since = since,
                rank = rank,
              }
              -- Session rollup. Higher rank wins; on a tie the older `since`
              -- (smaller number) wins so age reflects the longest-running pane.
              -- A pane with a real `since` beats one without (nil sorts last).
              local cur = sessions[workspace]
              local replace = false
              if not cur or rank > cur.rank then
                replace = true
              elseif rank == cur.rank then
                local a, b = since, cur.since
                if a and (not b or a < b) then
                  replace = true
                end
              end
              if replace then
                sessions[workspace] = {
                  status = status,
                  reason = reason or "",
                  since = since,
                  rank = rank,
                }
              end
            end
          end
        end
      end
    end)
    if not ok then
      return {}, {}
    end
    return sessions, panes
  end

  -- The rollup feeds the statusline, which tabline re-renders on every
  -- update-status tick (status_update_interval = 150 ms) for every window. A
  -- full mux walk at that rate is wasted work: the state only changes on hook
  -- events, and every surface that reads it renders whole seconds. One-second
  -- cache — os.time() has second granularity, so the compare IS the TTL.
  local rollup_cache = { at = -1, sessions = {}, panes = {} }
  local function agent_session_states()
    local now = os.time()
    if now ~= rollup_cache.at then
      local sessions, panes = compute_agent_session_states()
      rollup_cache = { at = now, sessions = sessions, panes = panes }
    end
    return rollup_cache.sessions, rollup_cache.panes
  end

  -- The GUI window currently displaying `workspace`, or nil when no window shows
  -- it. A background workspace still owns a mux window, so mux presence alone
  -- does not answer "is this on screen".
  local function gui_window_for_workspace(workspace)
    if not workspace or workspace == "" then
      return nil
    end
    local windows = {}
    pcall(function()
      windows = wezterm.mux.all_windows()
    end)
    for _, w in ipairs(windows) do
      local ok_ws, ws = pcall(function()
        return w:get_workspace()
      end)
      if ok_ws and ws == workspace then
        -- Guarded per window, not once around the whole loop: several mux
        -- windows can share a workspace and only one of them is on screen, so a
        -- throw on an unattached window must not end the scan before it reaches
        -- the attached one.
        local ok_gui, gui = pcall(function()
          return w:gui_window()
        end)
        if ok_gui and gui then
          return gui
        end
      end
    end
    return nil
  end

  -- Go to a session, correctly with more than one GUI window open. Each GUI
  -- window carries its own workspace, so the target may already be on screen in
  -- a different window: focus that window instead of retargeting this one, which
  -- would put two windows on the same workspace and abandon the one the user was
  -- reading. SwitchToWorkspace is the fallback for a workspace with no window.
  -- `spawn_cwd` (optional) roots the first pane when the workspace is created.
  local function switch_to_workspace(win, pane, name, spawn_cwd)
    if not name or name == "" then
      return
    end
    local ok_active, active = pcall(function()
      return win:active_workspace()
    end)
    if ok_active and active == name then
      return
    end
    local gui = gui_window_for_workspace(name)
    if gui then
      pcall(function()
        gui:focus()
      end)
      return
    end
    local act = spawn_cwd and wezterm.action.SwitchToWorkspace({ name = name, spawn = { cwd = spawn_cwd } })
      or wezterm.action.SwitchToWorkspace({ name = name })
    win:perform_action(act, pane)
  end

  -- Activate the exact pane a rollup record points at. Pane/tab ids are global,
  -- so the mux calls front the right tab + pane even in a background workspace.
  -- Focus then follows the pane's own GUI window when it has one: activating a
  -- mux tab does not move focus between GUI windows, so without this the picker
  -- silently re-targeted a pane in a window the user could not see.
  -- Best-effort — a since-closed pane resolves to nil and no-ops.
  local function activate_agent_pane(win, gui_pane, rec)
    if not rec or not rec.pane_id then
      return
    end
    local mux_win
    pcall(function()
      local mp = wezterm.mux.get_pane(rec.pane_id)
      if not mp then
        return
      end
      local tab = mp:tab()
      if tab then
        tab:activate()
        mux_win = tab:window()
      end
      mp:activate()
    end)
    -- Separate pcall: resolving the GUI window must not be able to skip the
    -- pane activation above.
    local gui
    if mux_win then
      pcall(function()
        gui = mux_win:gui_window()
      end)
    end
    if gui then
      pcall(function()
        gui:focus()
      end)
      return
    end
    switch_to_workspace(win, gui_pane, rec.workspace)
  end

  -- Normalize process names for display. Strips the `.` prefix and `-wrapped`
  -- suffix that Nix wrapping adds (e.g. `.claude-wrapped` → `claude`,
  -- `.code-wrapped` → `code`).
  local function normalize_proc(raw)
    if not raw or raw == "" then return raw end
    return (raw:gsub("^%.", ""):gsub("%-wrapped$", ""))
  end

  -- Best-effort short label for a pane: foreground process first (always current),
  -- then stored agent name (may be stale), then OSC title, then "". Preferring
  -- the live process avoids showing a previous agent's name after switching tools.
  local function pane_proc(p, agent)
    local ok, proc_name = pcall(function()
      local proc = p:get_foreground_process_name()
      if proc and proc ~= "" then
        return normalize_proc((proc:gsub("/+$", "")):match("([^/]+)$") or "")
      end
      return nil
    end)
    if ok and proc_name and proc_name ~= "" then
      return proc_name
    end
    if agent and agent ~= "" then
      return agent
    end
    local ok2, title = pcall(function() return normalize_proc(p:get_title() or "") end)
    return (ok2 and title) or ""
  end

  -- Best-effort tab segment: the tab's title, else the active pane's process,
  -- else the 1-based index. Never errors.
  local function tab_label(tab, index, active_pane)
    local ok, title = pcall(function()
      return tab:get_title() or ""
    end)
    if ok and title and title ~= "" then
      return title
    end
    if active_pane then
      local proc = pane_proc(active_pane, nil)
      if proc ~= "" then
        return proc
      end
    end
    return "tab " .. tostring(index)
  end

  -- Names of seshy sessions from `sy list` (header row skipped, first column).
  -- Returns (names, ok). `ok` is false when the shell-out failed, which callers
  -- must distinguish from a genuinely empty list: an empty list is authoritative
  -- ("no sessions"), a failure is not.
  local function seshy_session_names(sy_bin)
    if not sy_bin or sy_bin == "" then
      return {}, false
    end
    local names = {}
    local ok, out = pcall(function()
      local success, stdout = wezterm.run_child_process({ sy_bin, "list" })
      if not success then
        error("sy list failed")
      end
      return stdout
    end)
    if not ok or not out then
      return {}, false
    end
    local first = true
    for _, line in ipairs(wezterm.split_by_newlines(out)) do
      if first then
        first = false
      elseif line ~= "" then
        local name = line:match("^(%S+)")
        if name then
          names[#names + 1] = name
        end
      end
    end
    return names, true
  end

  -- `sy` is resolved to an absolute path from env.json: wezterm.run_child_process
  -- runs under the GUI process's own environment, whose PATH (when launched from
  -- Finder or the Dock on macOS) omits ~/.local/bin, so a bare "sy" silently fails
  -- and every seshy surface shows no sessions. Hoisted here rather than living in
  -- the workspace-manager block below, because the tab-bar session chips need it
  -- too and they are wired before that block runs.
  local home = os.getenv("HOME") or ""
  local seshy_dir = home .. "/.local/state/seshy/sessions"
  local sy_bin = home .. "/.local/bin/sy"
  do
    local env = utils.load_json_file(utils.get_config_path("env.json"))
    for dir in (env and env.PATH or ""):gmatch("[^:]+") do
      local candidate = dir .. "/sy"
      local fh = io.open(candidate, "r")
      if fh then
        fh:close()
        sy_bin = candidate
        break
      end
    end
  end

  -- `sy list` is a shell-out and the session tree calls it on every open, so
  -- cache it for 5 s. On a failed shell-out keep the previous answer: reporting
  -- zero sessions would empty the dormant view rather than admit the lookup
  -- failed.
  local seshy_cache = { at = -1, names = {} }
  local function seshy_names_cached()
    local now = os.time()
    if now - seshy_cache.at >= 5 then
      local names, ok = seshy_session_names(sy_bin)
      if ok then
        seshy_cache = { at = now, names = names }
      else
        seshy_cache.at = now
      end
    end
    return seshy_cache.names
  end

  -- Active session names: every workspace that currently has a live mux window,
  -- deduplicated. Two mux windows can share one workspace, so the dedup matters
  -- once more than one window is open.
  --
  -- Dormant seshy sessions (present in `sy list`, no live workspace) are
  -- deliberately excluded. The chip strip and the CTRL+SHIFT+<n> keys address
  -- only what is running; dormant sessions are reached from the SUPER+s tree,
  -- which lists them under ^d.
  local function active_session_names()
    local seen, names = {}, {}
    pcall(function()
      for _, win in ipairs(wezterm.mux.all_windows()) do
        local n = win:get_workspace()
        if n and n ~= "" and not seen[n] then
          seen[n] = true
          names[#names + 1] = n
        end
      end
    end)
    return names
  end

  -- Stable session slots, backing both the CTRL+SHIFT+<n> jump keys and the
  -- tab-bar chips. Every display surface here sorts by urgency or recency, and
  -- both reorder constantly, so the slot cannot come from the sort: CTRL+SHIFT+3
  -- must reach the same session every time. A slot is claimed on first sight
  -- (lowest free of 1..9), held for as long as the workspace stays live, and
  -- released once it is gone. The map lives in wezterm.GLOBAL so it survives a
  -- config reload; GLOBAL does not track nested mutation, so it is read,
  -- rebuilt, and written back whole.
  --
  -- Slots cover ACTIVE sessions only — one number per live workspace. Dormant
  -- seshy sessions get no slot and no chip: numbering them made the strip a list
  -- of everything `sy list` had ever created, most of it not running, and pushed
  -- live sessions past slot 9. Dormant sessions are reached from the SUPER+s
  -- tree (^d), which needs no number.
  --
  -- "default" is the home-base workspace, not a seshy session. It permanently
  -- holds the first slot and never competes with the rest, so it is always on
  -- the strip even when it is the only session running.
  --
  -- Numbering starts at 1, matching the tab keys (SUPER+1..9) rather than a
  -- 0-based array. That costs one addressable session: default takes 1 and the
  -- rest get 2..9, so eight are reachable by key instead of nine.
  local DEFAULT_WORKSPACE = "default"
  local DEFAULT_SLOT = 1
  local MAX_SLOT = 9

  local function compute_session_slots()
    local prev = wezterm.GLOBAL.workspace_slots
    if type(prev) ~= "table" then
      prev = {}
    end

    local names = active_session_names()
    -- The mux walk came up empty. That is a lookup failure, not a world with no
    -- sessions — a running GUI always has at least the window being rendered —
    -- so rebuilding from it would drop every slot.
    if #names == 0 then
      return prev
    end

    local present = {}
    for _, n in ipairs(names) do
      present[n] = true
    end

    -- Carry forward every slot whose session is still around. The rest free up.
    -- DEFAULT_SLOT is reserved before the walk so no seshy session can hold it,
    -- and a duplicate in a stale GLOBAL map loses rather than colliding.
    local slots, taken = {}, {}
    taken[DEFAULT_SLOT] = true
    for name, slot in pairs(prev) do
      if
        present[name]
        and name ~= DEFAULT_WORKSPACE
        and type(slot) == "number"
        and not taken[slot]
      then
        slots[name] = slot
        taken[slot] = true
      end
    end

    -- Claim the lowest free slot for anything newly seen, in name order so a
    -- batch of new sessions numbers deterministically rather than by mux order.
    local fresh = {}
    for _, n in ipairs(names) do
      if n ~= DEFAULT_WORKSPACE and not slots[n] then
        fresh[#fresh + 1] = n
      end
    end
    table.sort(fresh)
    local probe = 1
    for _, name in ipairs(fresh) do
      while probe <= MAX_SLOT and taken[probe] do
        probe = probe + 1
      end
      -- Past the last slot: the session still appears in the picker, just with
      -- no chip number and no jump key.
      if probe > MAX_SLOT then
        break
      end
      slots[name] = probe
      taken[probe] = true
    end

    -- "default" is always reachable — SwitchToWorkspace creates it on demand —
    -- so it holds its slot whether or not it currently exists in the mux.
    slots[DEFAULT_WORKSPACE] = DEFAULT_SLOT

    -- Only write when something actually moved. This runs on every status tick.
    local changed = false
    for name, slot in pairs(slots) do
      if prev[name] ~= slot then
        changed = true
        break
      end
    end
    if not changed then
      for name in pairs(prev) do
        if slots[name] == nil then
          changed = true
          break
        end
      end
    end
    if changed then
      wezterm.GLOBAL.workspace_slots = slots
    end
    return slots
  end

  -- The chip strip asks for slots on every status tick, once per window. Cache
  -- for a second, same as the agent rollup: a session cannot appear and need a
  -- number in less time than that.
  local slots_cache = { at = -1, slots = {} }
  local function session_slots()
    local now = os.time()
    if now ~= slots_cache.at then
      slots_cache = { at = now, slots = compute_session_slots() }
    end
    return slots_cache.slots
  end

  -- Workspace recency. The session tree sorts live sessions most-recent-first,
  -- but WezTerm exposes no per-workspace last-used timestamp in Lua, so we keep
  -- our own: stamp the focused window's workspace on each status tick. Without
  -- it, recency was derived purely from agent `since` values, which sorted every
  -- workspace holding no agent to the bottom — including the shell session you
  -- were in a second ago. wezterm.GLOBAL survives config reloads; it does not
  -- track nested mutation, so the table is read, updated, and written back whole.
  local touch_throttle = {}
  local function touch_workspace(name)
    if not name or name == "" then
      return
    end
    local now = os.time()
    -- Sorting is coarse; a 5 s resolution keeps the write off the render path.
    if touch_throttle[name] and now - touch_throttle[name] < 5 then
      return
    end
    touch_throttle[name] = now
    local t = wezterm.GLOBAL.workspace_last_active or {}
    t[name] = now
    wezterm.GLOBAL.workspace_last_active = t
  end

  local function workspace_last_active(name)
    local t = wezterm.GLOBAL.workspace_last_active
    return type(t) == "table" and t[name] or nil
  end

  wezterm.on("update-status", function(window, _pane)
    -- Prefer the focused window so a background workspace does not keep
    -- refreshing its own recency. is_focused() postdates some WezTerm builds;
    -- if the call is unavailable, stamp anyway rather than degrade to silence.
    local ok, focused = pcall(function()
      return window:is_focused()
    end)
    if (not ok) or focused then
      pcall(function()
        touch_workspace(window:active_workspace())
      end)
    end
  end)

  -- Build the full session tree in ONE mux walk: workspace -> tab -> pane, every
  -- live pane included (not just agent panes), each decorated with its agent
  -- state where present. Also returns the flat "attention" list (rank >=
  -- working) urgency-ordered, and folds in dormant seshy sessions (present in
  -- `sy list` but not live) as leaf workspace entries. Pure in-memory plus one
  -- optional `sy list` shell-out; every mux call is pcall-guarded so a
  -- since-closed pane degrades one node, never the walk.
  -- Returns { workspaces = <ordered array of workspace nodes>, attention = <recs> }.
  -- workspace node = { name, dormant, rank, since, status, tabs = { tab node } }
  -- tab node       = { tab_id, index, title, panes = { pane rec } }
  -- pane rec       = { pane_id, window_id, tab_id, workspace, tab_title, repo,
  --                    title, agent, status, reason, since, rank }
  local function session_tree()
    local deck_states = agent_deck_ok and agent_deck.get_all_agent_states() or {}
    local workspaces = {}
    local ws_index = {}
    local attention = {}
    local live_names = {}

    pcall(function()
      for _, win in ipairs(wezterm.mux.all_windows()) do
        local workspace = win:get_workspace()
        local window_id = win:window_id()
        local ws = ws_index[workspace]
        if not ws then
          ws = {
            name = workspace,
            dormant = false,
            rank = 0,
            since = nil,
            -- Seeded from our own recency stamp; agent `since` values below only
            -- ever raise it, so a session with no agent still sorts by real use.
            last_active = workspace_last_active(workspace),
            status = nil,
            tabs = {},
          }
          ws_index[workspace] = ws
          live_names[workspace] = true
          workspaces[#workspaces + 1] = ws
        end
        for ti, tab in ipairs(win:tabs()) do
          local infos = tab:panes_with_info()
          local active_pane
          for _, info in ipairs(infos) do
            if info.is_active then
              active_pane = info.pane
            end
          end
          local resolved_active = active_pane or (infos[1] and infos[1].pane)
          local tnode = {
            tab_id = tab:tab_id(),
            index = ti,
            title = tab_label(tab, ti, resolved_active),
            -- A tab jump is "activate this tab's active pane" — carry its id so
            -- the switcher reuses activate_agent_pane for tabs too.
            active_pane_id = resolved_active and resolved_active:pane_id() or nil,
            panes = {},
          }
          for _, info in ipairs(infos) do
            local p = info.pane
            local status, reason, since, agent = pane_agent_state(p, deck_states)
            local rank = status and agent_state_rank[status] or 0
            local pid = p:pane_id()
            local repo, cwd = pane_repo(p)
            local git = read_pane_git(pid)
            local rec = {
              pane_id = pid,
              window_id = window_id,
              tab_id = tnode.tab_id,
              workspace = workspace,
              tab_title = tnode.title,
              repo = repo,
              cwd = cwd,
              branch = git and git.branch or nil,
              dirty = git and git.dirty or false,
              title = pane_proc(p, agent),
              agent = agent or "",
              status = status,
              reason = reason or "",
              since = since,
              rank = rank,
            }
            tnode.panes[#tnode.panes + 1] = rec
            if since and (not ws.last_active or since > ws.last_active) then
              ws.last_active = since
            end
            if rank >= agent_state_rank.working then
              attention[#attention + 1] = rec
              if rank > ws.rank or (rank == ws.rank and since and (not ws.since or since < ws.since)) then
                ws.rank, ws.since, ws.status = rank, since, status
              end
            end
          end
          ws.tabs[#ws.tabs + 1] = tnode
        end
      end
    end)

    -- Dormant seshy sessions: present in `sy list` but not a live workspace.
    -- Cached: the ^d / ^x round trips reopen the tree several times a second,
    -- and `sy list` is a shell-out on each open.
    for _, name in ipairs(seshy_names_cached()) do
      if not ws_index[name] then
        local ws = { name = name, dormant = true, rank = 0, since = nil, status = nil, tabs = {} }
        ws_index[name] = ws
        workspaces[#workspaces + 1] = ws
      end
    end

    -- Attention list urgency-ordered: rank desc, then oldest `since` first.
    local now = os.time()
    table.sort(attention, function(a, b)
      if a.rank ~= b.rank then
        return a.rank > b.rank
      end
      return (a.since or now) < (b.since or now)
    end)

    return { workspaces = workspaces, attention = attention }
  end

  -- Shared palette for every agent-state surface (session chips, session tree),
  -- read from the active window's resolved palette so it tracks colorscheme
  -- changes (lantern). Falls back to config_data.colors (set at startup) when the
  -- palette isn't available yet.
  -- ANSI indices (1-based Lua): 1=black 2=red 3=green 4=yellow 5=blue 6=magenta 7=cyan 8=white
  local function tree_colors(win)
    local ok, pal = pcall(function()
      return win:effective_config().resolved_palette
    end)
    pal = (ok and pal) or (config_data and config_data.colors) or {}
    local a, b = pal.ansi or {}, pal.brights or {}
    return {
      ws_live  = b[7] or b[8] or pal.foreground or "#c0caf5",   -- bright cyan/white — live session
      ws_dorm  = a[8] or pal.foreground or "#a9b1d6",           -- ansi-white (mid-gray) — dormant
      dir_ic   = a[5] or "#7aa2f7",                             -- ansi blue — folder icon (softer than bright)
      waiting  = b[2] or a[2] or "#f7768e",                     -- bright red — needs input (status signal: keep vivid)
      done     = b[3] or a[3] or "#9ece6a",                     -- bright green — finished (status signal: keep vivid)
      working  = b[4] or a[4] or "#e0af68",                     -- bright yellow — running (status signal: keep vivid)
      idle     = a[8] or "#a9b1d6",                             -- ansi-white (mid-gray) — idle
      name     = pal.foreground or "#c0caf5",
      reason   = a[6] or "#bb9af7",                             -- ansi magenta — muted; reason is secondary info
      age      = a[8] or "#a9b1d6",                             -- ansi-white (mid-gray) — timestamps
      chrome   = b[1] or "#414868",                             -- bright-black — intentionally dim tree lines
      badge_bg = pal.cursor_bg or b[1] or "#414868",            -- subtle chip background for pane badges
      ghost    = a[8] or pal.foreground or "#a9b1d6",            -- muted bracketed match suffix
      ansi     = a,                                              -- raw ansi array for badge color slots
      brights  = b,
    }
  end

  -- Statusline component: name the single worst blocked session and its age,
  -- then append how many sessions hold actionable state in total so the user
  -- sees both which is worst and how many others are demanding attention. A
  -- single mux walk (the shared rollup) feeds both the worst pick and the count.
  --
  -- "Actionable" is rank >= working (waiting/done/working); idle is excluded.
  -- When nothing is actionable the component renders nothing (no worst, no `0`
  -- count) — idle-only state is not worth statusline space. When exactly one
  -- session is actionable the count suffix is omitted as redundant.
  local function agent_status()
    local sessions = agent_session_states()
    local now = os.time()
    local best_name, best, count = nil, nil, 0
    for name, st in pairs(sessions) do
      if st.rank >= agent_state_rank.working then
        count = count + 1
        if
          not best
          or st.rank > best.rank
          or (st.rank == best.rank and (st.since or now) < (best.since or now))
        then
          best_name, best = name, st
        end
      end
    end
    if not best then
      return ""
    end
    local icon = agent_state_icons[best.status] or "●"
    local text = " " .. icon
    -- Multiple sessions needing attention: append count so the signal scales.
    if count > 1 then
      text = text .. " " .. count
    end
    return wezterm.format({ { Text = text .. " " } })
  end

  -- Tab-bar session chips: one `<slot> <glyph> <name>` chip per ACTIVE session,
  -- ordered by slot so the strip never moves under you. Slot 1 is the "default"
  -- home-base workspace, so the chip you are standing in is always on the strip.
  --
  -- The strip is the live-session list, not the seshy inventory: a name appears
  -- here only while it has a live workspace. It always renders, "default" alone
  -- included — the strip is where the user reads which session they are in, so
  -- suppressing it at one chip made the answer disappear exactly when the layout
  -- was simplest.
  --
  -- The glyph carries agent state (waiting / done / working / idle), so a blocked
  -- background session is visible without opening anything. A session with no
  -- agent at all shows a bare dot.
  --
  -- Names are truncated so the strip cannot grow without bound. Nine sessions
  -- with long names would otherwise run into the native tab strip; the full names,
  -- repos, and branches live in the SUPER+s tree.
  --
  -- Signature is tabline's: a function component is called with the window and
  -- must return a string, so the colored run is pre-rendered with wezterm.format.
  local CHIP_NAME_MAX = 16

  local function session_chips(window)
    local slots = session_slots()
    local ordered = {}
    for name, slot in pairs(slots) do
      ordered[#ordered + 1] = { name = name, slot = slot }
    end
    if #ordered == 0 then
      return ""
    end
    table.sort(ordered, function(a, b)
      return a.slot < b.slot
    end)

    local sessions = agent_session_states()
    local active = ""
    pcall(function()
      active = window:active_workspace()
    end)
    local colors = tree_colors(window)

    local items = {}
    for _, entry in ipairs(ordered) do
      local st = sessions[entry.name]
      local status = st and st.status or nil
      local is_active = entry.name == active
      local label = entry.name
      if #label > CHIP_NAME_MAX then
        label = label:sub(1, CHIP_NAME_MAX - 1) .. "…"
      end
      -- Two independent signals, carried by two independent attributes so they
      -- can never mask each other:
      --   underline  = the session you are standing in
      --   colour+bold = the session that is waiting on YOU
      -- Colouring the whole chip (not just the one-cell glyph) is the point: a
      -- blocked session three chips away has to be legible without reading a
      -- glyph. "Needs attention" is done or waiting — the agent has stopped and
      -- the move is yours. `working` is informational, so it tints only the
      -- glyph and leaves the chip dim.
      local rank = status and agent_state_rank[status] or 0
      local needs_attention = rank >= agent_state_rank.done
      local sc = status_color(status, colors) or colors.idle
      local fg
      if needs_attention then
        fg = sc
      elseif is_active then
        fg = colors.name
      else
        fg = colors.chrome
      end
      items[#items + 1] = { Attribute = { Underline = is_active and "Single" or "None" } }
      items[#items + 1] = { Attribute = { Intensity = (is_active or needs_attention) and "Bold" or "Normal" } }
      items[#items + 1] = { Foreground = { Color = fg } }
      items[#items + 1] = { Text = "  " .. tostring(entry.slot) .. " " }
      items[#items + 1] = { Foreground = { Color = sc } }
      items[#items + 1] = { Text = status and (agent_state_icons[status] or "●") or "·" }
      items[#items + 1] = { Foreground = { Color = fg } }
      items[#items + 1] = { Text = " " .. label }
    end
    items[#items + 1] = { Text = " " }
    return wezterm.format(items)
  end

  -- CTRL+SHIFT+<n> jumps straight to the session holding slot <n>, the same
  -- number the chip shows. Slot 1 is the "default" home-base workspace.
  --
  -- CTRL, not SUPER: macOS reserves CMD+SHIFT+3/4/5 for screenshots and never
  -- delivers them to the application, so three of the nine slots would have been
  -- silently unreachable. CTRL+SHIFT+<digit> is unbound elsewhere in this config
  -- (the plain digits are tab switching under CTRL and SUPER, without SHIFT).
  --
  -- `phys:` binds the physical key position. WezTerm's key_map_preference
  -- defaults to "Mapped", where SHIFT+1 produces "!", so a plain
  -- { key = "1", mods = "CTRL|SHIFT" } never matches. The mapped alternative
  -- ({ key = "!", mods = "CTRL" }) would break on any non-US layout.
  config.keys = config.keys or {}
  for slot = DEFAULT_SLOT, MAX_SLOT do
    table.insert(config.keys, {
      key = "phys:" .. tostring(slot),
      mods = "CTRL|SHIFT",
      action = wezterm.action_callback(function(win, pane)
        if keybindings.locked_mode then
          win:perform_action({ SendKey = { key = tostring(slot), mods = "CTRL|SHIFT" } }, pane)
          return
        end
        local target
        for name, s in pairs(session_slots()) do
          if s == slot then
            target = name
            break
          end
        end
        -- Unassigned slot: no session holds this number. Do nothing rather than
        -- guess at a neighbour.
        if not target then
          return
        end
        local live = false
        pcall(function()
          for _, w in ipairs(wezterm.mux.all_windows()) do
            if w:get_workspace() == target then
              live = true
            end
          end
        end)
        -- Slots only cover live workspaces, so the dormant branch is a race: the
        -- session died between the cached slot map and this keypress. Root the
        -- first pane at the seshy session dir, as the session tree does for a
        -- dormant row. "default" is not a seshy session and has no such dir.
        local spawn_cwd = nil
        if not live and target ~= DEFAULT_WORKSPACE then
          spawn_cwd = seshy_dir .. "/" .. target
        end
        switch_to_workspace(win, pane, target, spawn_cwd)
      end),
    })
  end

  local tabline_ok, tabline = plugin_loader.load("tabline")
  if not tabline_ok then
    wezterm.log_warn("Failed to load tabline.wez: " .. tostring(tabline))
  end
  if tabline_ok then
    tabline.setup({
      options = {
        theme = config.colors,
        -- Enabled so each tab title can carry its own agent-state icon (native
        -- click-to-switch is the only clickable per-tab affordance WezTerm has).
        tabs_enabled = true,
        section_separators = {
          left = "",
          right = "",
        },
        component_separators = {
          left = "",
          right = "",
        },
        tab_separators = {
          left = " ",
          right = " ",
        },
      },
      sections = {
        tabline_a = {
          "mode",
          locked_indicator,
        },
        tabline_b = {},
        tabline_c = {},
        -- The whole right-hand group lives in `x`, with `y` and `z` empty. That
        -- is deliberate, not laziness: tabline emits a section separator between
        -- every pair of non-empty sections, and both agent_status and the old
        -- `workspace` cap render "" or duplicate text most of the time — which
        -- left a bare powerline wedge floating at the right edge. One section
        -- means zero separators, so the chips end flush against the edge.
        --
        -- `workspace` is gone outright: the active chip already names the session
        -- you are in, three cells to the left of where the cap used to sit.
        --
        -- agent_status leads so the chips stay rightmost. "ResetAttributes" is
        -- tabline's own guard — it re-emits the section's colors after our
        -- formatted run so nothing bleeds past it.
        tabline_x = { agent_status, session_chips, "ResetAttributes" },
        tabline_y = {},
        tabline_z = {},
        -- Use cwd for both active and inactive tabs so that Nix-wrapped process
        -- names (e.g. .claude-wrapped) never appear in the tab bar.
        tab_active = {
          "index",
          { "parent", padding = 0 },
          "/",
          { "cwd", padding = { left = 0, right = 1 } },
        },
        tab_inactive = {
          "index",
          { "cwd", padding = { left = 0, right = 1 } },
        },
      },
      extensions = {},
    })
    tabline.apply_to_config(config)
  end

  -- Fallback: if tabline plugin didn't load, use native right_status for locked indicator
  if not tabline_ok then
    wezterm.on("update-right-status", function(window, _pane)
      local mode_text = locked_indicator()
      window:set_right_status(wezterm.format({
        { Text = mode_text },
      }))
    end)
  end

  -- Post-process window padding for macOS
  if utils.is_darwin() then
    -- Set window padding AFTER tabline.apply_to_config, which zeroes all padding
    config.window_padding = {
      left = "1cell",
      right = "1cell",
      top = "1cell",
      bottom = "0cell",
    }
  end

  -- sravioli UI toolkit: warp (stdlib) must load first so ribbon/sigil's
  -- deps.lua `require("warp.api")` resolves off package.path. These bypass
  -- wezterm.plugin.require entirely (see plugin_loader).
  plugin_loader.load("warp")
  local ribbon_ok, ribbon = plugin_loader.load("ribbon")
  if not ribbon_ok then
    wezterm.log_warn("Failed to load ribbon.wz: " .. tostring(ribbon))
  end
  local sigil_ok, sigil = plugin_loader.load("sigil")
  if not sigil_ok then
    wezterm.log_warn("Failed to load sigil.wz: " .. tostring(sigil))
  end
  if sigil_ok then
    sigil.setup({
      -- Claude Code's foreground process basename is `.claude-wrapped` (a Bun
      -- Mach-O binary); register it (and aliases) so tabs show a clean glyph
      -- instead of the raw wrapper name.
      overrides = {
        claude = {
          name = "Claude",
          -- Claude's brand sparkle (U+2733), in the brand orange. Marks every
          -- Claude Code tab consistently instead of the raw OSC spinner glyph.
          icon = "✳",
          color = "#D97757",
          aliases = { ".claude-wrapped", "claude-code", "claude-wrapped" },
        },
        codex = {
          name = "Codex",
          icon = nf.md_robot or "C",
          color = "#10A37F",
          aliases = { ".codex-wrapped", "codex-wrapped", "codex" },
        },
      },
    })
  end

  -- Session tree icons: prefer sigil.symbol() for named structural icons so they
  -- stay consistent with the rest of the UI toolkit, fall back to nerdfonts
  -- directly. Agent-state icons live near agent_state_icons (above).
  local tree_icons = {
    session = (sigil_ok and sigil.symbol("Workspace")) or nf.cod_briefcase or "",
    dormant = nf.md_sleep or "󰒲",
    tab     = nf.md_tab or "󰓩",
    folder  = (sigil_ok and sigil.symbol("Folder")) or nf.md_folder or "",
    attn    = nf.md_alert or "󰀪",
    branch  = nf.cod_git_branch or "⎇",
  }

  -- Deterministic pane identity: hash pane_id → character name from sci-fi/fantasy.
  -- Same id yields the same name+color on every surface (tab title, session tree,
  -- statusline) so panes are cross-referenceable. Knuth multiplicative hash spreads
  -- sequential IDs across the full name space — plain modulo clusters low IDs.
  local BADGE_NAMES = {
    -- Dune (Herbert)
    "muadib",   "stilgar",  "chani",    "gurney",   "feyd",     "irulan",
    "alia",     "thufir",   "mentat",   "kwisatz",  "hayt",     "korba",    "scytale",
    -- Hyperion (Simmons)
    "shrike",   "kassad",   "silenus",  "brawne",   "aenea",    "raul",
    "consul",   "ummon",    "moneta",   "sol",      "endymion", "templar",
    -- Lord of the Rings (Tolkien)
    "aragorn",  "gandalf",  "samwise",  "legolas",  "gimli",    "boromir",
    "faramir",  "eowyn",    "galadriel","elrond",   "saruman",  "theoden",
    "frodo",    "merry",    "pippin",   "glorfindel","haldir",
    -- Stormlight / Mistborn (Sanderson)
    "kaladin",  "dalinar",  "szeth",    "jasnah",   "shallan",  "adolin",
    "wit",      "vin",      "elend",    "kelsier",  "sazed",    "spook",
    "breeze",   "marsh",    "nightblood","hoid",    "vasher",   "renarin",
    "lift",     "taravangian","navani",
    -- Empire of Silence (Ruocchio)
    "hadrian",  "valka",    "pallino",  "lorian",   "bassander",
    "vorgossos","gibson",   "siran",    "elara",    "kharn",
    -- First Law (Abercrombie)
    "logen",    "glokta",   "jezal",    "bayaz",    "ferro",    "dogman",
    "shivers",  "monza",    "cosca",    "friendly", "temple",   "caul",     "chella",
    -- Kingkiller Chronicle (Rothfuss)
    "kvothe",   "denna",    "bast",     "auri",     "elodin",   "kilvin",
    "simmon",   "wilem",    "devi",     "tempi",    "felurian", "ambrose",
    -- Neuromancer (Gibson)
    "case",     "molly",    "wintermute","armitage", "riviera",  "maelcum",  "flatline",
    -- Red Rising (Brown)
    "darrow",   "sevro",    "mustang",  "cassius",  "roque",    "victra",   "lysander",
    -- Book of the New Sun (Wolfe)
    "severian", "thecla",   "dorcas",   "agia",     "baldanders","typhon",  "jonas",
    -- Broken Empire (Lawrence)
    "jorg",     "makin",    "rike",     "sageous",  "miana",    "coddin",   "jalan",    "snorri",
    -- Goblin Emperor (Addison)
    "maia",     "csevet",   "cala",     "beshelar", "setheris",
    -- Necroscope (Lumley)
    "keogh",    "dragosani","zek",      "nathan",
    -- Covenant of Steel (Ryan)
    "alwyn",    "evadine",  "deckin",   "tiler",
    -- Raven's Shadow / Blood Song (Ryan)
    "vaelin",   "reva",     "nortah",   "caenis",   "barkus",
    -- Will of the Many (Islington)
    "vis",      "emissa",   "callidus", "acqua",    "ulciscor",
    -- Inheritance Cycle (Paolini)
    "eragon",   "saphira",  "arya",     "murtagh",  "brom",     "nasuada",  "roran",    "oromis",   "galbatorix",
    -- Blacktongue Thief / Daughters' War (Buehlman)
    "kinch",    "galva",    "norrigal",
    -- Between Two Fires (Buehlman)
    "thomas",
    -- Alien
    "ripley",   "newt",     "bishop",   "hicks",    "ash",      "hudson",   "vasquez",  "dallas",   "lambert",  "burke",
    -- Predator
    "dutch",    "mac",      "blain",    "harrigan", "dillon",
    -- Blade Runner
    "deckard",  "rachael",  "roy",      "pris",     "gaff",     "joi",      "luv",
    -- Metal Gear Solid
    "snake",    "otacon",   "meryl",    "liquid",   "ocelot",   "raiden",   "solidus",  "vamp",     "mantis",   "wolf",
    "quiet",    "paz",      "skull",
    -- Resident Evil
    "leon",     "claire",   "jill",     "wesker",   "ada",      "barry",    "chris",    "ethan",    "heisenberg","dimitrescu",
  }

  local function pane_badge(pane_id)
    local h = pane_id * 2654435761  -- Knuth multiplicative hash
    return BADGE_NAMES[(h % #BADGE_NAMES) + 1]
  end

  -- Return the ansi palette color for a pane badge. Uses ansi slots 2-7
  -- (6 distinct, muted hues: red/green/yellow/blue/magenta/cyan — skips 1=black
  -- and 8=white). Ansi colors are softer than brights, reducing visual noise.
  -- `colors` is tree_colors() result (has .ansi) or cfg.colors from format-tab-title.
  local function pane_badge_color(pane_id, colors)
    local h = pane_id * 2654435761
    local slot = (h % 6) + 2  -- ansi slots 2..7
    if type(colors) == "table" then
      local a = colors.ansi or (colors.colors and colors.colors.ansi)
      if type(a) == "table" and a[slot] then return a[slot] end
      -- fallback: brights (no ansi in this context, e.g. format-tab-title)
      local b = colors.brights or colors
      if type(b) == "table" then return b[(h % 6) + 2] end
    end
    return nil
  end

  -- lantern: runtime appearance picker (colorschemes, fonts, GPU, opacity, …).
  -- Its bundled "flames" (the choice sets) live at <plugin_dir>/plugin/lantern/
  -- flames; lantern.meta locates that dir from either a plugin url containing
  -- "lantern.wz" OR wezterm.GLOBAL.__lantern_plugin_dir. Our Nix-store paths
  -- (/nix/store/HASH-source) carry neither, so we seed the global explicitly
  -- BEFORE loading — otherwise register_builtins() (run at api.lua load) wires
  -- the colorscheme/font/gpu wicks with no choices. Its deps.lua (log/memo/
  -- ribbon/warp) is patched to resolve through plugin_loader instead of
  -- wezterm.plugin.require (see patches/lantern-deps-loader.patch).
  wezterm.GLOBAL = wezterm.GLOBAL or {}
  wezterm.GLOBAL.__lantern_plugin_dir = config_data.plugins and config_data.plugins.lantern
  local lantern_ok, lantern = plugin_loader.load("lantern")
  if not lantern_ok then
    wezterm.log_warn("Failed to load lantern.wz: " .. tostring(lantern))
  end
  if lantern_ok then
    lantern.setup({
      log = { enabled = false },
      -- Baseline the picker's "reset" font size to ours so it round-trips.
      default_font = { font_size = config.font_size },
      color = { opacity = config_data.transparency.opacity },
    })
    -- Restore the appearance the user picked in a previous session.
    lantern.rekindle(config)

    -- One entry point (SUPER+SHIFT+l) instead of the upstream CTRL+SHIFT+c/f/…
    -- bindings, which collide with our copy (CTRL+SHIFT+c) and pane-select
    -- (CTRL+SHIFT+f). Picking a category opens that wick's own selector —
    -- lantern.light.<x>() returns a ready WezTerm action.
    local lantern_categories = {
      { id = "colorscheme", label = "Colorscheme", fn = lantern.light.colorscheme },
      { id = "font", label = "Font", fn = lantern.light.font },
      { id = "font_size", label = "Font size", fn = lantern.light.font_size },
      { id = "font_leading", label = "Font leading", fn = lantern.light.font_leading },
      { id = "font_ligatures", label = "Font ligatures", fn = lantern.light.font_ligatures },
      { id = "gpu", label = "GPU / front end", fn = lantern.light.gpu },
      { id = "window_opacity", label = "Window opacity", fn = lantern.light.window_opacity },
      { id = "window_padding", label = "Window padding", fn = lantern.light.window_padding },
      { id = "inactive_pane_opacity", label = "Inactive pane opacity", fn = lantern.light.inactive_pane_opacity },
      { id = "cursor_style", label = "Cursor style", fn = lantern.light.cursor_style },
      { id = "tab_bar_style", label = "Tab bar style", fn = lantern.light.tab_bar_style },
    }

    config.keys = config.keys or {}
    table.insert(config.keys, {
      key = "l",
      mods = "SUPER|SHIFT",
      action = wezterm.action_callback(function(win, pane)
        if keybindings.locked_mode then
          win:perform_action({ SendKey = { key = "l", mods = "SUPER|SHIFT" } }, pane)
          return
        end
        local choices = {}
        for _, cat in ipairs(lantern_categories) do
          choices[#choices + 1] = { id = cat.id, label = cat.label }
        end
        win:perform_action(
          wezterm.action.InputSelector({
            title = "Appearance",
            fuzzy = true,
            choices = choices,
            action = wezterm.action_callback(function(inner_win, inner_pane, id, _label)
              if not id then
                return
              end
              for _, cat in ipairs(lantern_categories) do
                if cat.id == id then
                  inner_win:perform_action(cat.fn(), inner_pane)
                  return
                end
              end
            end),
          }),
          pane
        )
      end),
    })
  end

  -- Smart tab titles using ribbon + sigil. Info priority: dir > proc > OSC title.
  -- Badge (colored pet name) appended at the end so panes are cross-referenceable
  -- with the session tree without counting positions.
  -- Zoom indicator prepended when the active pane is zoomed.
  local SHELLS = { zsh = true, bash = true, fish = true, sh = true, ["-zsh"] = true }

  wezterm.on("format-tab-title", function(tab, _tabs, _panes, cfg, _hover, _max_width)
    -- format-tab-title hands us TabInformation/PaneInformation structs (fields),
    -- NOT MuxTab/Pane objects (methods). Calling methods here throws and aborts
    -- the handler, dropping WezTerm back to its default tab text.
    local pane = tab.active_pane
    local explicit = normalize_proc(tab.tab_title or "")
    local osc = normalize_proc(pane and pane.title or "")
    local proc = pane and pane.foreground_process_name
    if proc then proc = normalize_proc(proc:match("([^/]+)$") or proc) end

    -- A user- (or program-) set, non-numeric tab title always wins (no badge).
    if explicit ~= "" and not explicit:match("^%d+$") then
      return explicit
    end

    -- cwd basename, collapsing $HOME to ~.
    local dir
    local cwd_uri = pane and pane.current_working_dir
    if cwd_uri then
      local cwd = cwd_uri.file_path or tostring(cwd_uri)
      if home ~= "" and cwd == home then
        dir = "~"
      else
        dir = cwd:match("([^/]+)/?$") or cwd
      end
    end

    -- Primary label. Dir is preferred for shells (they set no useful OSC title);
    -- TUIs (nvim, claude, htop…) set their own OSC-2 title which wins over dir.
    local label
    if osc and osc ~= "" and not osc:match("^%d+$") and not SHELLS[osc:lower()] then
      label = osc
    end
    label = label or dir or proc or "shell"

    if not (sigil_ok and ribbon_ok) then
      return label
    end

    local r = ribbon.new("tab")

    -- Agent-state prefix: read the pane's user_var (plain table on PaneInformation,
    -- already base64-decoded by WezTerm). Only non-idle states surface — idle adds
    -- noise to every unattended pane.
    pcall(function()
      local uv = pane and pane.user_vars
      local raw = uv and uv.agent_state
      if not raw or raw == "" then return end
      local s = raw:match("^([^|]*)|")
      local icon = s and s ~= "idle" and agent_state_icons[s]
      if icon then r:append(nil, nil, icon .. " ") end
    end)

    -- Zoom indicator: active pane is filling the window.
    if pane and pane.is_zoomed then
      r:append(nil, nil, nf.md_dock_window and (nf.md_dock_window .. " ") or "⊞ ")
    end

    -- Process icon via sigil (fallback=false: skip unknown procs, no mystery glyph).
    if proc then
      local icon_items = sigil.items(proc, { padding = "right", fallback = false, reset = true })
      if icon_items and #icon_items > 0 then
        r:append_items(icon_items)
      end
    end

    -- Main label (dir / OSC title).
    r:append(nil, nil, label)

    -- Active-pane badge: muted chip for cross-referencing with session tree.
    if pane and pane.pane_id then
      local pid = pane.pane_id
      local bc = pane_badge_color(pid, cfg and cfg.colors or {})
      if bc then
        r:append(nil, "#3b4261", "  ")
        r:append(nil, bc, pane_badge(pid))
      end
    end

    return r:items()
  end)

  -- Hyperlink rules: start with defaults, then add custom patterns
  local hyperlink_rules = wezterm.default_hyperlink_rules()

  -- Nix store paths as file:// links
  table.insert(hyperlink_rules, {
    regex = [[(/nix/store/[a-z0-9]{32}[a-zA-Z0-9._+%-][^\s]*)]],
    format = "file://$1",
  })

  -- owner/repo#NNN → GitHub issue URL
  table.insert(hyperlink_rules, {
    regex = [[([a-zA-Z0-9_.-]+/[a-zA-Z0-9_.-]+)#([0-9]+)]],
    format = "https://github.com/$1/issues/$2",
  })

  config.hyperlink_rules = hyperlink_rules

  -- Extended quick-select patterns
  config.quick_select_patterns = {
    "/nix/store/[a-z0-9]{32}[a-zA-Z0-9._+%-][^\\s]*",
    "[0-9a-f]{40}",
    "(?<![0-9a-f])[0-9a-f]{7}(?![0-9a-f])",
    "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}",
    "/[^\\s]+",
  }

  -- workspace-manager: seshy session picker + layout persistence across restarts.
  -- We feed its switcher from `sy list`, bind it to SUPER+s (see below), and also
  -- surface it in the command palette. We do NOT use the plugin's own
  -- apply_to_config keybindings (they'd shadow vim's CTRL+[).
  local wm_ok, wm = plugin_loader.load("workspace-manager")
  if not wm_ok then
    wezterm.log_warn("Failed to load workspace-manager.wezterm: " .. tostring(wm))
  end
  if wm_ok then
    -- `home`, `seshy_dir`, and `sy_bin` are resolved once near seshy_session_names
    -- above; the session chips need them before this block runs.

    -- Replace the default choice provider: list seshy sessions instead of
    -- scanning a projects dir. `sy list` prints a header row then one row per
    -- session; column 1 is the session name.
    --
    -- The list always leads with a pinned "default" entry — the home-base
    -- workspace WezTerm starts in. Selecting it does SwitchToWorkspace{name=
    -- "default"} (create-if-absent), the one switcher path back from any seshy
    -- session. It's seeded first so it survives an empty/header-only `sy list`
    -- or a missing/erroring `sy` binary (the early return still carries it).
    wm.get_choices = function()
      -- Roll up live agent state once and decorate each session row with its
      -- state icon, reason, and age, sorted so the longest-blocked session is
      -- on top. Sourced from the same helper the statusline reads, so the two
      -- surfaces always agree on which session is worst.
      local sessions, panes = agent_session_states()
      local now = os.time()

      -- Aggregate the per-pane view into per-session (== per-workspace) detail:
      -- repo (in-memory cwd basename; branch/dirty aren't derivable here and the
      -- state-file bus carries them for out-of-WezTerm consumers), total agent
      -- pane count, blocked (rank >= working) count, and the worst pane's agent.
      -- Keyed by workspace, which seshy makes equal to the session name.
      local agg = {}
      for _, rec in ipairs(panes) do
        local a = agg[rec.workspace]
        if not a then
          a = { count = 0, blocked = 0, repo = "", agent = "", worst_rank = 0, worst_status = nil }
          agg[rec.workspace] = a
        end
        a.count = a.count + 1
        if a.repo == "" and rec.repo ~= "" then
          a.repo = rec.repo
        end
        if rec.rank >= agent_state_rank.working then
          a.blocked = a.blocked + 1
        end
        if rec.rank > a.worst_rank then
          a.worst_rank = rec.rank
          a.worst_status = rec.status
          if rec.agent ~= "" then
            a.agent = rec.agent
          end
        end
      end

      local default_choice = { name = "default", path = home, label = "default" }
      local rows = {}

      for _, name in ipairs(seshy_session_names(sy_bin)) do
        -- A seshy session actually named "default" would render twice: once as
        -- the pinned home-base row above, once here. Keep the pinned one.
        if name ~= "default" then
          local st = sessions[name]
          local label = name
          if st then
            local icon = agent_state_icons[st.status] or "●"
            label = icon .. " " .. name
            local a = agg[name]
            if a then
              if a.repo ~= "" then label = label .. "  at " .. a.repo end
              if a.agent ~= "" then label = label .. "  in " .. a.agent end
            end
            local age = st.since and format_age(now - st.since) or ""
            local fmt = format_status_label(st.status, st.reason)
            if fmt ~= "" then label = label .. "  — " .. fmt end
            if age ~= "" then label = label .. "  " .. age end
          end
          table.insert(rows, {
            name = name,
            path = seshy_dir .. "/" .. name,
            label = label,
            -- sort keys (stripped from the choice the plugin sees)
            _rank = st and st.rank or 0,
            _since = st and st.since or nil,
          })
        end
      end

      -- Urgency sort: higher rank first, then older `since` (longer wait), then
      -- name for stability. Stateless sessions (rank 0) fall to the bottom.
      table.sort(rows, function(a, b)
        if a._rank ~= b._rank then
          return a._rank > b._rank
        end
        if a._rank > 0 and a._since ~= b._since then
          return (a._since or now) < (b._since or now)
        end
        return a.name < b.name
      end)

      local choices = { default_choice }
      for _, row in ipairs(rows) do
        table.insert(choices, { name = row.name, path = row.path, label = row.label })
      end
      return choices
    end

    -- Build InputSelector choices from the session tree: a top "needs attention"
    -- zone (actionable panes, urgency-ordered) then the workspace -> tab -> pane
    -- tree as indented box-drawing rows. Each choice id encodes kind + target
    -- (`hdr:`/`attn:`/`ws:`/`tab:`/`pane:`) so the dispatch is level-aware, and
    -- `by_id` maps id -> the record needed to act. Slice 3 adds the filter path
    -- tokens and the jump alphabet; here rows are human-readable and dispatchable.
    -- Sanitize one path segment to a no-whitespace, no-separator token so a
    -- `session/tab/agent` query matches as a fuzzy subsequence.
    local function sanitize_seg(s)
      return (tostring(s or ""):gsub("[%s/·|]+", "-"):gsub("^%-+", ""):gsub("%-+$", ""))
    end

    -- The matchable suffix appended (dimly, off to the right) to a row so
    -- filtering "plays nicely": a `session/tab/agent` slash-path plus quick-filter
    -- tokens (status word, repo). Contiguous ASCII so subsequence matching is
    -- predictable. Every leaf carries its FULL ancestor path so a filter on an
    -- ancestor name keeps the leaf after non-matching parent rows drop out.
    local function match_suffix(ws, tab_title, proc, status, repo)
      local segs = {}
      for _, s in ipairs({ ws, tab_title, proc }) do
        local t = sanitize_seg(s)
        if t ~= "" then
          segs[#segs + 1] = t
        end
      end
      local tokens = {}
      if status and status ~= "" then
        tokens[#tokens + 1] = status
      end
      if repo and repo ~= "" then
        tokens[#tokens + 1] = sanitize_seg(repo)
      end
      local suffix = {}
      local path = table.concat(segs, "/")
      if path ~= "" then
        suffix[#suffix + 1] = path
      end
      if #tokens > 0 then
        suffix[#suffix + 1] = table.concat(tokens, " ")
      end
      if #suffix == 0 then
        return ""
      end
      return "  [" .. table.concat(suffix, "  ") .. "]"
    end

    -- One attention-zone row. Info order: workspace · tab · dir  proc  status reason (age).
    -- Uses ribbon for color + sigil for process icon. `colors` comes from tree_colors(win).
    local function attn_row(rec, now, colors)
      local sc = status_color(rec.status, colors) or colors.idle
      local icon = agent_state_icons[rec.status] or "●"
      local is_urgent = rec.rank and rec.rank >= agent_state_rank.working
      local age = rec.since and format_age(now - rec.since) or ""

      local r = ribbon.new("attn")
      -- warning prefix (only when actionable)
      if is_urgent then
        r:append(nil, colors.waiting, tree_icons.attn .. " ")
      else
        r:append(nil, nil, "  ")
      end
      -- agent status icon
      r:append(nil, sc, icon .. " ")
      -- breadcrumb: workspace · dir  proc  (omit empty parts)
      local crumb = rec.workspace
      if rec.tab_title ~= "" then crumb = crumb .. " · " .. rec.tab_title end
      r:append(nil, colors.name, crumb, "Bold")
      -- "at <path>": location context beyond what the breadcrumb already has
      local attn_dp = smart_path(rec.cwd)
      if attn_dp == "" then attn_dp = rec.repo end
      if attn_dp ~= "" and attn_dp ~= rec.tab_title then
        r:append(nil, colors.chrome, "  ")
        r:append(nil, colors.age, "at ")
        r:append(nil, colors.name, attn_dp)
      end
      -- "on <branch>" for agent-active panes (state file carries it)
      if rec.branch then
        r:append(nil, colors.chrome, "  ")
        r:append(nil, colors.age, "on ")
        r:append(nil, colors.age, rec.branch)
        if rec.dirty then r:append(nil, colors.working, " *") end
      end
      -- "in <proc>": process icon via sigil + proc name
      if rec.title ~= "" then
        r:append(nil, colors.chrome, "  ")
        r:append(nil, colors.age, "in ")
        if sigil_ok then
          local proc_items = sigil.items(rec.title, { fallback = true, padding = "right", reset = true })
          r:append_items(proc_items)
        end
        r:append(nil, colors.name, rec.title)
      end
      -- status label + meaningful reason (suppress generic agent prompts) + age
      local fmt = format_status_label(rec.status, rec.reason)
      if fmt ~= "" then r:append(nil, colors.reason, "  " .. fmt) end
      if age ~= "" then
        r:append(nil, colors.age, "  " .. age)
      end
      -- pane badge: colored pet name for cross-referencing
      local bc = pane_badge_color(rec.pane_id, colors)
      if bc then
        r:append(nil, colors.chrome, "  ")
        r:append(nil, bc, pane_badge(rec.pane_id))
      end
      -- Muted suffix for fuzzy search; visible so selection highlighting stays readable.
      return r:format()
    end

    -- Build InputSelector choices from the tree.
    -- `filter`: nil/"all" = attention zone + live tree (dormant hidden);
    --           "blocked" = flat urgent panes; "agents" = flat all agent panes;
    --           "dormant" = dormant seshy sessions only.
    -- `colors` comes from tree_colors(win) — pass it in from open_session_tree.
    local function session_tree_choices(tree, by_id, filter, colors)
      local choices = {}
      local now = os.time()
      local function add(id, label, rec)
        by_id[id] = rec or true
        choices[#choices + 1] = { id = id, label = label }
      end
      filter = filter or "all"

      -- flat filtered views (blocked / agents): just attention-zone rows
      if filter == "blocked" or filter == "agents" then
        local list = {}
        if filter == "blocked" then
          for _, rec in ipairs(tree.attention) do list[#list + 1] = rec end
        else
          for _, ws in ipairs(tree.workspaces) do
            for _, tnode in ipairs(ws.tabs) do
              for _, rec in ipairs(tnode.panes) do
                if rec.status then list[#list + 1] = rec end
              end
            end
          end
          table.sort(list, function(a, b)
            if a.rank ~= b.rank then return a.rank > b.rank end
            return (a.since or now) < (b.since or now)
          end)
        end
        for _, rec in ipairs(list) do
          add("pane:" .. rec.pane_id, attn_row(rec, now, colors), rec)
        end
        return choices
      end

      -- dormant-only view: show seshy sessions that have no live mux workspace
      if filter == "dormant" then
        for _, ws in ipairs(tree.workspaces) do
          if ws.dormant then
            local r = ribbon.new("dormant")
            r:append(nil, colors.ws_dorm, tree_icons.dormant .. " " .. ws.name)
            add("ws:" .. ws.name, r:format(), { workspace = ws.name, dormant = true })
          end
        end
        return choices
      end

      -- "sessions" view: workspace-only rows sorted by recency (no tab/pane expansion).
      -- Quick overview of all live sessions at a glance.
      if filter == "sessions" then
        local live = {}
        for _, ws in ipairs(tree.workspaces) do
          if not ws.dormant then live[#live + 1] = ws end
        end
        table.sort(live, function(a, b)
          return (a.last_active or 0) > (b.last_active or 0)
        end)
        for i, ws in ipairs(live) do
          local sc = status_color(ws.status, colors)
          local qs = i <= 9 and tostring(i) or string.char(96 + i - 9)
          local r = ribbon.new("ws")
          r:append(nil, colors.chrome, qs .. "  ")
          r:append(nil, sc or colors.ws_live, tree_icons.session .. " ")
          r:append(nil, colors.name, ws.name, "Bold")
          if ws.status then
            r:append(nil, sc or colors.working, "  " .. (agent_state_icons[ws.status] or "●"))
          end
          local age = ws.last_active and format_age(now - ws.last_active) or ""
          if age ~= "" then
            r:append(nil, colors.age, "  " .. age)
          end
          add("ws:" .. ws.name, r:format(), { workspace = ws.name, dormant = false })
        end
        return choices
      end

      -- "all" view: pure workspace tree, recency-sorted. Status is shown inline on
      -- each pane/workspace row — no separate attention zone so nothing is doubled.
      local live_sorted = {}
      for _, ws in ipairs(tree.workspaces) do
        if not ws.dormant then live_sorted[#live_sorted + 1] = ws end
      end
      table.sort(live_sorted, function(a, b)
        return (a.last_active or 0) > (b.last_active or 0)
      end)

      for _, ws in ipairs(live_sorted) do
          -- workspace row: icon + name + rollup status icon (if any)
          local sc = status_color(ws.status, colors)
          local ws_r = ribbon.new("ws")
          ws_r:append(nil, sc or colors.ws_live, tree_icons.session .. " ")
          ws_r:append(nil, colors.name, ws.name, { "Bold", "Single" })
          if ws.status then
            local ws_lbl = agent_state_labels[ws.status] or ""
            ws_r:append(nil, colors.chrome, "  ")
            ws_r:append(nil, sc or colors.working, agent_state_icons[ws.status] or "●")
            if ws_lbl ~= "" then
              ws_r:append(nil, colors.reason, " " .. ws_lbl)
            end
          end
          add("ws:" .. ws.name, ws_r:format(), { workspace = ws.name, dormant = false })

          for ti, tnode in ipairs(ws.tabs) do
            local tlast = ti == #ws.tabs
            local tbranch = tlast and "  └─ " or "  ├─ "
            -- tab row: chrome + tab icon + [index]  title
            local tab_r = ribbon.new("tab")
            tab_r:append(nil, colors.chrome, tbranch)
            tab_r:append(nil, colors.ws_live, tree_icons.tab)
            tab_r:append(nil, colors.chrome, " [" .. tostring(ti) .. "]")
            tab_r:append(nil, colors.chrome, "  ")
            tab_r:append(nil, colors.name, tnode.title)
            add("tab:" .. tnode.tab_id, tab_r:format(), { pane_id = tnode.active_pane_id, workspace = ws.name })

            for pi, rec in ipairs(tnode.panes) do
              local pbranch = (tlast and "     " or "  │  ")
                .. (pi == #tnode.panes and "└─ " or "├─ ")
              -- pane row: <badge>  path  branch  proc  state
              local pane_r = ribbon.new("pane")
              pane_r:append(nil, colors.chrome, pbranch)
              -- badge: colored character name for cross-referencing
              local bc = pane_badge_color(rec.pane_id, colors)
              if bc then
                pane_r:append(nil, colors.chrome, "<")
                pane_r:append(nil, bc, pane_badge(rec.pane_id))
                pane_r:append(nil, colors.chrome, ">")
              end
              -- "at <path>": smart path with placeholder prefix ({gh}/{sy}/{home})
              local pane_dp = smart_path(rec.cwd)
              if pane_dp == "" then pane_dp = rec.repo end
              if pane_dp ~= "" then
                pane_r:append(nil, colors.chrome, "  ")
                pane_r:append(nil, colors.age, "at ")
                pane_r:append(nil, colors.name, pane_dp)
              end
              -- "on <branch>" (agent-active panes only, from state file)
              if rec.branch then
                pane_r:append(nil, colors.chrome, "  ")
                pane_r:append(nil, colors.age, "on ")
                pane_r:append(nil, colors.age, rec.branch)
                if rec.dirty then pane_r:append(nil, colors.working, " *") end
              end
              -- "in <proc>": sigil icon + name
              local proc = rec.title ~= "" and rec.title or nil
              if proc then
                pane_r:append(nil, colors.chrome, "  ")
                pane_r:append(nil, colors.age, "in ")
                if sigil_ok then
                  local proc_items = sigil.items(proc, { fallback = true, padding = "right", reset = true })
                  pane_r:append_items(proc_items)
                end
                pane_r:append(nil, colors.name, proc)
              end
              -- agent state: status icon + label + meaningful reason; age only when active
              if rec.status then
                local asc = status_color(rec.status, colors) or colors.idle
                local p_fmt = format_status_label(rec.status, rec.reason)
                pane_r:append(nil, colors.chrome, "  ")
                pane_r:append(nil, asc, agent_state_icons[rec.status] or "●")
                if p_fmt ~= "" then
                  pane_r:append(nil, colors.reason, " " .. p_fmt)
                end
                -- age only for non-idle states; idle age is noise
                if rec.status ~= "done" then
                  local age = rec.since and format_age(now - rec.since) or ""
                  if age ~= "" then pane_r:append(nil, colors.age, " " .. age) end
                end
              end
              add("pane:" .. rec.pane_id, pane_r:format(), rec)
            end
          end
      end

      return choices
    end

    -- Level-aware activation for a selected tree node. pane/attn/tab all resolve
    -- to activating an exact pane (a tab carries its active pane id), reusing
    -- activate_agent_pane. A live workspace switches; a dormant seshy session
    -- switches with its session dir as cwd (D7: the plugin exposes no public
    -- switch-with-restore, so pane-layout restore is intentionally not performed
    -- here). Header rows and since-closed targets no-op.
    local function session_tree_dispatch(win, pane, id, by_id)
      if not id then
        return
      end
      local rec = by_id[id]
      if type(rec) ~= "table" then
        return
      end
      local kind = id:match("^([^:]+):")
      if kind == "ws" and rec.dormant then
        switch_to_workspace(win, pane, rec.workspace, seshy_dir .. "/" .. rec.workspace)
      elseif kind == "ws" then
        switch_to_workspace(win, pane, rec.workspace)
      else
        activate_agent_pane(win, pane, rec)
      end
    end

    -- Navigation/filter keys inside the picker. WezTerm's InputSelector hosts no
    -- custom keys directly, but a key table activated *before* the selector is
    -- (the workspace-manager trick): each entry sets a pending filter, pops the
    -- table, and sends Enter to close the selector; the callback then reopens the
    -- tree scoped to that filter. Enter/Escape are included so the table is ALWAYS
    -- popped on close — otherwise it would leak into normal typing. Every entry
    -- is CTRL-modified: bare letters belong to InputSelector's own alphabet jump
    -- in default mode, and to the filter text once `/` puts it in fuzzy mode.
    local tree_state = { pending_filter = nil, pending_action = nil, current_filter = "all", key_table_active = false }
    local function tree_close_key(key)
      return {
        key = key,
        mods = "NONE",
        action = wezterm.action_callback(function(win, pane)
          tree_state.pending_filter = nil
          tree_state.key_table_active = false
          win:perform_action(wezterm.action.PopKeyTable, pane)
          win:perform_action(wezterm.action.SendKey({ key = key }), pane)
        end),
      }
    end
    config.key_tables = config.key_tables or {}
    config.key_tables.session_tree_actions = {
      tree_close_key("Enter"),
      tree_close_key("Escape"),
      -- Navigation is NOT bound here. InputSelector ships its own: Up/Down,
      -- Ctrl+N/Ctrl+P, Ctrl+J/Ctrl+K, and bare j/k whenever the overlay is not
      -- in fuzzy mode (its default `alphabet` omits j and k precisely so they
      -- can move). Binding them again only risked shadowing the real thing.
      --
      -- The `^]`/`^[` workspace cycle is gone too: Ctrl+[ IS Escape at the
      -- terminal level, so that binding could never fire without also cancelling
      -- the picker. SUPER+] / SUPER+[ already cycle workspaces from outside.
      {
        key = "d",
        mods = "CTRL",
        action = wezterm.action_callback(function(win, pane)
          tree_state.pending_filter = tree_state.current_filter == "dormant" and "all" or "dormant"
          tree_state.key_table_active = false
          win:perform_action(wezterm.action.PopKeyTable, pane)
          win:perform_action(wezterm.action.SendKey({ key = "Enter" }), pane)
        end),
      },
      {
        key = "x",
        mods = "CTRL",
        action = wezterm.action_callback(function(win, pane)
          tree_state.pending_action = "delete"
          tree_state.key_table_active = false
          win:perform_action(wezterm.action.PopKeyTable, pane)
          win:perform_action(wezterm.action.SendKey({ key = "Enter" }), pane)
        end),
      },
    }

    -- ^x close: resolve the highlighted row to its containing workspace and
    -- close that live session (kill its panes through the CLI — the Lua mux
    -- API exposes no workspace close). Any row kind works — ws/tab/pane recs
    -- all carry .workspace — so close acts on the session the cursor is inside,
    -- not only its header row. The seshy session on disk is untouched: a
    -- closed session simply shows as dormant afterwards. A session displayed in
    -- any window is refused — closing the panes under the user's feet. Returns a
    -- notice for the reopened picker's title: toasts need a code-signed binary
    -- on macOS, so the title is the only reliable feedback channel.
    local function close_session_target(id, by_id)
      local rec = by_id[id]
      if type(rec) ~= "table" or not rec.workspace then
        return "not a session row"
      end
      local name = rec.workspace
      if rec.dormant then
        return "already dormant: " .. name
      end
      -- Refuse any session that is on screen, not only this window's own. With
      -- more than one GUI window the target may be displayed elsewhere, and
      -- killing its panes would close that window under the user.
      if gui_window_for_workspace(name) then
        return "cannot close a visible session"
      end
      local wezterm_bin = (wezterm.executable_dir or "") .. "/wezterm"
      local ok, stdout = wezterm.run_child_process({ wezterm_bin, "cli", "list", "--format=json" })
      if not ok then
        wezterm.log_error("wezterm cli list failed; workspace " .. name .. " left open")
        return "close failed: " .. name
      end
      local killed = 0
      for _, p in ipairs(wezterm.json_parse(stdout) or {}) do
        if p.workspace == name then
          local kill_ok = wezterm.run_child_process({ wezterm_bin, "cli", "kill-pane", "--pane-id=" .. tostring(p.pane_id) })
          if kill_ok then
            killed = killed + 1
          end
        end
      end
      if killed == 0 then
        return "no panes found: " .. name
      end
      return "closed " .. name
    end

    -- Open the all-in-one session tree picker in fuzzy mode (type to filter,
    -- ^j/^k to navigate). ^d toggles dormant view; Esc closes.
    -- Recursive: ^d reopens in the toggled filter; `notice` is transient
    -- feedback from the previous action, shown in the title.
    local function open_session_tree(win, pane, filter, notice)
      filter = filter or "all"
      tree_state.current_filter = filter
      local tree = session_tree()
      -- Resolve palette once per open so all rows in this invocation share
      -- the same colors even if the picker is open across a scheme switch.
      local colors = tree_colors(win)
      local by_id = {}
      local choices = session_tree_choices(tree, by_id, filter, colors)
      if #choices == 0 then
        if filter and filter ~= "all" then
          filter, by_id = "all", {}
          choices = session_tree_choices(tree, by_id, "all", colors)
        end
        if #choices == 0 then
          return
        end
      end
      local title
      if filter == "dormant" then
        title = "Sessions  [dormant · ^d all · ^x close]"
      else
        title = "Sessions  [^d dormant · ^x close]"
      end
      if notice then
        title = title .. "  · " .. notice
      end
      tree_state.pending_filter = nil
      tree_state.key_table_active = true
      win:perform_action(
        wezterm.action.ActivateKeyTable({ name = "session_tree_actions", one_shot = false }),
        pane
      )
      win:perform_action(
        wezterm.action.InputSelector({
          title = title,
          choices = choices,
          -- Default (non-fuzzy) mode, deliberately. Starting in fuzzy mode sent
          -- every keystroke to the filter, which is why j/k did not navigate:
          -- they were filter text. In default mode InputSelector gives j/k and
          -- Ctrl+N/Ctrl+P for movement, 1-9 and its `alphabet` letters for
          -- direct row jumps, and `/` to enter fuzzy filtering when you want it.
          fuzzy = false,
          description = "  j/k nav  1-9 jump  / filter  ^d dormant  ^x close  Esc quit",
          fuzzy_description = "  filter (Esc to leave):  ",
          action = wezterm.action_callback(function(inner_win, inner_pane, id, _label)
            -- Guard: pop the key table if it wasn't already cleared by a close/filter/cycle
            -- key handler — e.g. picker was dismissed by clicking outside the window.
            if tree_state.key_table_active then
              tree_state.key_table_active = false
              inner_win:perform_action(wezterm.action.PopKeyTable, inner_pane)
            end
            local pa = tree_state.pending_action
            tree_state.pending_action = nil
            local pf = tree_state.pending_filter
            tree_state.pending_filter = nil
            if pa == "delete" and id then
              local notice = close_session_target(id, by_id)
              wezterm.time.call_after(0.15, function()
                open_session_tree(inner_win, inner_pane, tree_state.current_filter, notice)
              end)
              return
            end
            if pf then
              wezterm.time.call_after(0.05, function()
                open_session_tree(inner_win, inner_pane, pf)
              end)
              return
            end
            session_tree_dispatch(inner_win, inner_pane, id, by_id)
          end),
        }),
        pane
      )
    end

    wm.session_enabled = true
    -- Always launch (and relaunch after quit) into the "default" workspace
    -- rather than auto-restoring the most-recently-used session. With this
    -- false the plugin registers no gui-startup restore handler, so WezTerm's
    -- own startup honors config.default_workspace ("default") below. Sessions
    -- still save (session_enabled) and still restore when switched into via the
    -- switcher; only the startup auto-restore is suppressed.
    wm.session_restore_on_startup = false
    wm.session_state_dir = home .. "/.local/state/wezterm/workspace_state"
    wm.workspace_switcher_sort = "recency"

    -- apply_to_config appends its own leader bindings and an in-switcher
    -- key_table (config.key_tables.workspace_switcher_actions). We keep the
    -- key_table — it drives the switcher's own UI — but strip the four
    -- user-facing leader bindings it injects: we open the switcher from SUPER+s
    -- below, and CTRL+[ (= ESC) in particular would shadow vim. Remove by
    -- (key, mods) identity so the override is explicit and immune to any
    -- change in the plugin's append order. None of these combos are bound by
    -- our own keybindings.lua, so this only removes the plugin's.
    wm.apply_to_config(config)
    local wm_injected_keys = {
      { key = "s", mods = "LEADER" },
      { key = "S", mods = "LEADER" },
      { key = "]", mods = "CTRL" },
      { key = "[", mods = "CTRL" },
    }
    if config.keys then
      for _, injected in ipairs(wm_injected_keys) do
        for i = #config.keys, 1, -1 do
          local k = config.keys[i]
          if k.key == injected.key and k.mods == injected.mods then
            table.remove(config.keys, i)
          end
        end
      end
    end

    -- SUPER+s opens the all-in-one session tree (workspace → tab → pane → agent
    -- state; label-jump default, `/` to filter by `session/tab/agent`). Bound
    -- here (not keybindings.lua) because it needs this configured wm instance and
    -- the tree helpers in scope; mirrors the locked-mode passthrough the other
    -- smart keybinds use. ssh is SUPER+SHIFT+s (keybindings.lua). The plain
    -- workspace switcher stays reachable via the command palette below.
    config.keys = config.keys or {}
    table.insert(config.keys, {
      key = "s",
      mods = "SUPER",
      action = wezterm.action_callback(function(win, pane)
        if keybindings.locked_mode then
          win:perform_action({ SendKey = { key = "s", mods = "SUPER" } }, pane)
          return
        end
        open_session_tree(win, pane)
      end),
    })
    -- SUPER+] / SUPER+[ cycle workspaces (next/prev) without opening the tree,
    -- mirroring nvim's buffer-cycle convention.
    table.insert(config.keys, {
      key = "]",
      mods = "SUPER",
      action = wezterm.action_callback(function(win, pane)
        if keybindings.locked_mode then
          win:perform_action({ SendKey = { key = "]", mods = "SUPER" } }, pane)
          return
        end
        win:perform_action(wezterm.action.SwitchWorkspaceRelative(1), pane)
      end),
    })
    table.insert(config.keys, {
      key = "[",
      mods = "SUPER",
      action = wezterm.action_callback(function(win, pane)
        if keybindings.locked_mode then
          win:perform_action({ SendKey = { key = "[", mods = "SUPER" } }, pane)
          return
        end
        win:perform_action(wezterm.action.SwitchWorkspaceRelative(-1), pane)
      end),
    })

    -- Command palette (reachable via SUPER+: / SUPER+; / CTRL+;): the tree, the
    -- plain workspace switcher, and previous-workspace.
    wezterm.on("augment-command-palette", function(_window, _pane)
      return {
        {
          brief = "Session tree",
          action = wezterm.action_callback(function(win, pane)
            open_session_tree(win, pane)
          end),
        },
        {
          brief = "Switch seshy session / workspace",
          action = wm.workspace_switcher(),
        },
        {
          brief = "Switch to previous workspace",
          action = wm.switch_to_previous_workspace(),
        },
      }
    end)
  end

  -- Agent navigation is now entirely SUPER+s (the session tree). The former
  -- SUPER+g express jump and SUPER+SHIFT+g blocked-pane picker are retired — the
  -- tree's needs-attention zone (worst on top) and pane nodes subsume both.
  -- `CTRL+g` (locked-mode toggle) is unaffected.
end

return M
