-- The clipboard history. Held in memory only and never written to disk, because what
-- passes through a clipboard includes passwords, and a file of them outliving the session
-- is a worse trade than losing the history on a reload.
local M = {}

-- How far back the history reaches. Enough to find what was copied a few minutes ago,
-- short enough that the list stays readable.
local depth = 60

-- The width a row shows. A copied paragraph is identified by its opening, not its whole.
local preview = 90

-- The pasteboard types a password manager marks its copies with. An entry carrying one is
-- never recorded, so a password does not end up in a list bound to cmd+space.
local concealed = {
  ["org.nspasteboard.ConcealedType"] = true,
  ["org.nspasteboard.TransientType"] = true,
  ["org.nspasteboard.AutoGeneratedType"] = true,
}

local history = {}
local watcher = nil

--- Whether the pasteboard is marked as holding something that must not be recorded.
---@return boolean
local function is_concealed()
  local ok, types = pcall(hs.pasteboard.contentTypes)
  if not ok or type(types) ~= "table" then
    return false
  end
  for _, kind in ipairs(types) do
    if concealed[kind] then
      return true
    end
  end
  return false
end

--- One line, with the whitespace collapsed, so a copied block reads as a row rather than
--- pushing the rest of the list off the panel.
---@param text string
---@return string
local function oneline(text)
  local flat = text:gsub("%s+", " "):gsub("^%s+", ""):gsub("%s+$", "")
  if #flat <= preview then
    return flat
  end
  return flat:sub(1, preview) .. "…"
end

--- Record what is on the pasteboard now, unless it is concealed, empty, or already on top.
local function record()
  if is_concealed() then
    return
  end
  local ok, text = pcall(hs.pasteboard.readString)
  if not ok or type(text) ~= "string" then
    return
  end
  local flat = oneline(text)
  if flat == "" then
    return
  end
  if history[1] and history[1].text == text then
    return
  end
  -- Moved to the front rather than added again, so copying the same thing twice leaves one
  -- row where it belongs instead of two.
  for index, entry in ipairs(history) do
    if entry.text == text then
      table.remove(history, index)
      break
    end
  end
  table.insert(history, 1, { text = text, label = flat, at = os.time() })
  while #history > depth do
    table.remove(history)
  end
end

--- Start watching. Idempotent: a second call replaces the watcher rather than adding one.
function M.start()
  if watcher then
    watcher:stop()
  end
  watcher = hs.pasteboard.watcher.new(function()
    record()
  end)
  if watcher then
    watcher:start()
  end
  -- Whatever is already on the pasteboard, so the first open is not an empty section.
  record()
end

--- The history as launcher rows, newest first.
---@return table[]
function M.rows()
  local rows = {}
  for _, entry in ipairs(history) do
    rows[#rows + 1] = {
      text = entry.label,
      detail = "",
      label = "Clipboard",
      badge = "C",
      kind = "clipboard",
      entry = entry,
      at = entry.at,
    }
  end
  return rows
end

--- Put one entry back on the pasteboard, which is the whole of what choosing it means.
---@param entry table|nil
function M.restore(entry)
  if entry == nil or entry.text == nil then
    return
  end
  hs.pasteboard.setContents(entry.text)
end

return M
