local M = {}

local depth = 60

local preview = 90

local concealed = {
  ["org.nspasteboard.ConcealedType"] = true,
  ["org.nspasteboard.TransientType"] = true,
  ["org.nspasteboard.AutoGeneratedType"] = true,
}

local history = {}
local watcher = nil

---@return boolean
local function is_concealed()
  local ok, types = pcall(hs.pasteboard.contentTypes)
  if not ok or type(types) ~= "table" then
    return false
  end
  for _, kind in ipairs(types) do
    if concealed[kind] then
      return true
    end
  end
  return false
end

---@param text string
---@return string
local function oneline(text)
  local flat = text:gsub("%s+", " "):gsub("^%s+", ""):gsub("%s+$", "")
  if #flat <= preview then
    return flat
  end
  return flat:sub(1, preview) .. "…"
end

local function record()
  if is_concealed() then
    return
  end
  local ok, text = pcall(hs.pasteboard.readString)
  if not ok or type(text) ~= "string" then
    return
  end
  local flat = oneline(text)
  if flat == "" then
    return
  end
  if history[1] and history[1].text == text then
    return
  end
  for index, entry in ipairs(history) do
    if entry.text == text then
      table.remove(history, index)
      break
    end
  end
  table.insert(history, 1, { text = text, label = flat, at = os.time() })
  while #history > depth do
    table.remove(history)
  end
end

function M.start()
  if watcher then
    watcher:stop()
  end
  watcher = hs.pasteboard.watcher.new(function()
    record()
  end)
  if watcher then
    watcher:start()
  end
  record()
end

---@return number
function M.depth()
  return #history
end

---@return table[]
function M.rows()
  local rows = {}
  for index, entry in ipairs(history) do
    rows[#rows + 1] = {
      text = entry.label,
      detail = os.date("%H:%M", entry.at),
      label = string.format("%d", index),
      glyph = "clipboard",
      kind = "clip-entry",
      entry = entry,
      at = entry.at,
    }
  end
  return rows
end

---@param entry table|nil
function M.restore(entry)
  if entry == nil or entry.text == nil then
    return
  end
  hs.pasteboard.setContents(entry.text)
end

return M
