cpu: 4
memory: 8
disk: 100
arch: aarch64
runtime: docker

vmType: vz
rosetta: true
mountType: sshfs
mountInotify: true

network:
  address: true
  dns: 
    - "1.1.1.1"
    - "1.0.0.1"

docker:
  insecure-registries:
    - "xpkg.crossplane.io"
    - "artifactory.nike.com:9001"
  buildkit: true
  features:
    buildkit: true

forwardAgent: false

mounts:
  - location: /tmp/colima
    writable: true
  - location: /etc/ssl/certs
    writable: true