local M = {}

M.plugins = {
	{
		"rose-pine/neovim",
		name = "rose-pine",
		config = function()
			require("rose-pine").setup({
				variant = "main",
				styles = {
					transparency = true,
				},
				palette = {
					main = {
						base = "#1a1b26",
						surface = "#201f2e",
						overlay = "#2c2b3a",
						muted = "#6e6b8c",
						subtle = "#9a97bb",
						text = "#e2e0f7",
						love = "#ce7b84",
						gold = "#d7b786",
						rose = "#d9a9b3",
						pine = "#6d889f",
						foam = "#8ebbc1",
						iris = "#a198c8",
						leaf = "#85a89f",
						highlight_low = "#23222f",
						highlight_med = "#3c3b52",
						highlight_high = "#4c4a67",
					},
				},
				highlight_groups = {
					DiagnosticError = { fg = "#e2738a" },
					DiagnosticWarn = { fg = "#d7b786" },
					DiagnosticInfo = { fg = "#6a9fb5" },
					DiagnosticHint = { fg = "#b4a7e7" },
					DiagnosticVirtualTextError = { fg = "#e2738a" },
					DiagnosticVirtualTextWarn = { fg = "#d7b786" },
					DiagnosticVirtualTextInfo = { fg = "#6a9fb5" },
					DiagnosticVirtualTextHint = { fg = "#b4a7e7" },
					DiagnosticUnderlineError = { undercurl = true, sp = "#e2738a" },
					DiagnosticUnderlineWarn = { undercurl = true, sp = "#d7b786" },
					DiagnosticUnderlineInfo = { undercurl = true, sp = "#6a9fb5" },
					DiagnosticUnderlineHint = { undercurl = true, sp = "#b4a7e7" },
					DiagnosticSignError = { fg = "#e2738a" },
					DiagnosticSignWarn = { fg = "#d7b786" },
					DiagnosticSignInfo = { fg = "#6a9fb5" },
					DiagnosticSignHint = { fg = "#b4a7e7" },
					["@lsp.type.function"] = { fg = "#a3dbe1" },
					["@lsp.type.method"] = { fg = "#a3dbe1" },
					["@lsp.type.variable"] = { fg = "text" },
					["@lsp.type.parameter"] = { fg = "subtle" },
					["@lsp.type.property"] = { fg = "rose" },
					["@lsp.type.enumMember"] = { fg = "#6a9fb5" },
					["@lsp.type.class"] = { fg = "#d7b786" },
					["@lsp.type.struct"] = { fg = "#d7b786" },
					["@lsp.type.interface"] = { fg = "#d7b786" },
					["@lsp.type.enum"] = { fg = "#d7b786" },
					["@lsp.type.typeParameter"] = { fg = "#b4a7e7" },
					["@lsp.type.keyword"] = { fg = "pine" },
					["@lsp.type.string"] = { fg = "#a5bdb6" },
					["@lsp.type.number"] = { fg = "#e0bfc0" },
					["@lsp.type.operator"] = { fg = "pine" },
					["@lsp.type.comment"] = { fg = "muted", italic = true },
					SnacksNotifierError = { fg = "#e2738a", bg = "surface" },
					SnacksNotifierWarn = { fg = "#d7b786", bg = "surface" },
					SnacksNotifierInfo = { fg = "#6a9fb5", bg = "surface" },
					SnacksNotifierDebug = { fg = "#b4a7e7", bg = "surface" },
					SnacksNotifierTrace = { fg = "subtle", bg = "surface" },
					SnacksNotifierIconError = { fg = "#e2738a" },
					SnacksNotifierIconWarn = { fg = "#d7b786" },
					SnacksNotifierIconInfo = { fg = "#6a9fb5" },
					SnacksNotifierIconDebug = { fg = "#b4a7e7" },
					SnacksNotifierIconTrace = { fg = "subtle" },
					SnacksNotifierTitleError = { fg = "#e2738a" },
					SnacksNotifierTitleWarn = { fg = "#d7b786" },
					SnacksNotifierTitleInfo = { fg = "#6a9fb5" },
					SnacksNotifierTitleDebug = { fg = "#b4a7e7" },
					SnacksNotifierTitleTrace = { fg = "subtle" },
					SnacksNotifierBorderError = { fg = "#e2738a" },
					SnacksNotifierBorderWarn = { fg = "#d7b786" },
					SnacksNotifierBorderInfo = { fg = "#6a9fb5" },
					SnacksNotifierBorderDebug = { fg = "#b4a7e7" },
					SnacksNotifierBorderTrace = { fg = "subtle" },
					CurSearch = {
						fg = "base",
						bg = "leaf",
						inherit = false,
					},
					NormalOpaque = {
						fg = "subtle",
						bg = "overlay",
					},
					NormalNCOpaque = {
						fg = "subtle",
						bg = "overlay",
					},
					Search = {
						fg = "text",
						bg = "leaf",
						blend = 20,
						inherit = false,
					},
					TelescopeBorder = {
						fg = "#3a3a52",
						bg = "#2d2b3b",
					},
					TelescopeNormal = {
						fg = "#e0def4",
						bg = "#2d2b3b",
					},
					TelescopeSelection = {
						fg = "text",
						bg = "#3e3c54",
					},
					TelescopeSelectionCaret = {
						fg = "love",
						bg = "#3e3c54",
					},
					TelescopeMultiSelection = {
						fg = "text",
						bg = "#4d4a64",
					},
					TelescopeTitle = {
						fg = "base",
						bg = "love",
					},
					TelescopePromptTitle = {
						fg = "base",
						bg = "pine",
					},
					TelescopePreviewTitle = {
						fg = "base",
						bg = "iris",
					},
					TelescopePromptNormal = {
						fg = "text",
						bg = "#242234",
					},
					TelescopePromptBorder = {
						fg = "#242234",
						bg = "#242234",
					},
					WinBar = { fg = "text", bg = "NONE" },
					WinBarNC = { fg = "subtle", bg = "NONE" },
					DropBarCurrentContext = { fg = "text", bg = "NONE" },
					DropBarHover = { fg = "text", bg = "highlight_low" },
					DropBarIconKindDefault = { fg = "subtle", bg = "NONE" },
					DropBarMenuNormalFloat = { fg = "text", bg = "overlay" },
					DropBarMenuFloatBorder = { fg = "muted", bg = "overlay" },
					DropBarMenuCurrentContext = { fg = "text", bg = "highlight_med" },
					DropBarMenuHoverEntry = { fg = "text", bg = "highlight_high" },
				},
			})
			vim.cmd("colorscheme rose-pine")
		end,
	},
}

return M

