package cmd

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/roshbhatia/seshy/internal/config"
	"github.com/roshbhatia/seshy/internal/ui"
	"github.com/spf13/cobra"
)

var configInitCmd = &cobra.Command{
	Use:   "init",
	Short: "Scaffold config directory with defaults",
	RunE: func(cmd *cobra.Command, args []string) error {
		cfgDir := config.ConfigDir()

		// Create dirs
		dirs := []string{
			cfgDir,
			filepath.Join(cfgDir, "templates", "repo"),
			filepath.Join(cfgDir, "templates", "session"),
			filepath.Join(cfgDir, "hooks"),
		}
		for _, d := range dirs {
			if err := os.MkdirAll(d, 0755); err != nil {
				return fmt.Errorf("creating %s: %w", d, err)
			}
		}

		// Write config.yaml if missing
		cfgPath := config.ConfigPath()
		if _, err := os.Stat(cfgPath); os.IsNotExist(err) {
			content := `# seshy configuration
# See: https://github.com/roshbhatia/seshy

# Branch naming template (Go template)
# Variables: .Session, .Repo, .User
branchFormat: "sy/{{.Session}}/{{.Repo}}"

# Sessions storage directory (default: $XDG_STATE_HOME/seshy/sessions)
sessionsDir: ""

# External tool commands
repoSource: "zoxide query --list"
picker: "fzf --multi --height=40% --reverse --prompt='repo > '"
sessionPicker: "fzf --height=40% --reverse --prompt='session > '"

# Repos always included in picker
defaultRepos: []

# Lifecycle hooks (Go-template-rendered, then sh -c executed)
# cwd = session path, SESHY_* env vars set
hooks:
  postCreate: []
  postAdd: []
  preDelete: []
`
			if err := os.WriteFile(cfgPath, []byte(content), 0644); err != nil {
				return fmt.Errorf("writing config: %w", err)
			}
			fmt.Fprintln(os.Stderr, ui.Successf("Created %s", cfgPath))
		} else {
			fmt.Fprintln(os.Stderr, ui.Info("Config already exists: "+cfgPath))
		}

		// Write example repo template if missing
		envrcPath := filepath.Join(cfgDir, "templates", "repo", ".envrc.tmpl")
		if _, err := os.Stat(envrcPath); os.IsNotExist(err) {
			content := `# Generated by seshy for {{.Session}}/{{.Repo}}
# source_up
export SERVICE_NAME={{.Repo}}
export SESSION_ROOT={{.SessionPath}}
`
			if err := os.WriteFile(envrcPath, []byte(content), 0644); err != nil {
				return fmt.Errorf("writing example template: %w", err)
			}
			fmt.Fprintln(os.Stderr, ui.Successf("Created example template: %s", envrcPath))
		}

		fmt.Fprintln(os.Stderr, ui.Info("Config directory: "+cfgDir))
		return nil
	},
}

func init() {
	configCmd.AddCommand(configInitCmd)
}
