package cmd

import (
	"fmt"

	"github.com/spf13/cobra"
)

var initCmd = &cobra.Command{
	Use:   "init <shell>",
	Short: "Print shell integration code",
	Long: `Print shell integration code for your shell.

Add to your shell config:
  eval "$(sy init zsh)"   # zsh
  eval "$(sy init bash)"  # bash
  sy init fish | source   # fish

With shell integration active, "sy <name>" will cd into the session directory
using greedy matching. All other sy subcommands pass through unchanged.`,
	Args:      cobra.ExactArgs(1),
	ValidArgs: []string{"zsh", "bash", "fish"},
	RunE: func(cmd *cobra.Command, args []string) error {
		switch args[0] {
		case "zsh":
			fmt.Print(zshIntegration)
		case "bash":
			fmt.Print(bashIntegration)
		case "fish":
			fmt.Print(fishIntegration)
		default:
			return fmt.Errorf("unsupported shell %q — supported: zsh, bash, fish", args[0])
		}
		return nil
	},
}

// zshIntegration wraps sy so that "sy <name>" cds into the matched session.
// Subcommands (new, add, delete, list, …) and flags pass through unchanged.
const zshIntegration = `# seshy shell integration — generated by sy init zsh
function sy() {
  local _p
  if [[ $# -eq 1 ]] && [[ "${1}" != -* ]] && _p=$(command sy --greedy "${1}" 2>/dev/null) && [[ -n "${_p}" ]]; then
    cd "${_p}"
  else
    command sy "$@"
  fi
}
`

const bashIntegration = `# seshy shell integration — generated by sy init bash
sy() {
  local _p
  if [[ $# -eq 1 ]] && [[ "${1}" != -* ]] && _p=$(command sy --greedy "${1}" 2>/dev/null) && [[ -n "${_p}" ]]; then
    cd "${_p}"
  else
    command sy "$@"
  fi
}
`

const fishIntegration = `# seshy shell integration — generated by sy init fish
function sy
  if test (count $argv) -eq 1; and not string match -q -- '-*' $argv[1]
    set -l _p (command sy --greedy $argv[1] 2>/dev/null)
    if test -n "$_p"
      cd $_p
      return
    end
  end
  command sy $argv
end
`

func init() {
	rootCmd.AddCommand(initCmd)
}
