---
tasks:
  default:
    cmds:
      - task -l
    desc: Show help information
    silent: true

  nvim:run-local-clean:
    cmds:
      - |
        rm -rf "/tmp/nvim-run-local-isolated"
    desc: Clean local Neovim test environment
    silent: true

  nvim:run-local-headless-isolated:
    cmds:
      - |
        NVIM_TMP_DIR="/tmp/nvim-$(date +%s)"
        NVIM_DATA_DIR="/tmp/nvim-run-local-isolated"

        # Create directories
        mkdir -p "$NVIM_TMP_DIR" "$NVIM_DATA_DIR/share" "$NVIM_DATA_DIR/state" "$NVIM_DATA_DIR/cache"

        # Copy config to temporary directory
        cp -r * "$NVIM_TMP_DIR/"

        # Run Neovim headless with the copied config
        XDG_DATA_HOME="$NVIM_DATA_DIR/share" \
        XDG_STATE_HOME="$NVIM_DATA_DIR/state" \
        XDG_CACHE_HOME="$NVIM_DATA_DIR/cache" \
        nvim \
          --cmd "let g:auto_session_enabled = v:false" \
          --cmd "set runtimepath^=$NVIM_TMP_DIR,$NVIM_TMP_DIR/lua" \
          -u "$NVIM_TMP_DIR/init.lua" --headless

        # Clean up tmp directory
        rm -rf "$NVIM_TMP_DIR"
    desc: Run Neovim with local configuration in temporary directory (headless)
    silent: true

  nvim:run-local-isolated:
    cmds:
      - |
        NVIM_TMP_DIR="/tmp/nvim-$(date +%s)"
        NVIM_DATA_DIR="/tmp/nvim-run-local-isolated"

        # Create directories
        mkdir -p "$NVIM_TMP_DIR" "$NVIM_DATA_DIR/share" "$NVIM_DATA_DIR/state" "$NVIM_DATA_DIR/cache"

        # Copy config to temporary directory
        cp -r * "$NVIM_TMP_DIR/"

        # Run Neovim with the copied config
        # Run Neovim headless with the copied config
        # Run Neovim with the copied config
        XDG_DATA_HOME="$NVIM_DATA_DIR/share" \
        XDG_STATE_HOME="$NVIM_DATA_DIR/state" \
        XDG_CACHE_HOME="$NVIM_DATA_DIR/cache" \
        nvim \
          --cmd "let g:auto_session_enabled = v:false" \
          --cmd "set runtimepath^=$NVIM_TMP_DIR,$NVIM_TMP_DIR/lua" \
          -u "$NVIM_TMP_DIR/init.lua"

        # Clean up tmp directory
        rm -rf "$NVIM_TMP_DIR"
    desc: Run Neovim with local configuration in temporary directory
    silent: true

version: '3'
