# Show a palette bar at the top of the output
show_palette = false

# Prefer to use the preferred_theme if it exists, otherwise,
# it'll fall back to the theme that gets set in 'theme = "..."' below.
# This is useful for automatically using themes (such as everforest-dark
# and everforest-light) based on your currently-active theme.
# The line below tries to get the preferred theme from the theme_getter.rhai script, and if
# that fails, just returns the "rosh" theme.
use_preferred_theme = false
preferred_theme = "rosh"

# Sets the theme that macchina uses
theme = "rosh"

# Displays the palette bar in true or ASCII colors
true_color = true

# Displays the bar with ASCII colors instead of Unicode characters
# Set this to true if Unicode is not supported in your shell
ascii = false

# Displays only the specified readouts
# This overrides the skip_* options
show = [
    "Host",
    "Machine",
    "Kernel",
    "Shell",
    "Terminal",
    "Distro",
    "Uptime",
    "Memory",
    "OS",
]

# Skips the specified readouts
# This can be overridden by the show option
#skip = ["Locale", "LocalIP"]

# Configure how memory is displayed
# Possible options are:
# Mebibyte, MiB
# Megabyte, MB
# Gibibyte, GiB
# Gigabyte, GB
mem_used_format = "MiB"
mem_total_format = "GiB"

# Themes need to be placed in "$XDG_CONFIG_HOME/macchina/themes" beforehand.
# e.g.: "~/.config/macchina/themes/rosh.toml"
# will be interpreted as "theme = rosh"