#!/bin/zsh
# shellcheck disable=all
REPO_BASE=~/github

list_repos() {
    repos=$(find "$REPO_BASE" -mindepth 2 -maxdepth 2 -type d ! -name ".*" | sort)
    selected_repo=$(echo "$repos" | while read -r repo; do
        org=$(basename "$(dirname "$repo")")
        name=$(basename "$repo")
        echo -e "$name ($org)"
    done | fzf --ansi --height=20)

    if [[ -n "$selected_repo" ]]; then
        repo_name=$(echo "$selected_repo" | awk '{print $1}')
        change_dir "$repo_name"
    fi
}

change_dir() {
    target_repo=$1
    repos=$(find "$REPO_BASE" -mindepth 2 -maxdepth 2 -type d -name "$target_repo" ! -name ".*")
    target_path=$(echo "$repos" | head -n 1)
    if [[ -d "$target_path" ]]; then
        pushd "$target_path" || return
        echo "Changed directory to $target_path"
    else
        echo "Repository $target_repo not found."
    fi
}

show_help() {
    echo "Usage: crepo {list|l|d|cd|h|help} [REPO_NAME]"
    echo
    echo "Commands:"
    echo "  list, l          List all repositories and their organizations"
    echo "  d, cd [REPO_NAME] Change directory to the specified repository"
    echo "  h, help          Show this help message"
}

crepo() {
    case "$1" in
        list|l)
            list_repos
            ;;
        d|cd)
            if [[ -z "$2" ]]; then
                echo "Please provide a repository name."
            else
                change_dir "$2"
            fi
            ;;
        h|help)
            show_help
            ;;
        *)
            show_help
            ;;
    esac
}