hide_ascii      = false
spacing         = 1
padding         = 0
separator       = ""
key_color       = "#5277C3"  # NixOS blue
separator_color = "#7EBAE4"  # NixOS light blue

[bar]
glyph           = " "
symbol_open     = "("
symbol_close    = ")"
hide_delimiters = false
visible         = false

[box]
title           = "nix"
border          = "rounded"
visible         = true

[box.inner_margin]
x               = 2
y               = 1

[custom_ascii]
color           = "#5277C3"  # NixOS blue
path            = "~/.config/macchina/themes/nix.ascii"

[randomize]
key_color       = false
separator_color = false

[palette]
visible         = false

[keys]
host            = " host"
kernel          = "󰌽 kernel"
shell           = " shell"
packages        = " packages"
machine         = "󰇅 machine"