hide_ascii      = false
spacing         = 1
padding         = 0
separator       = ""
key_color       = "LightCyan"
separator_color = "Yellow"

[bar]
glyph           = " "
symbol_open     = "("
symbol_close    = ")"
hide_delimiters = false
visible         = false

[box]
title           = "rosh"
border          = "rounded"
visible         = true

[box.inner_margin]
x               = 2
y               = 1

[custom_ascii]
color           = "#BB90B7"
path            = "~/.config/macchina/themes/rosh.ascii"

[randomize]
key_color       = false
separator_color = false

[palette]
visible         = false

[keys]
host            = " host"
kernel          = "󰌽 kernel"
shell           = " shell"
packages        = " packages"
machine         = "󰇅 machine"