format = """
[](#2D1F3D)\
$os\
$username\
[](bg:#45315D fg:#2D1F3D)\
$directory\
[](fg:#45315D bg:#8C4351)\
$git_branch\
$git_status\
[](fg:#8C4351 bg:#5C2751)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:#5C2751 bg:#372549)\
$docker_context\
[](fg:#372549 bg:#1F1B3D)\
$time\
[ ](fg:#1F1B3D)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#2D1F3D"
style_root = "bg:#2D1F3D"
format = '[$user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#2D1F3D"
disabled = true # Disabled by default

[directory]
style = "bg:#45315D"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[c]
symbol = " "
style = "bg:#5C2751"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#372549"
format = '[ $symbol $context ]($style)'

[elixir]
symbol = " "
style = "bg:#5C2751"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#5C2751"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#8C4351"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#8C4351"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#5C2751"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:#5C2751"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#5C2751"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#5C2751"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#5C2751"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#5C2751"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:#5C2751"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#5C2751"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#5C2751"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1F1B3D"
format = '[ ♥ $time ]($style)'