format = """
[](#090300)\
$os\
$username\
[](bg:#a16a94 fg:#090300)\
$directory\
[](fg:#a16a94 bg:#db2d20)\
$git_branch\
$git_status\
[](fg:#db2d20 bg:#01a0e4)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:#01a0e4 bg:#01a252)\
$docker_context\
[](fg:#01a252 bg:#fded02)\
$time\
[ ](fg:#fded02)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#090300"
style_root = "bg:#090300"
format = '[$user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#090300"
disabled = true # Disabled by default

[directory]
style = "bg:#a16a94"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[c]
symbol = " "
style = "bg:#01a0e4"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#01a252"
format = '[ $symbol $context ]($style)'

[elixir]
symbol = " "
style = "bg:#01a0e4"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#01a0e4"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#db2d20"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#db2d20"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#01a0e4"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:#01a0e4"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#01a0e4"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#01a0e4"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#01a0e4"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#01a0e4"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:#01a0e4"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#01a0e4"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#01a0e4"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#fded02"
format = '[ ♥ $time ]($style)'