import { spawnSync } from "node:child_process";
import { cpSync, existsSync, mkdirSync, readdirSync, readFileSync, rmSync, statSync, writeFileSync } from "node:fs";
import { basename, join, resolve } from "node:path";

interface BuiltinCopy {
	label: string;
	destinationName: string;
	sourceDir: string;
}

const packageRoot = resolve(import.meta.dir, "..");
const distDir = join(packageRoot, "dist");
const distBuiltinDir = join(distDir, "builtin");
const distIndexDts = join(distDir, "index.d.ts");
const packagesRoot = resolve(packageRoot, "..");

// Issue #1208: the @bastani/atomic/workflows types condition must resolve to
// EMITTED declarations, never to the raw .ts that copyFilteredDirectory drops in
// dist. Verified empirically: under NodeNext, tsc resolves a `.js` specifier to a
// sibling `.ts` in preference to a sibling `.d.ts`, so a raw authoring `.ts` next
// to the emitted `.d.ts` would leak the SDK's internal type errors into every
// consumer (skipLibCheck only suppresses `.d.ts`). We therefore emit the lean
// authoring surface as `.d.ts` and prune the raw `.ts` copies below.
const workflowsDistDir = join(distBuiltinDir, "workflows");
const workflowsAuthoringTsconfig = join(packageRoot, "tsconfig.workflows-types.json");
const workflowsAmbientDts = join(workflowsDistDir, "ambient.d.ts");
const workflowsAmbientReference = '/// <reference path="./builtin/workflows/ambient.d.ts" />';
// Raw authoring-surface sources that are type-only at runtime (all importers use
// `import type`), so deleting their `.ts` copies is behaviorally inert; only the
// emitted `.d.ts` siblings remain for `tsc` resolution.
const rawAuthoringSourcesToPrune = [
	join(workflowsDistDir, "src", "authoring.ts"),
	join(workflowsDistDir, "src", "shared", "authoring-contract.ts"),
];
const ambientHeader = `// AUTO-GENERATED by scripts/copy-builtin-packages.ts (issue #1208). Do not edit by hand.
//
// Ambient bridge so the documented bare specifier \`@bastani/workflows\` (and its
// \`builtin/*\` submodules) type-check in installed packages that depend only on
// @bastani/atomic. Runtime resolution is unchanged: Atomic's jiti virtual-module
// loader still supplies the real SDK when workflow files load; these declarations
// only affect \`tsc\`. Each module is declared in exactly one file to avoid
// TS2666 / duplicate-identifier errors.`;

// Host-provided module specifiers that the extension loader resolves to live
// in-process instances (jiti alias / virtualModules); they must stay external
// so the bundled extension shares state with the host.
const HOST_PROVIDED_EXTERNALS = [
	"@bastani/atomic",
	"@bastani/atomic/*",
	"@earendil-works/*",
	"@mariozechner/*",
	"typebox",
	"typebox/*",
	"@sinclair/typebox",
	"@sinclair/typebox/*",
];

const WORKSPACE_BUILTINS = [
	{ packageName: "@bastani/workflows", workspaceDirName: "workflows" },
	{ packageName: "@bastani/subagents", workspaceDirName: "subagents" },
	{ packageName: "@bastani/mcp", workspaceDirName: "mcp" },
	{ packageName: "@bastani/web-access", workspaceDirName: "web-access" },
	{ packageName: "@bastani/intercom", workspaceDirName: "intercom" },
] as const;

function readPackageName(packageDir: string): string | undefined {
	try {
		const pkg = JSON.parse(readFileSync(join(packageDir, "package.json"), "utf-8")) as { name?: string };
		return pkg.name;
	} catch {
		return undefined;
	}
}

function assertPackageDir(packageDir: string, expectedName: string): void {
	const actualName = readPackageName(packageDir);
	if (actualName !== expectedName) {
		throw new Error(`Expected ${packageDir} to contain package ${expectedName}, found ${actualName ?? "none"}`);
	}
}

function shouldSkipEntry(name: string): boolean {
	return (
		name === "node_modules" ||
		name === ".git" ||
		name === ".github" ||
		name === "coverage" ||
		name === ".nyc_output" ||
		name === ".DS_Store" ||
		name === ".turbo" ||
		name === ".vite" ||
		name === ".vitest" ||
		name === "test" ||
		name === "tests" ||
		name.endsWith(".test.ts") ||
		name.endsWith(".test.mjs") ||
		name.endsWith(".spec.ts") ||
		name.endsWith(".map")
	);
}

function copyFilteredDirectory(sourceDir: string, destinationDir: string): void {
	mkdirSync(destinationDir, { recursive: true });
	for (const entry of readdirSync(sourceDir)) {
		if (shouldSkipEntry(entry)) {
			continue;
		}

		const sourcePath = join(sourceDir, entry);
		const destinationPath = join(destinationDir, entry);
		const stats = statSync(sourcePath);
		if (stats.isDirectory()) {
			copyFilteredDirectory(sourcePath, destinationPath);
			continue;
		}
		if (stats.isFile()) {
			cpSync(sourcePath, destinationPath, { force: true, preserveTimestamps: true });
		}
	}
}

function getCopyPlan(): BuiltinCopy[] {
	return WORKSPACE_BUILTINS.map(({ packageName, workspaceDirName }) => {
		const sourceDir = resolve(packagesRoot, workspaceDirName);
		if (!existsSync(sourceDir)) {
			throw new Error(`Workspace package directory not found: ${sourceDir}`);
		}
		assertPackageDir(sourceDir, packageName);
		return {
			label: packageName,
			destinationName: workspaceDirName,
			sourceDir,
		};
	});
}

function listWorkflowBuiltinNames(): string[] {
	const builtinDir = join(workflowsDistDir, "builtin");
	return readdirSync(builtinDir)
		.filter((name) => name.endsWith(".d.ts") && name !== "index.d.ts")
		.map((name) => name.slice(0, -".d.ts".length))
		.sort();
}

// Emit the lean @bastani/workflows authoring surface (authoring.ts +
// shared/authoring-contract.ts) as declarations into the copied workflows tree so
// the @bastani/atomic/workflows exports `types` condition resolves to `.d.ts`.
function emitWorkflowAuthoringTypes(): void {
	const result = spawnSync("bunx", ["tsgo", "-p", workflowsAuthoringTsconfig], {
		cwd: packageRoot,
		stdio: "inherit",
	});
	if (result.status !== 0) {
		throw new Error(`Failed to emit @bastani/workflows authoring declarations (tsgo exited ${result.status ?? "null"})`);
	}
	const emitted = join(workflowsDistDir, "src", "authoring.d.ts");
	if (!existsSync(emitted)) {
		throw new Error(`Expected emitted authoring declaration at ${emitted}`);
	}
	console.log(`Emitted @bastani/workflows authoring types -> ${join("dist", "builtin", "workflows", "src", "authoring.d.ts")}`);
}

// Remove the raw `.ts` copies of the emitted authoring surface so `tsc` cannot
// resolve a consumer's `.js` import to the leaky raw source instead of the `.d.ts`.
function pruneRawWorkflowAuthoringSources(): void {
	for (const file of rawAuthoringSourcesToPrune) {
		rmSync(file, { force: true });
	}
}

// Generate the single ambient bridge `.d.ts` that maps the documented bare
// specifier `@bastani/workflows` (and its `builtin/*` submodules) onto the
// @bastani/atomic subpath exports. Builtin names are derived from the copied
// builtin declarations so the bridge stays drift-free as builtins change.
function writeWorkflowsAmbientDeclaration(): void {
	const builtinBlocks = listWorkflowBuiltinNames()
		.map(
			(name) =>
				`declare module "@bastani/workflows/builtin/${name}" {\n` +
				`\texport * from "@bastani/atomic/workflows/builtin/${name}";\n` +
				`\texport { default } from "@bastani/atomic/workflows/builtin/${name}";\n` +
				`}`,
		)
		.join("\n\n");
	const contents =
		`${ambientHeader}\n\n` +
		`declare module "@bastani/workflows" {\n\texport * from "@bastani/atomic/workflows";\n}\n\n` +
		`declare module "@bastani/workflows/builtin" {\n\texport * from "@bastani/atomic/workflows/builtin";\n}\n\n` +
		`${builtinBlocks}\n`;
	mkdirSync(workflowsDistDir, { recursive: true });
	writeFileSync(workflowsAmbientDts, contents, "utf-8");
	console.log(`Wrote @bastani/workflows ambient bridge -> ${join("dist", "builtin", "workflows", "ambient.d.ts")}`);
}

// Reference the ambient bridge from the package root declarations so packages that
// import @bastani/atomic anywhere (or use `types: ["@bastani/atomic"]`) pick up the
// `@bastani/workflows` ambient module automatically. Idempotent.
function injectWorkflowsAmbientReference(): void {
	if (!existsSync(distIndexDts)) {
		console.warn(`Skipping ambient reference injection: ${distIndexDts} not found (run the type build first)`);
		return;
	}
	const original = readFileSync(distIndexDts, "utf-8");
	if (original.includes(workflowsAmbientReference)) {
		return;
	}
	writeFileSync(distIndexDts, `${workflowsAmbientReference}\n${original}`, "utf-8");
	console.log(`Injected workflows ambient reference into ${join("dist", "index.d.ts")}`);
}

rmSync(distBuiltinDir, { recursive: true, force: true });
mkdirSync(distBuiltinDir, { recursive: true });

for (const copy of getCopyPlan()) {
	const destinationDir = join(distBuiltinDir, copy.destinationName);
	copyFilteredDirectory(copy.sourceDir, destinationDir);
	console.log(`Copied builtin ${copy.label} -> ${join("dist", "builtin", basename(destinationDir))}`);
}

// Bundle the workflows extension into a single ESM file so installed builds
// load one module instead of a ~300-file TS graph (multi-second resolve +
// transpile cost per launch on Windows, issue #1962). Only workflows is
// bundled: it references no import.meta.url-relative sibling files, unlike
// e.g. subagents/intercom which spawn sibling .ts entrypoints at runtime.
async function bundleWorkflowsExtension(): Promise<void> {
	const entry = join(workflowsDistDir, "src", "extension", "index.ts");
	const outfile = join(workflowsDistDir, "src", "extension", "index.bundle.mjs");
	const result = await Bun.build({
		entrypoints: [entry],
		target: "node",
		format: "esm",
		external: HOST_PROVIDED_EXTERNALS,
	});
	const output = result.outputs[0];
	if (!result.success || output === undefined) {
		throw new Error(`Failed to bundle workflows extension: ${result.logs.map((log) => log.message).join("\n")}`);
	}
	writeFileSync(outfile, await output.text(), "utf-8");

	const packageJsonPath = join(workflowsDistDir, "package.json");
	const pkg = JSON.parse(readFileSync(packageJsonPath, "utf-8")) as Record<string, unknown>;
	const manifest = pkg.pi as { extensions?: string[] } | undefined;
	if (!manifest?.extensions?.length) {
		throw new Error(`Expected pi.extensions in ${packageJsonPath}`);
	}
	manifest.extensions = ["./src/extension/index.bundle.mjs"];
	writeFileSync(packageJsonPath, `${JSON.stringify(pkg, null, 2)}\n`, "utf-8");
	console.log(`Bundled @bastani/workflows extension -> ${join("dist", "builtin", "workflows", "src", "extension", "index.bundle.mjs")}`);
}

// Issue #1208: derive externally-resolvable @bastani/workflows types from source.
emitWorkflowAuthoringTypes();
pruneRawWorkflowAuthoringSources();
writeWorkflowsAmbientDeclaration();
injectWorkflowsAmbientReference();

// Issue #1962: ship the workflows extension prebundled for fast startup.
await bundleWorkflowsExtension();
