# $XDG_CONFIG_HOME/k9s/config.yaml
k9s:
  # Enable periodic refresh of resource browser windows. Default false
  liveViewAutoRefresh: true
  # The path to screen dump. Default: '%temp_dir%/k9s-screens-%username%' (k9s info)
  screenDumpDir: /tmp/dumps
  # Represents ui poll intervals. Default 2secs
  refreshRate: 2
  # Number of retries once the connection to the api-server is lost. Default 15.
  maxConnRetry: 5
  # Indicates whether modification commands like delete/kill/edit are disabled. Default is false
  readOnly: false
  # Toggles whether k9s should exit when CTRL-C is pressed. When set to true, you will need to exist k9s via the :quit command. Default is false.
  noExitOnCtrlC: false
  #UI settings
  ui:
    # Enable mouse support. Default false
    enableMouse: false
    # Set to true to hide K9s header. Default false
    headless: false
    # Set to true to hide the K9S logo Default false
    logoless: false
    # Set to true to hide K9s crumbs. Default false
    crumbsless: false
    noIcons: false
    # Toggles reactive UI. This option provide for watching on disk artifacts changes and update the UI live Defaults to false.
    reactive: true
    # By default all contexts wil use the dracula skin unless explicitly overridden in the context config file.
    skin: catppuccin-mocha # => assumes the file skins/dracula.yaml is present in the  $XDG_DATA_HOME/k9s/skins directory
    # Allows to set certain views default fullscreen mode. (yaml, helm history, describe, value_extender, details, logs) Default false
    defaultsToFullScreen: true
  # Toggles icons display as not all terminal support these chars.
  noIcons: false
  # Toggles whether k9s should check for the latest revision from the Github repository releases. Default is false.
  skipLatestRevCheck: false
  # When altering kubeconfig or using multiple kube configs, k9s will clean up clusters configurations that are no longer in use. Setting this flag to true will keep k9s from cleaning up inactive cluster configs. Defaults to false.
  keepMissingClusters: false
  # Logs configuration
  logger:
    tail: 200
    buffer: 500
    sinceSeconds: 300 # => tail the last 5 mins.
    textWrap: true
    showTime: false
  shellPod:
    image: killerAdmin
    namespace: default
    limits:
      cpu: 100m
      memory: 100Mi
    tty: true
