version: '3'

tasks:
  default:
    desc: Show help information
    cmds:
      - task -l
    silent: true
    
  nvim-run-local:
    desc: Run Neovim with local configuration
    silent: true
    cmds:
      - NEOVIM_LUA_DIR=$(pwd)/lua nvim -u init.lua --cmd "set runtimepath+=$(pwd)"
    usage: |
      Run Neovim with the local configuration:
        task nvim-run-local