version: '3'

tasks:
  default:
    desc: Show help information
    cmds:
      - task -l
    silent: true
      
  nvim-run-local:
    desc: Run Neovim with local configuration (isolated)
    silent: true
    cmds:
      - >
        NVIM_APPNAME=nvim-test XDG_CONFIG_HOME=/tmp/nvim-test XDG_DATA_HOME=/tmp/nvim-test XDG_STATE_HOME=/tmp/nvim-test XDG_CACHE_HOME=/tmp/nvim-test nvim -u ./init.lua
    usage: |
      Run Neovim with the local configuration (isolated environment):
        task nvim-run-local