version: '3'

tasks:
  default:
    desc: Show help information
    cmds:
      - task -l
    silent: true
      
  nvim-run-local:
    desc: Run Neovim with local configuration (isolated)
    silent: true
    cmds:
      - >
        rm -rf /tmp/nvim-tmp
        XDG_CONFIG_HOME=/tmp/nvim-tmp XDG_DATA_HOME=/tmp/nvim-tmp nvim -u init.lua
    usage: |
      Run Neovim with the local configuration (isolated environment):
        task nvim-run-local