;;; mail.el --- Mail integration checks -*- lexical-binding: t; -*-
(require 'ert)
(setq sysinit-mail-accounts '(("test@example.com" "/tmp/personal" "personal")
                              ("work@example.com" "/tmp/work" "work"))
      sysinit-mail-palette '((base00 . "#181818") (base03 . "#585858") (base06 . "#e8e8e8")
                             (base07 . "#f8f8f8") (base08 . "#ab4642") (base09 . "#dc9656")
                             (base0A . "#f7ca88") (base0B . "#a1b56c") (base0C . "#86c1b9")
                             (base0E . "#ba8baf") (base0F . "#a16946") (base05 . "#d8d8d8") (base04 . "#b8b8b8") (base01 . "#282828")
                             (base02 . "#383838") (base0D . "#7cafc2"))
      sysinit-mail-chafa-command (executable-find "chafa")
      sysinit-mail-sync-command (executable-find "true"))
(load (getenv "MAIL_CONFIG"))
;; Notmuch forces cwd to ~, which is absent in the Nix build sandbox.
(dolist (pair '((notmuch--make-process . make-process)
                (notmuch--call-process . call-process)
                (notmuch--call-process-region . call-process-region)
                (notmuch--process-lines . process-lines)))
  (advice-add (car pair) :override (cdr pair)))
(setq message-auto-save-directory temporary-file-directory)


(defun mail-test-command (&rest args)
  (with-temp-buffer
    (should (= 0 (apply #'call-process "notmuch" nil t nil args)))
    (string-trim (buffer-string))))

(defun mail-test-wait ()
  (while (get-buffer-process (current-buffer))
    (accept-process-output nil 0.1)))

(advice-add 'sysinit-mail-tag :after (lambda (&rest _) (mail-test-wait)))

(ert-deftest mail-category-bulk-actions ()
  (let* ((root (make-temp-file "mail-test-" t))
         (config (expand-file-name "config" root))
         (process-environment (copy-sequence process-environment)))
    (unwind-protect
        (progn
          (setenv "NOTMUCH_CONFIG" config)
          (with-temp-file config
            (insert (format "[database]\npath=%s/mail\n[user]\nname=Test\nprimary_email=test@example.com\n[new]\ntags=\n[maildir]\nsynchronize_flags=false\n" root)))
          (dolist (entry '(("one" "personal" "")
                           ("hidden" "personal" "In-Reply-To: <one@example.com>\nReferences: <one@example.com>\n")
                           ("two" "personal" "")
                           ("work" "work" "In-Reply-To: <one@example.com>\nReferences: <one@example.com>\n")))
            (let ((path (expand-file-name (format "mail/%s/mail/cur/%s" (nth 1 entry) (car entry)) root)))
              (make-directory (file-name-directory path) t)
              (with-temp-file path
                (insert (format "From: sender@example.com\nTo: test@example.com\nSubject: %s\nMessage-ID: <%s@example.com>\n%sDate: Wed, 7 Oct 2026 12:00:00 +0000\n\nTest message\n"
                                (if (equal (car entry) "hidden") "Re: one" (car entry))
                                (car entry) (nth 2 entry))))))
          (mail-test-command "new")
          (mail-test-command "tag" "+inbox" "+unread" "+personal" "--" "*")
          (mail-test-command "tag" "-personal" "+promotions" "--" "id:hidden@example.com")
          (with-temp-buffer
            (notmuch-hello-mode)
            (should (commandp (key-binding (kbd "g1")))))
          (sysinit-mail-view "1")
          (mail-test-wait)
          (should (commandp (key-binding (kbd "SPC a"))))
          (should (eq evil-state 'normal))
          (should (eq (key-binding (kbd "j")) #'notmuch-search-next-thread))
          (should (eq (key-binding (kbd "e")) #'sysinit-mail-archive))
          (sysinit-mail-view "2")
          (mail-test-wait)
          (sysinit-mail-search "subject:two")
          (mail-test-wait)
          (notmuch-refresh-this-buffer)
          (mail-test-wait)
          (should sysinit-mail-filtered-p)
          (should (equal sysinit-mail-current-view "2"))
          (sysinit-mail-clear-search)
          (mail-test-wait)
          (should (string-match-p "tag:promotions" notmuch-search-query-string))
          (sysinit-mail-view "1")
          (mail-test-wait)
          (sysinit-mail-search "subject:two")
          (mail-test-wait)
          (should sysinit-mail-filtered-p)
          (call-interactively (key-binding (kbd "<escape>")))
          (mail-test-wait)
          (should-not sysinit-mail-filtered-p)
          (should (equal notmuch-search-query-string
                         "path:personal/** and (tag:inbox and tag:personal)"))
          (sysinit-mail-search "subject:two")
          (mail-test-wait)
          (sysinit-mail-tree)
          (mail-test-wait)
          (should sysinit-mail-filtered-p)
          (sysinit-mail-clear-search)
          (mail-test-wait)
          (should-not sysinit-mail-filtered-p)
          (sysinit-mail-tree)
          (mail-test-wait)
          (should (eq major-mode 'notmuch-tree-mode))
          (should notmuch-tree-outline-mode)
          (let (ids)
            (goto-char (point-min))
            (while (< (point) (point-max))
              (when-let* ((id (notmuch-tree-get-message-id t))) (push id ids))
              (forward-line 1))
            (should (equal (sort ids #'string<) '("one@example.com" "two@example.com"))))
          (goto-char (point-min))
          (evil-visual-line)
          (call-interactively (key-binding (kbd "t")))
          (should (equal "3" (mail-test-command "count" "tag:unread")))
          (call-interactively (key-binding (kbd "C-a")))
          (should (eq (key-binding (kbd "SPC m T")) #'sysinit-mail-toggle-read))
          (execute-kbd-macro (kbd "SPC m T"))
          (should (equal "2" (mail-test-command "count" "tag:unread")))
          (sysinit-mail-select-all)
          (call-interactively (key-binding (kbd "t")))
          (should (equal "4" (mail-test-command "count" "tag:unread")))
          (sysinit-mail-select-all)
          (sysinit-mail-read)
          (should (equal "2" (mail-test-command "count" "tag:unread")))
          (sysinit-mail-select-all)
          (sysinit-mail-unread)
          (should (equal "4" (mail-test-command "count" "tag:unread")))
          (sysinit-mail-view "1")
          (mail-test-wait)
          (goto-char (point-min))
          (evil-visual-line)
          (call-interactively (key-binding (kbd "t")))
          (should (equal "3" (mail-test-command "count" "tag:unread")))
          (call-interactively (key-binding (kbd "C-a")))
          (should (eq (key-binding (kbd "SPC m T")) #'sysinit-mail-toggle-read))
          (execute-kbd-macro (kbd "SPC m T"))
          (should (equal "2" (mail-test-command "count" "tag:unread")))
          (sysinit-mail-select-all)
          (call-interactively (key-binding (kbd "t")))
          (should (equal "4" (mail-test-command "count" "tag:unread")))
          (sysinit-mail-select-all)
          (sysinit-mail-read)
          (should (equal "2" (mail-test-command "count" "tag:unread")))
          (sysinit-mail-select-all)
          (sysinit-mail-unread)
          (should (equal "4" (mail-test-command "count" "tag:unread")))
          (sysinit-mail-select-all)
          (cl-letf (((symbol-function 'notmuch-read-tag-changes)
                     (lambda (&rest _) '("+TestLabel"))))
            (execute-kbd-macro (kbd ", t")))
          (should (equal "2" (mail-test-command "count" "tag:TestLabel")))
          (sysinit-mail-select-all)
          (cl-letf (((symbol-function 'notmuch-read-tag-changes)
                     (lambda (&rest _) '("-TestLabel"))))
            (execute-kbd-macro (kbd ", t")))
          (should (equal "0" (mail-test-command "count" "tag:TestLabel")))
          (sysinit-mail-select-all)
          (sysinit-mail-unsubscribe)
          (should (equal "2" (mail-test-command "count" "tag:Unsubscribe")))
          (execute-kbd-macro (kbd ", v a"))
          (should (equal "2" (mail-test-command "count" "tag:inbox")))
          (goto-char (point-min))
          (should-not (notmuch-search-get-result))
          (should (string-match-p "This account has 1 inbox messages" (buffer-string)))
          (should (equal "2" (mail-test-command "count" "tag:inbox and (id:hidden@example.com or id:work@example.com)")))
          (should (equal "4" (mail-test-command "count" "tag:unread")))
          (let ((process (get-process "mail-sync")))
            (when process (while (process-live-p process) (accept-process-output process 0.1)))))
      (dolist (buffer (buffer-list))
        (with-current-buffer buffer
          (when (derived-mode-p 'notmuch-search-mode 'notmuch-tree-mode) (kill-buffer buffer))))
      (delete-directory root t))))

(ert-deftest mail-sender-routing ()
  (with-temp-buffer
    (message-mode)
    (insert "From: Work User <work@example.com>\nTo: nobody@example.com\n\nDraft only")
    (sysinit-mail-send-account)
    (should (equal message-sendmail-extra-arguments '("send" "--quiet" "--path" "/tmp/work")))
    (erase-buffer)
    (insert "From: unknown@example.com\n\nDraft only")
    (should-error (sysinit-mail-send-account) :type 'user-error)))

(ert-deftest mail-category-label-names ()
  (should (equal (plist-get (cl-find "Unsubscribe Success" notmuch-saved-searches
                                   :key (lambda (entry) (plist-get entry :name)) :test #'equal) :query)
                 "path:personal/** and (tag:\"Unsubscribe Success\")")))

(ert-deftest mail-account-switch-and-vim-keys ()
  (let ((sysinit-mail-account (car sysinit-mail-accounts))
        (notmuch-saved-searches nil)
        (user-mail-address nil)
        (notmuch-identities nil))
    (sysinit-mail-configure-account)
    (should (equal (sysinit-mail-scope "tag:inbox or tag:unread")
                   "path:personal/** and (tag:inbox or tag:unread)"))
    (cl-letf (((symbol-function 'completing-read) (lambda (&rest _) "work@example.com"))
              ((symbol-function 'sysinit-mail-open) #'ignore))
      (sysinit-mail-switch-account))
    (should (equal user-mail-address "work@example.com"))
    (should (equal notmuch-identities '("work@example.com")))
    (dolist (view notmuch-saved-searches)
      (should (string-prefix-p "path:work/** and (" (plist-get view :query))))
    (with-temp-buffer
      (notmuch-search-mode)
      (should (eq (key-binding (kbd "SPC a")) #'sysinit-mail-switch-account))
      (should (eq (key-binding (kbd "SPC f g")) #'sysinit-mail-search))
      (should (eq (key-binding (kbd "G")) #'evil-goto-line))
      (should (eq (key-binding (kbd "/")) #'evil-search-forward)))))

(ert-deftest mail-remembers-selected-account ()
  (let* ((root (make-temp-file "mail-state-" t))
         (sysinit-mail-state-file (expand-file-name "email/account" root))
         (sysinit-mail-account (cadr sysinit-mail-accounts))
         (notmuch-saved-searches nil)
         (notmuch-identities nil)
         (user-mail-address nil))
    (unwind-protect
        (progn
          (sysinit-mail-configure-account)
          (should (equal (with-temp-buffer
                           (insert-file-contents sysinit-mail-state-file)
                           (buffer-string)) "work"))
          (should (= (file-modes sysinit-mail-state-file) #o600)))
      (delete-directory root t))))

(ert-deftest mail-category-leader-queries ()
  (let ((sysinit-mail-account (car sysinit-mail-accounts))
        (notmuch-saved-searches nil))
    (sysinit-mail-configure-account)
    (dolist (mode '(notmuch-hello-mode notmuch-search-mode notmuch-show-mode))
      (with-temp-buffer
        (funcall mode)
        (dolist (entry '(("A" . "tag:inbox")
                         ("p" . "tag:inbox and tag:personal")
                         ("r" . "tag:inbox and tag:promotions")
                         ("s" . "tag:inbox and tag:social")
                         ("u" . "tag:inbox and tag:updates")))
          (let (actual)
            (cl-letf (((symbol-function 'notmuch-search)
                       (lambda (query &rest _) (setq actual query))))
              (call-interactively (key-binding (kbd (concat "SPC c" (car entry))))))
            (should (equal actual (sysinit-mail-scope (cdr entry))))))))))

(ert-deftest mail-default-primary-and-autosync ()
  (let ((sysinit-mail-sync-timer nil)
        requested-view)
    (cl-letf (((symbol-function 'sysinit-mail-view)
               (lambda (key) (setq requested-view key))))
      (sysinit-mail-open))
    (should (equal requested-view "1"))
    (unwind-protect
        (progn
          (sysinit-mail-start-autosync)
          (let ((first sysinit-mail-sync-timer))
            (should (timerp first))
            (should (= (timer--repeat-delay first) 60))
            (should (eq (timer--function first) #'sysinit-mail-sync-if-authenticated))
            (sysinit-mail-start-autosync)
            (should-not (memq first timer-list))))
      (cancel-timer sysinit-mail-sync-timer))))

(ert-deftest mail-chafa-preview-local-image ()
  (let ((process-environment (copy-sequence process-environment))
        (message '(:id "image@example.com"
                      :body ((:id 1 :content-type "multipart/mixed"
                                  :content ((:id 2 :content-type "image/png"
                                                 :content-binary nil)))))))
    (setenv "WEZTERM_PANE" nil)
    (setf (plist-get (car (sysinit-mail-image-parts (plist-get message :body))) :content-binary)
          (base64-decode-string "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aX1sAAAAASUVORK5CYII="))
    (unwind-protect
        (with-temp-buffer
          (notmuch-show-mode)
          (cl-letf (((symbol-function 'notmuch-show-get-message-properties) (lambda () message)))
            (sysinit-mail-preview-image))
          (should (get-buffer "*Mail image*"))
          (with-current-buffer "*Mail image*"
            (should (> (buffer-size) 0))
            (should (eq major-mode 'special-mode))))
      (when (get-buffer "*Mail image*") (kill-buffer "*Mail image*")))))

(ert-deftest mail-menus-and-terminal-ui ()
  (should which-key-mode)
  (should vertico-mode)
  (should marginalia-mode)
  (should (memq 'sysinit-mail custom-enabled-themes))
  (should (featurep 'base16-theme))
  (should (featurep 'hydra))
  (should (string-match-p "#d8d8d8" (prin1-to-string (get 'sysinit-mail 'theme-settings))))
  (should window-combination-resize)
  (should vertico-resize)
  (should (equal (face-attribute 'default :background nil t) "unspecified-bg"))
  (dolist (mode '(notmuch-hello-mode notmuch-search-mode notmuch-show-mode notmuch-tree-mode))
    (with-temp-buffer
      (funcall mode)
      (dolist (entry sysinit-mail-leader-actions)
        (should (commandp (key-binding (kbd (concat "SPC " (car entry)))))))
      (should (eq (key-binding (kbd "<escape>")) #'sysinit-mail-clear-search))
      (should (eq (key-binding (kbd "C-u")) #'evil-scroll-up))
      (should (eq (key-binding (kbd "C-d")) #'evil-scroll-down))
      (should (eq (key-binding (kbd "5")) #'digit-argument)))))

(ert-deftest mail-native-html-rendering ()
  (should (libxml-available-p))
  (should (equal (car (notmuch-multipart/alternative-choose
                       nil '("text/plain" "text/html"))) "text/html"))
  (with-temp-buffer
    (insert "<html><body><h1>Reading test</h1><p>Hello <b>reader</b>.</p><ul><li>One item</li></ul><a href='https://example.com'>Example link</a></body></html>")
    (let ((dom (libxml-parse-html-region (point-min) (point-max))))
      (erase-buffer)
      (shr-insert-document dom))
    (should (string-match-p "Reading test" (buffer-string)))
    (should (string-match-p "One item" (buffer-string)))
    (goto-char (point-min))
    (search-forward "Example link")
    (should (equal (get-text-property (1- (point)) 'shr-url) "https://example.com")))
  (with-temp-buffer
    (notmuch-show-mode)
    (cl-letf (((symbol-function 'notmuch-show-refresh-view) #'ignore))
      (sysinit-mail-toggle-html)
      (should (equal (car (notmuch-multipart/alternative-choose
                           nil '("text/plain" "text/html"))) "text/plain"))
      (sysinit-mail-toggle-html)
      (should (equal notmuch-multipart/alternative-discouraged '("text/plain"))))))
