local M = {}

M.plugins = {
	{ "folke/tokyonight.nvim" },
	{ "AlexvZyl/nordic.nvim" },
	{ "EdenEast/nightfox.nvim" },
	{ "shaunsingh/nord.nvim" },
	{ "marko-cerovac/material.nvim" },
	{ "projekt0n/github-nvim-theme" },
	{ "olimorris/onedarkpro.nvim" },
	{ "rebelot/kanagawa.nvim" },
	{ "nyoom-engineering/oxocarbon.nvim" },
	{ "sainnhe/everforest" },
	{ "sainnhe/gruvbox-material" },
	{ "sainnhe/sonokai" },
	{ "Shatur/neovim-ayu" },
	{ "dracula/vim", name = "dracula" },
	{ "Mofiqul/vscode.nvim" },
	{ "tiagovla/tokyodark.nvim" },
	{ "morhetz/gruvbox" },
	{ "mhartington/oceanic-next" },
	{ "glepnir/zephyr-nvim" },
	{ "rafamadriz/neon" },
	{ "savq/melange-nvim" },
	{ "Shatur/neovim-ayu" },
	{ "ray-x/starry.nvim" },
	{ "rmehri01/onenord.nvim" },
	{ "neanias/everforest-nvim" },
	{ "olivercederborg/poimandres.nvim" },
	{ "maxmx03/fluoromachine.nvim" },
	{ "kvrohit/substrata.nvim" },
	{ "NTBBloodbath/sweetie.nvim" },
	{
		"zaldih/themery.nvim",
		lazy = false,
		config = function()
			require("themery").setup({
				themes = {
					"tokyonight-night",
					"tokyonight-storm",
					"tokyonight-moon",
					"nordic",
					"nightfox",
					"duskfox",
					"nordfox",
					"terafox",
					"carbonfox",
					"nord",
					"material-oceanic",
					"material-palenight",
					"github_dark",
					"github_dark_dimmed",
					"github_dark_default",
					"github_dark_high_contrast",
					"onedark",
					"kanagawa",
					"oxocarbon",
					"everforest",
					"gruvbox-material",
					"sonokai",
					"ayu",
					"dracula",
					"vscode",
					"tokyodark",
					"gruvbox",
					"oceanic-next",
					"zephyr",
					"neon",
					"melange",
					"starry",
					"onenord",
					"everforest-nvim",
					"poimandres",
					"fluoromachine",
					"substrata",
					"sweetie",
				},
				livePreview = true,
			})
		end,
	},
}

return M
