gui:
  mouseEvents: false
  nerdFontsVersion: "3"

git:
  paging:
    colorArg: always
    pager: delta --paging=never --hyperlinks --hunk-header-decoration-style=omit
  scrollPastBottom: false
  showCommandLog: false
  showRandomTip: false

customCommands:
  - key: "s"
    context: "files"
    command: "ghcs -t git"
    description: "Suggest commit message (AI)"
    output: popup
    outputTitle: "AI Commit Suggestion"

