{
  pkgs,
  values,
  ...
}:

let
  additionalPackages = values.nix.additionalPackages or [ ];

  allPackages =
    (with pkgs; [
      _1password-cli
      _1password-gui
      ansible
      ansible-lint
      argc
      argocd
      asciinema
      asciinema-agg
      ast-grep
      awk-language-server
      awscli2
      bash
      bash-language-server
      bashInteractive
      cachix
      cargo-watch
      chafa
      checkmake
      codespell
      colima
      copilot-cli
      copilot-language-server
      coreutils
      crossplane-cli
      crush
      cue
      cuelsp
      cupcake-cli
      curl
      cursor-cli
      deadnix
      delta
      delve
      devbox
      diffnav
      direnv
      discordo
      docker
      docker-buildx
      docker-color-output
      docker-compose
      docker-compose-language-service
      docker-credential-helpers
      docker-language-server
      duf
      eslint
      fd
      findutils
      fish
      gettext
      gh
      gh-dash
      git
      git-crypt
      git-filter-repo
      glow
      gnugrep
      gnumake
      gnupg
      gnused
      go
      go-task
      golangci-lint
      gopls
      gum
      helm-ls
      imagemagick
      jq
      jq-lsp
      jqp
      jsonld-cli
      k9s
      krew
      kube-linter
      kubecolor
      kubectl
      kubectx
      kubernetes-helm
      kubernetes-zeitgeist
      kustomize
      lazygit
      libgit2
      lima
      lsp-ai
      lua-language-server
      lua54Packages.cjson
      luajit
      macchina
      meld
      mermaid-cli
      mods
      nerd-fonts.agave
      nerd-fonts.monaspace
      nil
      nix-output-monitor
      nix-prefetch
      nix-prefetch-docker
      nix-prefetch-git
      nix-prefetch-github
      nix-tree
      nix-your-shell
      nixd
      nixfmt
      nodejs_22
      oh-my-posh
      openssh
      pipx
      pkg-config
      postgresql17Packages.pgvector
      postgresql_17
      proselint
      pyright
      python311
      ripgrep
      rustc
      rustup
      sad
      shellcheck
      shfmt
      simple-completion-language-server
      socat
      sshpass
      statix
      stern
      stylua
      taplo
      terraform-ls
      textlint
      tflint
      tflint-plugins.tflint-ruleset-aws
      tfsec
      tig
      tlrc
      typescript
      typescript-language-server
      upbound
      uv
      vale-ls
      vscode-langservers-extracted
      watch
      # weechat-unwrapped
      # weechatScripts.colorize_nicks
      # weechatScripts.edit
      # weechatScripts.multiline
      # weechatScripts.url_hint
      # weechatScripts.wee-slack
      # weechatScripts.weechat-autosort
      # weechatScripts.weechat-grep
      # weechatScripts.weechat-matrix
      wget
      which
      yaml-language-server
      yamllint
      yarn
      yazi
      yq
      zsh
    ])
    ++ additionalPackages;
in
{
  home.packages = allPackages;
}
