{
  pkgs,
  values,
  ...
}:
let
  additionalPackages = values.nix.additionalPackages or [ ];

  baseNixPackages = with pkgs; [
    ansible
    ansible-lint
    argc
    argocd
    asciinema
    asciinema-agg
    ast-grep
    atuin
    awk-language-server
    awscli2
    bashInteractive
    bash-language-server
    caddy
    cargo-watch
    chafa
    checkmake
    codespell
    copilot-cli
    copilot-language-server
    crossplane-cli
    deadnix
    delta
    diffnav
    delve
    direnv
    docker
    docker-compose
    docker-compose-language-service
    docker-language-server
    duf
    eslint
    gettext
    gh
    gh-dash
    git-filter-repo
    glow
    gnupg
    go
    go-task
    golangci-lint
    gopls
    gum
    helm-ls
    intelli-shell
    jetbrains-mono
    jq
    jq-lsp
    jqp
    jsonld-cli
    k9s
    krew
    kube-linter
    kubecolor
    kubectl
    kubernetes-helm
    kustomize
    lazygit
    libgit2
    lua-language-server
    luajit
    macchina
    marksman
    mermaid-cli
    mods
    nil
    nix-output-monitor
    nix-prefetch
    nix-prefetch-docker
    nix-prefetch-git
    nix-prefetch-github
    nix-search-cli
    nix-your-shell
    nixfmt-rfc-style
    nodePackages.fkill-cli
    nodejs_22
    oh-my-posh
    ollama
    openscad
    openscad-lsp
    openssh
    pipx
    pkg-config
    postgresql17Packages.pgvector
    postgresql_17
    proselint
    pyright
    python311
    rustc
    rustup
    sad
    sbarlua
    shellcheck
    shfmt
    simple-completion-language-server
    socat
    sshpass
    statix
    stern
    stylua
    swift
    taplo
    terraform-ls
    textlint
    tflint
    tflint-plugins.tflint-ruleset-aws
    tfsec
    tig
    tlrc
    typescript
    typescript-language-server
    upbound
    uv
    vale-ls
    vivid
    vscode-langservers-extracted
    watch
    yaml-language-server
    yamllint
    yarn
    yazi
    yq
    zig
    zls
    zoxide
  ];

  allNixPackages = baseNixPackages ++ additionalPackages;
in
{
  home.packages = allNixPackages;
}
